# Generated by Django 2.0.6 on 2018-06-21 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_assessmentstudents_gradeyear_medicalrecords_parents_students_subjects_teachers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mobilenumber',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
