# Generated by Django 2.0.6 on 2018-06-21 12:43

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_customuser_mobilenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(blank=True, max_length=64, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='childsname',
            field=models.CharField(blank=True, max_length=30, verbose_name='Childs Name'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='dateofbirth',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='customuser',
            name='dateupdatedbio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='customuser',
            name='dateuserjoined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gradeyear',
            field=models.CharField(choices=[('1', 'GRADE 1'), ('2', 'GRADE 2'), ('3', 'GRADE 3'), ('4', 'GRADE 4'), ('5', 'GRADE 5'), ('6', 'GRADE 6'), ('7', 'GRADE 7'), ('8', 'GRADE 8'), ('9', 'GRADE 9'), ('10', 'GRADE 10')], default=1, max_length=2, verbose_name='Grade Choice'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='usertype',
            field=models.CharField(choices=[('P', 'Parent'), ('T', 'Teacher')], default='P', max_length=2, verbose_name='User Type'),
        ),
        migrations.AddField(
            model_name='medicalrecords',
            name='studentsname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Students'),
        ),
        migrations.AlterField(
            model_name='assessmentstudents',
            name='assessmentinfo',
            field=models.CharField(max_length=30, verbose_name='Assessment Info'),
        ),
        migrations.AlterField(
            model_name='assessmentstudents',
            name='status',
            field=models.CharField(max_length=30, verbose_name='Current Status of Student'),
        ),
        migrations.AlterField(
            model_name='assessmentstudents',
            name='studentsname',
            field=models.CharField(max_length=30, verbose_name='Student Name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='mobilenumber',
            field=models.CharField(blank=True, max_length=30, verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(blank=True, max_length=64, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='gradeyear',
            name='year',
            field=models.CharField(blank=True, max_length=30, verbose_name='Grade Year'),
        ),
        migrations.AlterField(
            model_name='medicalrecords',
            name='accident_injury',
            field=models.CharField(max_length=30, verbose_name='Accident / Injury'),
        ),
        migrations.AlterField(
            model_name='medicalrecords',
            name='currentcondition',
            field=models.CharField(max_length=30, verbose_name='Current Medical Condition'),
        ),
        migrations.AlterField(
            model_name='medicalrecords',
            name='hospitalizationinfo',
            field=models.CharField(max_length=30, verbose_name='Hospitalization Information'),
        ),
        migrations.AlterField(
            model_name='medicalrecords',
            name='illnessinfo',
            field=models.CharField(max_length=30, verbose_name='Illness Information'),
        ),
        migrations.AlterField(
            model_name='medicalrecords',
            name='immunizationinfo',
            field=models.CharField(max_length=30, verbose_name='Immunization Information'),
        ),
        migrations.AlterField(
            model_name='parents',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Parents Name'),
        ),
        migrations.AlterField(
            model_name='parents',
            name='studentsname',
            field=models.CharField(max_length=30, verbose_name='Childs Name'),
        ),
        migrations.AlterField(
            model_name='students',
            name='email',
            field=models.EmailField(max_length=30, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='students',
            name='name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Student Name'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='subjectname',
            field=models.CharField(max_length=30, verbose_name='Subject Name'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='email',
            field=models.EmailField(max_length=30, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Teachers Name'),
        ),
    ]
