# Generated by Django 2.0.6 on 2018-06-21 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20180621_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecords',
            name='studentsname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students_medical_records', to='students.Students'),
        ),
    ]
