# Generated by Django 2.0.6 on 2018-06-21 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20180621_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecords',
            name='studentsname',
        ),
    ]
