# Generated by Django 2.0.6 on 2018-06-21 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_auto_20180621_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecords',
            name='accident_injury',
            field=models.CharField(max_length=30, verbose_name='Accident or Injury'),
        ),
    ]
