# Generated by Django 2.0.6 on 2018-06-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_auto_20180621_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='mobilenumber',
            field=models.IntegerField(blank=True, verbose_name='Mobile Number'),
        ),
    ]
