# Generated by Django 2.0.6 on 2018-06-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_auto_20180621_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gradeyear',
            field=models.CharField(choices=[('G1', 'GRADE 1'), ('G2', 'GRADE 2'), ('G3', 'GRADE 3'), ('G4', 'GRADE 4'), ('G5', 'GRADE 5'), ('G6', 'GRADE 6'), ('G7', 'GRADE 7'), ('G8', 'GRADE 8'), ('G9', 'GRADE 9'), ('G10', 'GRADE 10')], default='G1', max_length=10, verbose_name='Grade Choice'),
        ),
    ]
