# Generated by Django 2.0.6 on 2018-06-23 22:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_auto_20180621_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='applicationtype',
            field=models.CharField(blank=True, choices=[('JH', 'Junior High School Program'), ('GS', 'Grade School Program'), ('SH', 'Senior High School Program'), ('HSP', 'Home Study Program'), ('SPED', 'Special Education Program'), ('CA', 'CASA Program')], default='CA', help_text='Choose Application Program', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='dateofbirth',
            field=models.DateField(default=datetime.date.today, verbose_name='Date of Birth'),
        ),
    ]
