# Generated by Django 2.0.6 on 2018-06-26 03:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_auto_20180624_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('registered_on', models.DateField()),
                ('account_type', models.CharField(choices=[('R', 'Regular'), ('G', 'Gold'), ('P', 'Platinum')], default='R', max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='gradeyear',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='applicationtype',
            field=models.CharField(blank=True, choices=[('SH', 'Senior High School Program'), ('JH', 'Junior High School Program'), ('GS', 'Grade School Program'), ('CA', 'CASA Program'), ('SPED', 'Special Education Program')], default='CA', help_text='Choose Application Program', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='childsname',
            field=models.CharField(max_length=30, verbose_name='Childs Name'),
        ),
        migrations.AlterField(
            model_name='students',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students_name', to=settings.AUTH_USER_MODEL),
        ),
    ]
