# Generated by Django 2.0.6 on 2018-06-26 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_auto_20180626_0314'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='applicationtype',
            field=models.CharField(blank=True, choices=[('GS', 'Grade School Program'), ('SPED', 'Special Education Program'), ('CA', 'CASA Program'), ('JH', 'Junior High School Program'), ('SH', 'Senior High School Program')], default='CA', help_text='Choose Application Program', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='childsname',
            field=models.CharField(max_length=30, verbose_name='Students'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='mobilenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='+639171238888', max_length=128, verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='students',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
