# Generated by Django 2.0.6 on 2018-06-26 12:43

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_auto_20180626_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='applicationtype',
            field=models.CharField(blank=True, choices=[('JH', 'Junior High School Program'), ('SPED', 'Special Education Program'), ('CA', 'CASA Program'), ('SH', 'Senior High School Program'), ('GS', 'Grade School Program')], default='CA', help_text='Choose Application Program', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='childsname',
            field=models.CharField(max_length=30, verbose_name='Childs Name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='mobilenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='MOBILE FORMAT : +639178888888', max_length=128),
        ),
        migrations.AlterField(
            model_name='students',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Students Name'),
        ),
    ]
