# Generated by Django 2.0.6 on 2018-06-27 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_auto_20180626_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assesmentsstats', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.AssessmentStudents')),
                ('gradeenrolled', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.GradeYear')),
                ('medicalrecords', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.MedicalRecords')),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='applicationtype',
            field=models.CharField(blank=True, choices=[('JH', 'Junior High School Program'), ('GS', 'Grade School Program'), ('SH', 'Senior High School Program'), ('CA', 'CASA Program'), ('SPED', 'Special Education Program')], default='CA', help_text='Choose Application Program', max_length=10),
        ),
        migrations.AddField(
            model_name='classroom',
            name='studentsname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classroom',
            name='teachersname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Teachers'),
        ),
    ]
