# Generated by Django 2.0.6 on 2018-06-27 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0019_auto_20180627_0513'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessmentstudents',
            options={'verbose_name_plural': 'Students Assessments Info'},
        ),
        migrations.AlterModelOptions(
            name='classroom',
            options={'verbose_name_plural': 'Class Room Info'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name_plural': 'Users Information'},
        ),
        migrations.AlterModelOptions(
            name='gradeyear',
            options={'verbose_name_plural': 'Grade Year'},
        ),
        migrations.AlterModelOptions(
            name='medicalrecords',
            options={'verbose_name_plural': 'Parents Information'},
        ),
        migrations.AlterModelOptions(
            name='parents',
            options={'verbose_name_plural': 'Parents Information'},
        ),
        migrations.AlterModelOptions(
            name='students',
            options={'verbose_name_plural': 'Students Information'},
        ),
        migrations.AlterModelOptions(
            name='subjects',
            options={'verbose_name_plural': 'List of Subjects'},
        ),
        migrations.AlterModelOptions(
            name='teachers',
            options={'verbose_name_plural': 'Teachers Info'},
        ),
        migrations.RenameField(
            model_name='classroom',
            old_name='studentsname',
            new_name='applicationenrolled',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='applicationtype',
            field=models.CharField(blank=True, choices=[('GS', 'Grade School Program'), ('CA', 'CASA Program'), ('SH', 'Senior High School Program'), ('SPED', 'Special Education Program'), ('JH', 'Junior High School Program')], default='CA', help_text='Choose Application Program', max_length=10),
        ),
    ]
