# Generated by Django 2.0.6 on 2018-07-01 01:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0021_auto_20180630_0648'),
    ]

    operations = [
        migrations.CreateModel(
            name='Children',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Student Info',
            },
        ),
        migrations.CreateModel(
            name='StudentBio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='gradeyear',
            name='studentslists',
            field=models.ManyToManyField(max_length=64, to='students.Students'),
        ),
        migrations.AddField(
            model_name='teachers',
            name='studentslists',
            field=models.ManyToManyField(max_length=64, to='students.Students'),
        ),
        migrations.AddField(
            model_name='teachers',
            name='subjectlist',
            field=models.ManyToManyField(max_length=64, to='students.Subjects'),
        ),
        migrations.AlterField(
            model_name='assessmentstudents',
            name='assessmentinfo',
            field=models.CharField(max_length=64, verbose_name='Assessment Info'),
        ),
        migrations.AlterField(
            model_name='assessmentstudents',
            name='status',
            field=models.CharField(max_length=64, verbose_name='Current Status of Student'),
        ),
        migrations.AlterField(
            model_name='assessmentstudents',
            name='studentsname',
            field=models.CharField(max_length=64, verbose_name='Student Name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='applicationtype',
            field=models.CharField(blank=True, choices=[('SPED', 'Special Education Program'), ('CA', 'CASA Program'), ('SH', 'Senior High School Program'), ('GS', 'Grade School Program'), ('JH', 'Junior High School Program')], default='CA', help_text='Choose Application Program', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='childsname',
            field=models.CharField(max_length=64, verbose_name='Childs Name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='civilstatus',
            field=models.CharField(blank=True, choices=[('D', 'Divorcee'), ('W', 'Widowed'), ('M', 'Married'), ('SP', 'Single Parent')], default='M', help_text='Please select Civit Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='religion',
            field=models.CharField(blank=True, choices=[('B', 'Buddhist'), ('I', 'INC'), ('M', 'Muslim'), ('C', 'Catholic')], default='C', help_text='Please select your Religion', max_length=30),
        ),
        migrations.AlterField(
            model_name='medicalrecords',
            name='accident_injury',
            field=models.CharField(max_length=64, verbose_name='Accident or Injury'),
        ),
        migrations.AlterField(
            model_name='medicalrecords',
            name='currentcondition',
            field=models.CharField(max_length=64, verbose_name='Current Medical Condition'),
        ),
        migrations.AlterField(
            model_name='medicalrecords',
            name='hospitalizationinfo',
            field=models.CharField(max_length=64, verbose_name='Hospitalization Information'),
        ),
        migrations.AlterField(
            model_name='medicalrecords',
            name='illnessinfo',
            field=models.CharField(max_length=64, verbose_name='Illness Information'),
        ),
        migrations.AlterField(
            model_name='medicalrecords',
            name='immunizationinfo',
            field=models.CharField(max_length=64, verbose_name='Immunization Information'),
        ),
        migrations.AlterField(
            model_name='parents',
            name='name',
            field=models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='subjectname',
            field=models.CharField(max_length=64, verbose_name='Subject Name'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='email',
            field=models.EmailField(max_length=64, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='name',
            field=models.ForeignKey(blank=True, max_length=64, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentbio',
            name='parentsname',
            field=models.ForeignKey(max_length=64, on_delete=django.db.models.deletion.CASCADE, to='students.Parents'),
        ),
        migrations.AddField(
            model_name='studentbio',
            name='studentname',
            field=models.ForeignKey(max_length=64, on_delete=django.db.models.deletion.CASCADE, to='students.Students'),
        ),
        migrations.AddField(
            model_name='studentbio',
            name='subjects',
            field=models.ForeignKey(max_length=64, on_delete=django.db.models.deletion.CASCADE, to='students.Subjects'),
        ),
        migrations.AddField(
            model_name='studentbio',
            name='teachersname',
            field=models.ForeignKey(max_length=64, on_delete=django.db.models.deletion.CASCADE, to='students.Teachers'),
        ),
        migrations.AddField(
            model_name='children',
            name='childsname',
            field=models.OneToOneField(max_length=30, on_delete=django.db.models.deletion.CASCADE, related_name='children_parents', to='students.Parents'),
        ),
        migrations.AddField(
            model_name='parents',
            name='children',
            field=models.ManyToManyField(max_length=64, to='students.Children'),
        ),
    ]
