# Generated by Django 2.0.6 on 2018-07-01 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0022_auto_20180701_0113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parents',
            old_name='name',
            new_name='userparents',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='applicationtype',
            field=models.CharField(blank=True, choices=[('CA', 'CASA Program'), ('JH', 'Junior High School Program'), ('GS', 'Grade School Program'), ('SPED', 'Special Education Program'), ('SH', 'Senior High School Program')], default='CA', help_text='Choose Application Program', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='civilstatus',
            field=models.CharField(blank=True, choices=[('M', 'Married'), ('D', 'Divorcee'), ('SP', 'Single Parent'), ('W', 'Widowed')], default='M', help_text='Please select Civit Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='religion',
            field=models.CharField(blank=True, choices=[('C', 'Catholic'), ('M', 'Muslim'), ('I', 'INC'), ('B', 'Buddhist')], default='C', help_text='Please select your Religion', max_length=30),
        ),
    ]
