# Generated by Django 2.0.6 on 2018-07-01 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0023_auto_20180701_0151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='children',
            name='childsname',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='childsname',
        ),
        migrations.RemoveField(
            model_name='parents',
            name='children',
        ),
        migrations.AddField(
            model_name='parents',
            name='childsname',
            field=models.CharField(blank=True, max_length=30, verbose_name='Childs Name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='applicationtype',
            field=models.CharField(blank=True, choices=[('JH', 'Junior High School Program'), ('SH', 'Senior High School Program'), ('GS', 'Grade School Program'), ('CA', 'CASA Program'), ('SPED', 'Special Education Program')], default='CA', help_text='Choose Application Program', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='civilstatus',
            field=models.CharField(blank=True, choices=[('SP', 'Single Parent'), ('M', 'Married'), ('D', 'Divorcee'), ('W', 'Widowed')], default='M', help_text='Please select Civit Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='religion',
            field=models.CharField(blank=True, choices=[('M', 'Muslim'), ('I', 'INC'), ('C', 'Catholic'), ('B', 'Buddhist')], default='C', help_text='Please select your Religion', max_length=30),
        ),
        migrations.DeleteModel(
            name='Children',
        ),
    ]
