# Generated by Django 2.0.6 on 2018-07-01 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0024_auto_20180701_0712'),
    ]

    operations = [
        migrations.CreateModel(
            name='Children',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('children', models.ForeignKey(blank=True, max_length=30, on_delete=django.db.models.deletion.CASCADE, to='students.Parents')),
            ],
            options={
                'verbose_name_plural': 'Childrens Information',
            },
        ),
        migrations.AlterField(
            model_name='customuser',
            name='applicationtype',
            field=models.CharField(blank=True, choices=[('GS', 'Grade School Program'), ('CA', 'CASA Program'), ('SPED', 'Special Education Program'), ('JH', 'Junior High School Program'), ('SH', 'Senior High School Program')], default='CA', help_text='Choose Application Program', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='civilstatus',
            field=models.CharField(blank=True, choices=[('SP', 'Single Parent'), ('W', 'Widowed'), ('M', 'Married'), ('D', 'Divorcee')], default='M', help_text='Please select Civit Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='religion',
            field=models.CharField(blank=True, choices=[('C', 'Catholic'), ('M', 'Muslim'), ('B', 'Buddhist'), ('I', 'INC')], default='C', help_text='Please select your Religion', max_length=30),
        ),
    ]
