# Generated by Django 2.0.6 on 2018-07-01 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0025_auto_20180701_0714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentbio',
            name='parentsname',
        ),
        migrations.RemoveField(
            model_name='studentbio',
            name='studentname',
        ),
        migrations.RemoveField(
            model_name='studentbio',
            name='subjects',
        ),
        migrations.RemoveField(
            model_name='studentbio',
            name='teachersname',
        ),
        migrations.AddField(
            model_name='customuser',
            name='childsname',
            field=models.CharField(blank=True, max_length=64, verbose_name='Childs Name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='applicationtype',
            field=models.CharField(blank=True, choices=[('SH', 'Senior High School Program'), ('JH', 'Junior High School Program'), ('CA', 'CASA Program'), ('GS', 'Grade School Program'), ('SPED', 'Special Education Program')], default='CA', help_text='Choose Application Program', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='civilstatus',
            field=models.CharField(blank=True, choices=[('W', 'Widowed'), ('SP', 'Single Parent'), ('D', 'Divorcee'), ('M', 'Married')], default='M', help_text='Please select Civit Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='religion',
            field=models.CharField(blank=True, choices=[('M', 'Muslim'), ('I', 'INC'), ('C', 'Catholic'), ('B', 'Buddhist')], default='C', help_text='Please select your Religion', max_length=30),
        ),
        migrations.DeleteModel(
            name='StudentBio',
        ),
    ]
