# Generated by Django 2.0.6 on 2018-07-02 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0028_auto_20180701_0816'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterBuildingActivities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traitsname', models.CharField(max_length=64, verbose_name='Traits')),
            ],
        ),
        migrations.AlterModelOptions(
            name='subjects',
            options={'verbose_name_plural': 'Sujects List'},
        ),
        migrations.RemoveField(
            model_name='gradeyear',
            name='studentslists',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='applicationtype',
            field=models.CharField(blank=True, choices=[('GS', 'Grade School Program'), ('CA', 'CASA Program'), ('JH', 'Junior High School Program'), ('SH', 'Senior High School Program'), ('SPED', 'Special Education Program')], default='CA', help_text='Choose Application Program', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='civilstatus',
            field=models.CharField(blank=True, choices=[('M', 'Married'), ('D', 'Divorcee'), ('SP', 'Single Parent'), ('W', 'Widowed')], default='M', help_text='Please select Civit Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='religion',
            field=models.CharField(blank=True, choices=[('M', 'Muslim'), ('I', 'INC'), ('B', 'Buddhist'), ('C', 'Catholic')], default='C', help_text='Please select your Religion', max_length=30),
        ),
    ]
