# Generated by Django 2.0.6 on 2018-07-02 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0029_auto_20180702_0100'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentBio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gradeyear', models.OneToOneField(max_length=30, on_delete=django.db.models.deletion.CASCADE, related_name='grade_year', to='students.GradeYear')),
                ('parentsname', models.ForeignKey(max_length=64, on_delete=django.db.models.deletion.CASCADE, related_name='parentsname', to='students.Parents')),
                ('studentname', models.ForeignKey(max_length=64, on_delete=django.db.models.deletion.CASCADE, related_name='childsname', to='students.Students')),
                ('subjectinfo', models.ManyToManyField(max_length=64, related_name='students_subjects', to='students.Subjects')),
                ('teachersname', models.ForeignKey(max_length=64, on_delete=django.db.models.deletion.CASCADE, related_name='teachers_name', to='students.Teachers')),
            ],
        ),
        migrations.AlterModelOptions(
            name='characterbuildingactivities',
            options={'verbose_name_plural': 'Character Building Activities'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='applicationtype',
            field=models.CharField(blank=True, choices=[('SH', 'Senior High School Program'), ('SPED', 'Special Education Program'), ('GS', 'Grade School Program'), ('JH', 'Junior High School Program'), ('CA', 'CASA Program')], default='CA', help_text='Choose Application Program', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='civilstatus',
            field=models.CharField(blank=True, choices=[('W', 'Widowed'), ('D', 'Divorcee'), ('SP', 'Single Parent'), ('M', 'Married')], default='M', help_text='Please select Civit Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='religion',
            field=models.CharField(blank=True, choices=[('I', 'INC'), ('C', 'Catholic'), ('B', 'Buddhist'), ('M', 'Muslim')], default='C', help_text='Please select your Religion', max_length=30),
        ),
    ]
