# Generated by Django 2.0.6 on 2018-07-02 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0030_auto_20180702_0127'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssessmentStudents',
        ),
        migrations.DeleteModel(
            name='CharacterBuildingActivities',
        ),
        migrations.RemoveField(
            model_name='children',
            name='children',
        ),
        migrations.DeleteModel(
            name='MedicalRecords',
        ),
        migrations.RemoveField(
            model_name='parents',
            name='userparents',
        ),
        migrations.RemoveField(
            model_name='studentbio',
            name='gradeyear',
        ),
        migrations.RemoveField(
            model_name='studentbio',
            name='parentsname',
        ),
        migrations.RemoveField(
            model_name='studentbio',
            name='studentname',
        ),
        migrations.RemoveField(
            model_name='studentbio',
            name='subjectinfo',
        ),
        migrations.RemoveField(
            model_name='studentbio',
            name='teachersname',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='studentslists',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='subjectlist',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='applicationtype',
            field=models.CharField(blank=True, choices=[('GS', 'Grade School Program'), ('CA', 'CASA Program'), ('SPED', 'Special Education Program'), ('JH', 'Junior High School Program'), ('SH', 'Senior High School Program')], default='CA', help_text='Choose Application Program', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='civilstatus',
            field=models.CharField(blank=True, choices=[('SP', 'Single Parent'), ('W', 'Widowed'), ('D', 'Divorcee'), ('M', 'Married')], default='M', help_text='Please select Civit Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(blank=True, max_length=64, verbose_name='Complete Name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='religion',
            field=models.CharField(blank=True, choices=[('I', 'INC'), ('M', 'Muslim'), ('C', 'Catholic'), ('B', 'Buddhist')], default='C', help_text='Please select your Religion', max_length=30),
        ),
        migrations.DeleteModel(
            name='Children',
        ),
        migrations.DeleteModel(
            name='GradeYear',
        ),
        migrations.DeleteModel(
            name='Parents',
        ),
        migrations.DeleteModel(
            name='StudentBio',
        ),
        migrations.DeleteModel(
            name='Students',
        ),
        migrations.DeleteModel(
            name='Subjects',
        ),
        migrations.DeleteModel(
            name='Teachers',
        ),
    ]
