# Generated by Django 2.0.6 on 2018-07-02 02:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0031_auto_20180702_0206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Parents Information',
            },
        ),
        migrations.AlterField(
            model_name='customuser',
            name='applicationtype',
            field=models.CharField(blank=True, choices=[('CA', 'CASA Program'), ('GS', 'Grade School Program'), ('JH', 'Junior High School Program'), ('SH', 'Senior High School Program'), ('SPED', 'Special Education Program')], default='CA', help_text='Choose Application Program', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='religion',
            field=models.CharField(blank=True, choices=[('C', 'Catholic'), ('I', 'INC'), ('M', 'Muslim'), ('B', 'Buddhist')], default='C', help_text='Please select your Religion', max_length=30),
        ),
        migrations.AddField(
            model_name='parents',
            name='childsname',
            field=models.OneToOneField(max_length=64, on_delete=django.db.models.deletion.CASCADE, related_name='childs_name', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parents',
            name='parentsname',
            field=models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, related_name='parents_nameinfo', to=settings.AUTH_USER_MODEL),
        ),
    ]
