# Generated by Django 2.0.6 on 2018-07-02 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0034_auto_20180702_0216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='usertype',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='applicationtype',
            field=models.CharField(blank=True, choices=[('CA', 'CASA Program'), ('JH', 'Junior High School Program'), ('SH', 'Senior High School Program'), ('GS', 'Grade School Program'), ('SPED', 'Special Education Program')], default='CA', help_text='Choose Application Program', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='civilstatus',
            field=models.CharField(blank=True, choices=[('M', 'Married'), ('D', 'Divorcee'), ('SP', 'Single Parent'), ('W', 'Widowed')], default='M', help_text='Please select Civit Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='religion',
            field=models.CharField(blank=True, choices=[('M', 'Muslim'), ('C', 'Catholic'), ('I', 'INC'), ('B', 'Buddhist')], default='C', help_text='Please select your Religion', max_length=30),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='teachersname',
            field=models.CharField(max_length=64, verbose_name='Teachers Name'),
        ),
    ]
