# Generated by Django 2.0.6 on 2018-07-02 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0036_auto_20180702_0225'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=30, verbose_name='Grade Year')),
            ],
            options={
                'verbose_name_plural': 'Grade Year',
            },
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectname', models.CharField(max_length=64, verbose_name='Subject Name')),
            ],
            options={
                'verbose_name_plural': 'Sujects List',
            },
        ),
        migrations.AlterField(
            model_name='customuser',
            name='applicationtype',
            field=models.CharField(blank=True, choices=[('SH', 'Senior High School Program'), ('SPED', 'Special Education Program'), ('JH', 'Junior High School Program'), ('GS', 'Grade School Program'), ('CA', 'CASA Program')], default='CA', help_text='Choose Application Program', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='civilstatus',
            field=models.CharField(blank=True, choices=[('D', 'Divorcee'), ('W', 'Widowed'), ('SP', 'Single Parent'), ('M', 'Married')], default='M', help_text='Please select Civit Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='religion',
            field=models.CharField(blank=True, choices=[('C', 'Catholic'), ('I', 'INC'), ('M', 'Muslim'), ('B', 'Buddhist')], default='C', help_text='Please select your Religion', max_length=30),
        ),
    ]
