# Generated by Django 2.0.6 on 2018-07-02 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0037_auto_20180702_0227'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterBuildingActivities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traitsname', models.CharField(max_length=64, verbose_name='Traits')),
            ],
            options={
                'verbose_name_plural': 'Character Building Activities',
            },
        ),
        migrations.AlterField(
            model_name='customuser',
            name='applicationtype',
            field=models.CharField(blank=True, choices=[('SPED', 'Special Education Program'), ('CA', 'CASA Program'), ('SH', 'Senior High School Program'), ('JH', 'Junior High School Program'), ('GS', 'Grade School Program')], default='CA', help_text='Choose Application Program', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='civilstatus',
            field=models.CharField(blank=True, choices=[('W', 'Widowed'), ('SP', 'Single Parent'), ('M', 'Married'), ('D', 'Divorcee')], default='M', help_text='Please select Civit Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='religion',
            field=models.CharField(blank=True, choices=[('I', 'INC'), ('B', 'Buddhist'), ('M', 'Muslim'), ('C', 'Catholic')], default='C', help_text='Please select your Religion', max_length=30),
        ),
    ]
