# Generated by Django 2.0.6 on 2018-07-02 03:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0038_auto_20180702_0235'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, verbose_name='Students Name')),
                ('currentcondition', models.CharField(max_length=64, verbose_name='Current Medical Condition')),
                ('illnessinfo', models.CharField(max_length=64, verbose_name='Illness Information')),
                ('hospitalizationinfo', models.CharField(max_length=64, verbose_name='Hospitalization Information')),
                ('accident_injury', models.CharField(max_length=64, verbose_name='Accident or Injury')),
                ('immunizationinfo', models.CharField(max_length=64, verbose_name='Immunization Information')),
            ],
            options={
                'verbose_name_plural': 'Medical Records Information',
            },
        ),
        migrations.CreateModel(
            name='StudentBio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gradeyear', models.OneToOneField(max_length=30, on_delete=django.db.models.deletion.CASCADE, related_name='gradeyear_gradeyear', to='students.GradeYear')),
            ],
            options={
                'verbose_name_plural': 'Student Profile',
            },
        ),
        migrations.AlterField(
            model_name='customuser',
            name='applicationtype',
            field=models.CharField(blank=True, choices=[('GS', 'Grade School Program'), ('CA', 'CASA Program'), ('SPED', 'Special Education Program'), ('SH', 'Senior High School Program'), ('JH', 'Junior High School Program')], default='CA', help_text='Choose Application Program', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='civilstatus',
            field=models.CharField(blank=True, choices=[('SP', 'Single Parent'), ('W', 'Widowed'), ('M', 'Married'), ('D', 'Divorcee')], default='M', help_text='Please select Civit Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='religion',
            field=models.CharField(blank=True, choices=[('M', 'Muslim'), ('B', 'Buddhist'), ('I', 'INC'), ('C', 'Catholic')], default='C', help_text='Please select your Religion', max_length=30),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='email',
            field=models.EmailField(default='example@email.com', max_length=64, verbose_name='Email Address'),
        ),
        migrations.AddField(
            model_name='studentbio',
            name='parentsnameinfo',
            field=models.ForeignKey(max_length=64, on_delete=django.db.models.deletion.CASCADE, related_name='customeruser_parents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentbio',
            name='studentname',
            field=models.ForeignKey(max_length=64, on_delete=django.db.models.deletion.CASCADE, related_name='customuser_childsname', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentbio',
            name='subjectinfo',
            field=models.ManyToManyField(max_length=64, related_name='students_subjects', to='students.Subjects'),
        ),
        migrations.AddField(
            model_name='studentbio',
            name='teachersname',
            field=models.ForeignKey(max_length=64, on_delete=django.db.models.deletion.CASCADE, related_name='student_teacher', to='students.Teachers'),
        ),
    ]
