# Generated by Django 2.0.6 on 2018-07-02 04:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0039_auto_20180702_0313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentname', models.CharField(max_length=64, verbose_name='Student Name')),
                ('student_id', models.IntegerField(verbose_name='Student ID')),
                ('birthday', models.DateField(default=datetime.date.today, verbose_name='Date of Birth')),
            ],
            options={
                'verbose_name_plural': 'Student Lists',
            },
        ),
        migrations.AlterModelOptions(
            name='studentbio',
            options={'verbose_name_plural': 'Student Profile BIO'},
        ),
        migrations.AlterModelOptions(
            name='subjects',
            options={'verbose_name_plural': 'Subjects List'},
        ),
        migrations.AddField(
            model_name='teachers',
            name='teachers_id',
            field=models.IntegerField(default='1234', verbose_name='Teachers ID No.'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='applicationtype',
            field=models.CharField(blank=True, choices=[('GS', 'Grade School Program'), ('CA', 'CASA Program'), ('SH', 'Senior High School Program'), ('JH', 'Junior High School Program'), ('SPED', 'Special Education Program')], default='CA', help_text='Choose Application Program', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='civilstatus',
            field=models.CharField(blank=True, choices=[('SP', 'Single Parent'), ('W', 'Widowed'), ('D', 'Divorcee'), ('M', 'Married')], default='M', help_text='Please select Civit Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='religion',
            field=models.CharField(blank=True, choices=[('I', 'INC'), ('B', 'Buddhist'), ('M', 'Muslim'), ('C', 'Catholic')], default='C', help_text='Please select your Religion', max_length=30),
        ),
    ]
