# Generated by Django 2.0.6 on 2018-07-02 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0040_auto_20180702_0412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentbio',
            name='subjectinfo',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='applicationtype',
            field=models.CharField(blank=True, choices=[('GS', 'Grade School Program'), ('CA', 'CASA Program'), ('JH', 'Junior High School Program'), ('SPED', 'Special Education Program'), ('SH', 'Senior High School Program')], default='CA', help_text='Choose Application Program', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='civilstatus',
            field=models.CharField(blank=True, choices=[('SP', 'Single Parent'), ('M', 'Married'), ('W', 'Widowed'), ('D', 'Divorcee')], default='M', help_text='Please select Civit Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='religion',
            field=models.CharField(blank=True, choices=[('B', 'Buddhist'), ('M', 'Muslim'), ('C', 'Catholic'), ('I', 'INC')], default='C', help_text='Please select your Religion', max_length=30),
        ),
    ]
