# Generated by Django 2.0.6 on 2018-07-02 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0042_auto_20180702_0447'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentbio',
            name='subjects',
            field=models.ManyToManyField(to='students.Subjects'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='applicationtype',
            field=models.CharField(blank=True, choices=[('SPED', 'Special Education Program'), ('JH', 'Junior High School Program'), ('SH', 'Senior High School Program'), ('GS', 'Grade School Program'), ('CA', 'CASA Program')], default='CA', help_text='Choose Application Program', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='civilstatus',
            field=models.CharField(blank=True, choices=[('W', 'Widowed'), ('SP', 'Single Parent'), ('M', 'Married'), ('D', 'Divorcee')], default='M', help_text='Please select Civit Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='religion',
            field=models.CharField(blank=True, choices=[('I', 'INC'), ('M', 'Muslim'), ('B', 'Buddhist'), ('C', 'Catholic')], default='C', help_text='Please select your Religion', max_length=30),
        ),
    ]
