# Generated by Django 2.0.6 on 2018-07-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0044_auto_20180702_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='classgroup',
        ),
        migrations.AddField(
            model_name='students',
            name='groupinfo',
            field=models.CharField(blank=True, choices=[('CM', 'CASA AM'), ('G9', 'GRADE 9'), ('G2', 'GRADE 2'), ('G6', 'GRADE 6'), ('PG', 'PLAY GROUP'), ('G4', 'GRADE 4'), ('G7', 'GRADE 7'), ('CA', 'CASA AFTERNOON 1:30'), ('G5', 'GRADE 5'), ('G8', 'GRADE 8'), ('G10', 'GRADE 10'), ('G1', 'GRADE 1'), ('G3', 'GRADE 3')], default='CM', help_text='Choose Group for Students', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='applicationtype',
            field=models.CharField(blank=True, choices=[('SH', 'Senior High School Program'), ('SPED', 'Special Education Program'), ('CA', 'CASA Program'), ('JH', 'Junior High School Program'), ('GS', 'Grade School Program')], default='CA', help_text='Choose Application Program', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='civilstatus',
            field=models.CharField(blank=True, choices=[('D', 'Divorcee'), ('SP', 'Single Parent'), ('W', 'Widowed'), ('M', 'Married')], default='M', help_text='Please select Civit Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='religion',
            field=models.CharField(blank=True, choices=[('M', 'Muslim'), ('B', 'Buddhist'), ('I', 'INC'), ('C', 'Catholic')], default='C', help_text='Please select your Religion', max_length=30),
        ),
    ]
