# Generated by Django 2.0.6 on 2018-07-02 11:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0045_auto_20180702_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='birthday',
            field=models.DateField(default=datetime.date.today, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='applicationtype',
            field=models.CharField(blank=True, choices=[('GS', 'Grade School Program'), ('SPED', 'Special Education Program'), ('CA', 'CASA Program'), ('SH', 'Senior High School Program'), ('JH', 'Junior High School Program')], default='CA', help_text='Choose Application Program', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='civilstatus',
            field=models.CharField(blank=True, choices=[('W', 'Widowed'), ('SP', 'Single Parent'), ('D', 'Divorcee'), ('M', 'Married')], default='M', help_text='Please select Civit Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='religion',
            field=models.CharField(blank=True, choices=[('C', 'Catholic'), ('B', 'Buddhist'), ('M', 'Muslim'), ('I', 'INC')], default='C', help_text='Please select your Religion', max_length=30),
        ),
        migrations.AlterField(
            model_name='students',
            name='groupinfo',
            field=models.CharField(blank=True, choices=[('TEP-GR2', 'TEACH PM GRADE 2'), ('G8', 'GRADE 8'), ('G4', 'GRADE 4'), ('TEP-GR2', 'TEACH PM GRADE 3'), ('G6', 'GRADE 6'), ('TEA', 'TEACH AM'), ('G5', 'GRADE 5'), ('TEP', 'TEACH PM'), ('CA', 'CASA AFTERNOON 1:30'), ('G9', 'GRADE 9'), ('G10', 'GRADE 10'), ('G1', 'GRADE 1'), ('G2', 'GRADE 2'), ('CM', 'CASA AM'), ('PG', 'PLAY GROUP'), ('G3', 'GRADE 3'), ('TEP-GR1', 'TEACH PM GRADE 1'), ('G7', 'GRADE 7')], default='CM', help_text='Choose Group for Students', max_length=10),
        ),
    ]
