# Generated by Django 2.0.6 on 2018-07-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0046_auto_20180702_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='rolegroup',
            field=models.CharField(blank=True, choices=[('F', 'FACULTY'), ('SH', 'SCHOOL HEAD'), ('S', 'STAFF')], default='F', help_text='Please choose Role / Duty', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='applicationtype',
            field=models.CharField(blank=True, choices=[('SH', 'Senior High School Program'), ('GS', 'Grade School Program'), ('SPED', 'Special Education Program'), ('CA', 'CASA Program'), ('JH', 'Junior High School Program')], default='CA', help_text='Choose Application Program', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='civilstatus',
            field=models.CharField(blank=True, choices=[('SP', 'Single Parent'), ('D', 'Divorcee'), ('M', 'Married'), ('W', 'Widowed')], default='M', help_text='Please select Civit Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='religion',
            field=models.CharField(blank=True, choices=[('M', 'Muslim'), ('I', 'INC'), ('B', 'Buddhist'), ('C', 'Catholic')], default='C', help_text='Please select your Religion', max_length=30),
        ),
        migrations.AlterField(
            model_name='students',
            name='groupinfo',
            field=models.CharField(blank=True, choices=[('G1', 'GRADE 1'), ('G5', 'GRADE 5'), ('G4', 'GRADE 4'), ('G10', 'GRADE 10'), ('G7', 'GRADE 7'), ('TEA', 'TEACH AM'), ('G6', 'GRADE 6'), ('G9', 'GRADE 9'), ('TEP-GR2', 'TEACH PM GRADE 3'), ('TEP-GR1', 'TEACH PM GRADE 1'), ('CM', 'CASA AM'), ('G3', 'GRADE 3'), ('G2', 'GRADE 2'), ('G8', 'GRADE 8'), ('TEP', 'TEACH PM'), ('TEP-GR2', 'TEACH PM GRADE 2'), ('CA', 'CASA AFTERNOON 1:30'), ('PG', 'PLAY GROUP')], default='CM', help_text='Choose Group for Students', max_length=10),
        ),
    ]
