# Generated by Django 2.0.6 on 2018-07-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0050_auto_20180705_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='applicationtype',
            field=models.CharField(blank=True, choices=[('GS', 'Grade School Program'), ('JH', 'Junior High School Program'), ('SH', 'Senior High School Program'), ('SPED', 'Special Education Program'), ('CA', 'CASA Program')], default='CA', help_text='Choose Application Program', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='civilstatus',
            field=models.CharField(blank=True, choices=[('W', 'Widowed'), ('M', 'Married'), ('D', 'Divorcee'), ('SP', 'Single Parent')], default='M', help_text='Please select Civit Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='religion',
            field=models.CharField(blank=True, choices=[('M', 'Muslim'), ('B', 'Buddhist'), ('I', 'INC'), ('C', 'Catholic')], default='C', help_text='Please select your Religion', max_length=30),
        ),
        migrations.AlterField(
            model_name='students',
            name='groupinfo',
            field=models.CharField(blank=True, choices=[('TEP', 'TEACH PM'), ('PG', 'PLAY GROUP'), ('G4', 'GRADE 4'), ('TEP-GR2', 'TEACH PM GRADE 2'), ('TEP-GR2', 'TEACH PM GRADE 3'), ('G9', 'GRADE 9'), ('G8', 'GRADE 8'), ('CM', 'CASA AM'), ('TEP-GR1', 'TEACH PM GRADE 1'), ('G7', 'GRADE 7'), ('G1', 'GRADE 1'), ('TEA', 'TEACH AM'), ('G5', 'GRADE 5'), ('CA', 'CASA AFTERNOON 1:30'), ('G6', 'GRADE 6'), ('G2', 'GRADE 2'), ('G3', 'GRADE 3'), ('G10', 'GRADE 10')], default='CM', help_text='Choose Group for Students', max_length=10),
        ),
    ]
