# Generated by Django 2.0.6 on 2018-07-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0051_auto_20180705_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='applicationtype',
            field=models.CharField(blank=True, choices=[('SH', 'Senior High School Program'), ('GS', 'Grade School Program'), ('CA', 'CASA Program'), ('JH', 'Junior High School Program'), ('SPED', 'Special Education Program')], default='CA', help_text='Choose Application Program', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='civilstatus',
            field=models.CharField(blank=True, choices=[('M', 'Married'), ('W', 'Widowed'), ('SP', 'Single Parent'), ('D', 'Divorcee')], default='M', help_text='Please select Civit Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='religion',
            field=models.CharField(blank=True, choices=[('C', 'Catholic'), ('I', 'INC'), ('B', 'Buddhist'), ('M', 'Muslim')], default='C', help_text='Please select your Religion', max_length=30),
        ),
        migrations.AlterField(
            model_name='students',
            name='groupinfo',
            field=models.CharField(blank=True, choices=[('TEP', 'TEACH PM'), ('G7', 'GRADE 7'), ('G9', 'GRADE 9'), ('CA', 'CASA AFTERNOON 1:30'), ('PG', 'PLAY GROUP'), ('G8', 'GRADE 8'), ('G4', 'GRADE 4'), ('G5', 'GRADE 5'), ('TEP-GR2', 'TEACH PM GRADE 3'), ('G1', 'GRADE 1'), ('TEP-GR1', 'TEACH PM GRADE 1'), ('CM', 'CASA AM'), ('G3', 'GRADE 3'), ('G10', 'GRADE 10'), ('TEA', 'TEACH AM'), ('TEP-GR2', 'TEACH PM GRADE 2'), ('G2', 'GRADE 2'), ('G6', 'GRADE 6')], default='CM', help_text='Choose Group for Students', max_length=10),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='rolegroup',
            field=models.CharField(blank=True, choices=[('S', 'STAFF'), ('F', 'FACULTY'), ('SH', 'SCHOOL HEAD')], default='F', help_text='Please choose Role / Duty', max_length=10),
        ),
    ]
