# Generated by Django 2.0.6 on 2018-07-10 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0054_auto_20180708_0818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parents',
            name='parentsname',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='religion',
        ),
        migrations.RemoveField(
            model_name='studentbio',
            name='parentsnameinfo',
        ),
        migrations.AddField(
            model_name='customuser',
            name='fathersname',
            field=models.CharField(blank=True, max_length=64, verbose_name='Complete Fathers Name'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='fathersreligion',
            field=models.CharField(blank=True, choices=[('B', 'Buddhist'), ('M', 'Muslim'), ('C', 'Catholic'), ('I', 'INC')], default='C', help_text='Please select Religion', max_length=30),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mothersname',
            field=models.CharField(blank=True, max_length=64, verbose_name='Complete Mothers Name'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mothersreligion',
            field=models.CharField(blank=True, choices=[('B', 'Buddhist'), ('M', 'Muslim'), ('C', 'Catholic'), ('I', 'INC')], default='C', help_text='Please select Religion', max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='applicationtype',
            field=models.CharField(blank=True, choices=[('CA', 'CASA Program'), ('SH', 'Senior High School Program'), ('JH', 'Junior High School Program'), ('GS', 'Grade School Program'), ('SPED', 'Special Education Program')], default='CA', help_text='Choose Application Program', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='civilstatus',
            field=models.CharField(blank=True, choices=[('W', 'Widowed'), ('SP', 'Single Parent'), ('M', 'Married'), ('D', 'Divorcee')], default='M', help_text='Please select Civit Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='students',
            name='groupinfo',
            field=models.CharField(blank=True, choices=[('TEA', 'TEACH AM'), ('G2', 'GRADE 2'), ('G4', 'GRADE 4'), ('G5', 'GRADE 5'), ('G6', 'GRADE 6'), ('G7', 'GRADE 7'), ('G3', 'GRADE 3'), ('G1', 'GRADE 1'), ('G9', 'GRADE 9'), ('TEP-GR2', 'TEACH PM GRADE 3'), ('TEP-GR1', 'TEACH PM GRADE 1'), ('CA', 'CASA AFTERNOON 1:30'), ('TEP', 'TEACH PM'), ('G10', 'GRADE 10'), ('TEP-GR2', 'TEACH PM GRADE 2'), ('G8', 'GRADE 8'), ('CM', 'CASA AM'), ('PG', 'PLAY GROUP')], default='CM', help_text='Choose Group for Students', max_length=10),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='rolegroup',
            field=models.CharField(blank=True, choices=[('S', 'STAFF'), ('SH', 'SCHOOL HEAD'), ('F', 'FACULTY')], default='F', help_text='Please choose Role / Duty', max_length=10),
        ),
        migrations.DeleteModel(
            name='Parents',
        ),
    ]
