# Generated by Django 2.0.6 on 2018-07-10 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0055_auto_20180710_0025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='fathersname',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='fathersreligion',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='mothersname',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='mothersreligion',
        ),
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(blank=True, max_length=64, verbose_name='Complete Name'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='religion',
            field=models.CharField(blank=True, choices=[('B', 'Buddhist'), ('I', 'INC'), ('C', 'Catholic'), ('M', 'Muslim')], default='C', help_text='Please select Religion', max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='applicationtype',
            field=models.CharField(blank=True, choices=[('SPED', 'Special Education Program'), ('CA', 'CASA Program'), ('JH', 'Junior High School Program'), ('SH', 'Senior High School Program'), ('GS', 'Grade School Program')], default='CA', help_text='Choose Application Program', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='civilstatus',
            field=models.CharField(blank=True, choices=[('SP', 'Single Parent'), ('D', 'Divorcee'), ('M', 'Married'), ('W', 'Widowed')], default='M', help_text='Please select Civit Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='students',
            name='groupinfo',
            field=models.CharField(blank=True, choices=[('G1', 'GRADE 1'), ('G3', 'GRADE 3'), ('G6', 'GRADE 6'), ('CA', 'CASA AFTERNOON 1:30'), ('TEP-GR2', 'TEACH PM GRADE 2'), ('G9', 'GRADE 9'), ('G5', 'GRADE 5'), ('G7', 'GRADE 7'), ('G2', 'GRADE 2'), ('PG', 'PLAY GROUP'), ('TEP-GR1', 'TEACH PM GRADE 1'), ('G10', 'GRADE 10'), ('TEP', 'TEACH PM'), ('G8', 'GRADE 8'), ('G4', 'GRADE 4'), ('TEA', 'TEACH AM'), ('TEP-GR2', 'TEACH PM GRADE 3'), ('CM', 'CASA AM')], default='CM', help_text='Choose Group for Students', max_length=10),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='rolegroup',
            field=models.CharField(blank=True, choices=[('SH', 'SCHOOL HEAD'), ('F', 'FACULTY'), ('S', 'STAFF')], default='F', help_text='Please choose Role / Duty', max_length=10),
        ),
    ]
