# Generated by Django 2.0.6 on 2018-07-10 04:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0056_auto_20180710_0314'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fathersname', models.CharField(max_length=30, verbose_name='Fathers Name')),
                ('fatherseducationalbackground', models.CharField(max_length=64, verbose_name='Fathers Educational Attainment')),
                ('motherseducationalbackground', models.CharField(max_length=64, verbose_name='Mothers Educational Attainment')),
                ('occupation', models.CharField(max_length=64, verbose_name='Occupation')),
                ('companyname', models.CharField(max_length=64, verbose_name='Occupation')),
            ],
            options={
                'verbose_name_plural': 'Parents Information',
            },
        ),
        migrations.AlterField(
            model_name='customuser',
            name='applicationtype',
            field=models.CharField(blank=True, choices=[('JH', 'Junior High School Program'), ('SPED', 'Special Education Program'), ('GS', 'Grade School Program'), ('SH', 'Senior High School Program'), ('CA', 'CASA Program')], default='CA', help_text='Choose Application Program', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='civilstatus',
            field=models.CharField(blank=True, choices=[('M', 'Married'), ('D', 'Divorcee'), ('W', 'Widowed'), ('SP', 'Single Parent')], default='M', help_text='Please select Civit Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='religion',
            field=models.CharField(blank=True, choices=[('B', 'Buddhist'), ('C', 'Catholic'), ('M', 'Muslim'), ('I', 'INC')], default='C', help_text='Please select Religion', max_length=30),
        ),
        migrations.AlterField(
            model_name='students',
            name='groupinfo',
            field=models.CharField(blank=True, choices=[('TEP', 'TEACH PM'), ('TEP-GR2', 'TEACH PM GRADE 2'), ('G8', 'GRADE 8'), ('CM', 'CASA AM'), ('G9', 'GRADE 9'), ('TEP-GR1', 'TEACH PM GRADE 1'), ('G1', 'GRADE 1'), ('TEA', 'TEACH AM'), ('G3', 'GRADE 3'), ('CA', 'CASA AFTERNOON 1:30'), ('PG', 'PLAY GROUP'), ('TEP-GR2', 'TEACH PM GRADE 3'), ('G2', 'GRADE 2'), ('G5', 'GRADE 5'), ('G6', 'GRADE 6'), ('G10', 'GRADE 10'), ('G4', 'GRADE 4'), ('G7', 'GRADE 7')], default='CM', help_text='Choose Group for Students', max_length=10),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='rolegroup',
            field=models.CharField(blank=True, choices=[('F', 'FACULTY'), ('SH', 'SCHOOL HEAD'), ('S', 'STAFF')], default='F', help_text='Please choose Role / Duty', max_length=10),
        ),
        migrations.AddField(
            model_name='parentsinfo',
            name='address',
            field=models.OneToOneField(max_length=30, on_delete=django.db.models.deletion.CASCADE, related_name='parents_address', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parentsinfo',
            name='civilstats',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parents_civilstatus', to=settings.AUTH_USER_MODEL, verbose_name='Civil Status'),
        ),
        migrations.AddField(
            model_name='parentsinfo',
            name='mobilenumber',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parentsinfo',
            name='mothersname',
            field=models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, related_name='parents_parentsname', to=settings.AUTH_USER_MODEL, verbose_name='Mothers Name'),
        ),
        migrations.AddField(
            model_name='parentsinfo',
            name='religion',
            field=models.OneToOneField(max_length=30, on_delete=django.db.models.deletion.CASCADE, related_name='parents_religion', to=settings.AUTH_USER_MODEL),
        ),
    ]
