# Generated by Django 2.0.6 on 2018-07-10 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0057_auto_20180710_0421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentsinfo',
            name='civilstats',
        ),
        migrations.RemoveField(
            model_name='parentsinfo',
            name='companyname',
        ),
        migrations.RemoveField(
            model_name='parentsinfo',
            name='occupation',
        ),
        migrations.AddField(
            model_name='parentsinfo',
            name='fatheroccupation',
            field=models.CharField(blank=True, max_length=64, verbose_name='Fathers Occupation'),
        ),
        migrations.AddField(
            model_name='parentsinfo',
            name='fatherscompanyname',
            field=models.CharField(blank=True, max_length=64, verbose_name='Company Name'),
        ),
        migrations.AddField(
            model_name='parentsinfo',
            name='motherscompanyname',
            field=models.CharField(blank=True, max_length=64, verbose_name='Company Name'),
        ),
        migrations.AddField(
            model_name='parentsinfo',
            name='mothersoccupation',
            field=models.CharField(blank=True, max_length=64, verbose_name='Mothers Occupation'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='applicationtype',
            field=models.CharField(blank=True, choices=[('SPED', 'Special Education Program'), ('SH', 'Senior High School Program'), ('JH', 'Junior High School Program'), ('CA', 'CASA Program'), ('GS', 'Grade School Program')], default='CA', help_text='Choose Application Program', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='civilstatus',
            field=models.CharField(blank=True, choices=[('M', 'Married'), ('SP', 'Single Parent'), ('W', 'Widowed'), ('D', 'Divorcee')], default='M', help_text='Please select Civit Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='religion',
            field=models.CharField(blank=True, choices=[('I', 'INC'), ('M', 'Muslim'), ('B', 'Buddhist'), ('C', 'Catholic')], default='C', help_text='Please select Religion', max_length=30),
        ),
        migrations.AlterField(
            model_name='parentsinfo',
            name='address',
            field=models.CharField(max_length=64, verbose_name='Home Address'),
        ),
        migrations.AlterField(
            model_name='parentsinfo',
            name='fathersname',
            field=models.CharField(max_length=30, verbose_name='second Parent'),
        ),
        migrations.AlterField(
            model_name='parentsinfo',
            name='mobilenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='MOBILE FORMAT : +639178888888', max_length=128),
        ),
        migrations.AlterField(
            model_name='parentsinfo',
            name='mothersname',
            field=models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, related_name='customuser_name', to=settings.AUTH_USER_MODEL, verbose_name='Parents Name'),
        ),
        migrations.AlterField(
            model_name='parentsinfo',
            name='religion',
            field=models.CharField(blank=True, choices=[('I', 'INC'), ('M', 'Muslim'), ('B', 'Buddhist'), ('C', 'Catholic')], default='C', help_text='Please select Religion', max_length=30),
        ),
        migrations.AlterField(
            model_name='students',
            name='groupinfo',
            field=models.CharField(blank=True, choices=[('G10', 'GRADE 10'), ('G5', 'GRADE 5'), ('G7', 'GRADE 7'), ('G2', 'GRADE 2'), ('G3', 'GRADE 3'), ('G4', 'GRADE 4'), ('TEP-GR2', 'TEACH PM GRADE 3'), ('TEA', 'TEACH AM'), ('TEP-GR2', 'TEACH PM GRADE 2'), ('PG', 'PLAY GROUP'), ('G1', 'GRADE 1'), ('CA', 'CASA AFTERNOON 1:30'), ('G8', 'GRADE 8'), ('CM', 'CASA AM'), ('TEP-GR1', 'TEACH PM GRADE 1'), ('G9', 'GRADE 9'), ('G6', 'GRADE 6'), ('TEP', 'TEACH PM')], default='CM', help_text='Choose Group for Students', max_length=10),
        ),
    ]
