# Generated by Django 2.0.6 on 2018-07-11 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0058_auto_20180710_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentbio',
            name='parentsnameinfo',
            field=models.CharField(blank=True, max_length=64, verbose_name='Parents Information'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='applicationtype',
            field=models.CharField(blank=True, choices=[('CA', 'CASA Program'), ('SH', 'Senior High School Program'), ('JH', 'Junior High School Program'), ('GS', 'Grade School Program'), ('SPED', 'Special Education Program')], default='CA', help_text='Choose Application Program', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='civilstatus',
            field=models.CharField(blank=True, choices=[('SP', 'Single Parent'), ('W', 'Widowed'), ('D', 'Divorcee'), ('M', 'Married')], default='M', help_text='Please select Civit Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='religion',
            field=models.CharField(blank=True, choices=[('M', 'Muslim'), ('B', 'Buddhist'), ('C', 'Catholic'), ('I', 'INC')], default='C', help_text='Please select Religion', max_length=30),
        ),
        migrations.AlterField(
            model_name='parentsinfo',
            name='religion',
            field=models.CharField(blank=True, choices=[('M', 'Muslim'), ('B', 'Buddhist'), ('C', 'Catholic'), ('I', 'INC')], default='C', help_text='Please select Religion', max_length=30),
        ),
        migrations.AlterField(
            model_name='studentbio',
            name='studentname',
            field=models.CharField(blank=True, max_length=64, verbose_name='Student Name'),
        ),
        migrations.AlterField(
            model_name='students',
            name='groupinfo',
            field=models.CharField(blank=True, choices=[('CA', 'CASA AFTERNOON 1:30'), ('G9', 'GRADE 9'), ('G10', 'GRADE 10'), ('G3', 'GRADE 3'), ('CM', 'CASA AM'), ('TEP-GR1', 'TEACH PM GRADE 1'), ('G6', 'GRADE 6'), ('G7', 'GRADE 7'), ('G1', 'GRADE 1'), ('G2', 'GRADE 2'), ('G4', 'GRADE 4'), ('TEA', 'TEACH AM'), ('G5', 'GRADE 5'), ('TEP-GR2', 'TEACH PM GRADE 3'), ('TEP', 'TEACH PM'), ('G8', 'GRADE 8'), ('TEP-GR2', 'TEACH PM GRADE 2'), ('PG', 'PLAY GROUP')], default='CM', help_text='Choose Group for Students', max_length=10),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='rolegroup',
            field=models.CharField(blank=True, choices=[('SH', 'SCHOOL HEAD'), ('F', 'FACULTY'), ('S', 'STAFF')], default='F', help_text='Please choose Role / Duty', max_length=10),
        ),
    ]
