# Generated by Django 2.0.6 on 2018-07-11 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0059_auto_20180711_0519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='applicationtype',
            field=models.CharField(blank=True, choices=[('JH', 'Junior High School Program'), ('SH', 'Senior High School Program'), ('SPED', 'Special Education Program'), ('CA', 'CASA Program'), ('GS', 'Grade School Program')], default='CA', help_text='Choose Application Program', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='childsname',
            field=models.ForeignKey(max_length=64, on_delete=django.db.models.deletion.CASCADE, to='students.StudentBio'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='civilstatus',
            field=models.CharField(blank=True, choices=[('D', 'Divorcee'), ('M', 'Married'), ('W', 'Widowed'), ('SP', 'Single Parent')], default='M', help_text='Please select Civit Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='students',
            name='groupinfo',
            field=models.CharField(blank=True, choices=[('TEP', 'TEACH PM'), ('TEP-GR1', 'TEACH PM GRADE 1'), ('G10', 'GRADE 10'), ('G2', 'GRADE 2'), ('G9', 'GRADE 9'), ('TEP-GR2', 'TEACH PM GRADE 2'), ('G5', 'GRADE 5'), ('CM', 'CASA AM'), ('PG', 'PLAY GROUP'), ('G3', 'GRADE 3'), ('CA', 'CASA AFTERNOON 1:30'), ('TEA', 'TEACH AM'), ('G4', 'GRADE 4'), ('G7', 'GRADE 7'), ('G6', 'GRADE 6'), ('G8', 'GRADE 8'), ('TEP-GR2', 'TEACH PM GRADE 3'), ('G1', 'GRADE 1')], default='CM', help_text='Choose Group for Students', max_length=10),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='rolegroup',
            field=models.CharField(blank=True, choices=[('S', 'STAFF'), ('F', 'FACULTY'), ('SH', 'SCHOOL HEAD')], default='F', help_text='Please choose Role / Duty', max_length=10),
        ),
    ]
