# Generated by Django 2.0.6 on 2018-07-12 01:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0061_auto_20180711_0529'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccidentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accidentdetails', models.TextField(max_length=300, verbose_name='Accident Details')),
                ('treatmentdetails', models.CharField(help_text='If under treatment, please indicate dosage of drug', max_length=64, verbose_name='Treatment Details')),
                ('startperiodofillness', models.DateField(default=datetime.date.today, verbose_name='Date Started')),
            ],
        ),
        migrations.CreateModel(
            name='HospitalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reasonforhospital', models.CharField(max_length=64, verbose_name='Reason for Hospitalisation')),
                ('hospitalisationdetails', models.TextField(max_length=300, verbose_name='Hospitalization Details')),
                ('treatmentdetails', models.CharField(help_text='If under treatment, please indicate dosage of drug', max_length=64, verbose_name='Treatment Details')),
                ('startperiodofillness', models.DateField(default=datetime.date.today, verbose_name='Date Started')),
                ('endperiodillness', models.DateField(default=datetime.date.today, verbose_name='Date Ended')),
            ],
            options={
                'verbose_name_plural': 'Student Hospital Info',
            },
        ),
        migrations.CreateModel(
            name='IllnessInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('illnessinfo', models.CharField(choices=[('HP', 'Heart Problem'), ('HT', 'Hypertension'), ('DP', 'Dermatology Problem'), ('MP', 'Metabolc Problem'), ('HMP', 'Hematologic Problem'), ('A', 'Allergy'), ('CV', 'Convulsion'), ('EP', 'Ear Problems'), ('EPL', 'Epilepsy'), ('TP', 'Thyroid Problem'), ('O', 'Others'), ('AST', 'Asthma'), ('ANE', 'Anemia'), ('LP', 'Lung Problem'), ('SZ', 'Seizures'), ('VP', 'Viral Infection'), ('GP', 'Gastrointestinal Problems'), ('DM', 'Diabetes Mellitus')], default='A', max_length=64, verbose_name='Illness Information')),
                ('illnessdetails', models.TextField(max_length=300, verbose_name='Details of Illness')),
                ('treatmentdetails', models.CharField(help_text='If under treatment, please indicate dosage of drug', max_length=64, verbose_name='Treatment Details')),
                ('startperiodofillness', models.DateField(default=datetime.date.today, verbose_name='Date Started')),
                ('endperiodillness', models.DateField(default=datetime.date.today, verbose_name='Date Ended')),
            ],
            options={
                'verbose_name_plural': 'Student Illness Information',
            },
        ),
        migrations.CreateModel(
            name='ImmunisationInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PresentCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentcondition', models.CharField(choices=[('S', 'STOMACH ACHE'), ('D', 'DIARRHEA'), ('V', 'VOMITING'), ('C', 'COLDS'), ('CO', 'COUGH'), ('0', 'OTHERS'), ('H', 'HEADACHE'), ('F', 'FEVER'), ('L', 'LBM')], max_length=64, verbose_name='Current Medical Condition')),
                ('conditiondetails', models.TextField(max_length=64, verbose_name='Condition Details')),
                ('treatmentdetails', models.CharField(max_length=64, verbose_name='Treatment Information')),
                ('startperiodofillness', models.DateField(default=datetime.date.today, verbose_name='Date Started')),
                ('endperiodillness', models.DateField(default=datetime.date.today, verbose_name='Date Ended')),
            ],
            options={
                'verbose_name_plural': 'Student Present Condition',
            },
        ),
        migrations.DeleteModel(
            name='MedicalRecords',
        ),
        migrations.RemoveField(
            model_name='parentsinfo',
            name='fatheroccupation',
        ),
        migrations.RemoveField(
            model_name='parentsinfo',
            name='fatherscompanyname',
        ),
        migrations.RemoveField(
            model_name='parentsinfo',
            name='fatherseducationalbackground',
        ),
        migrations.RemoveField(
            model_name='parentsinfo',
            name='motherscompanyname',
        ),
        migrations.RemoveField(
            model_name='parentsinfo',
            name='motherseducationalbackground',
        ),
        migrations.RemoveField(
            model_name='parentsinfo',
            name='mothersoccupation',
        ),
        migrations.RemoveField(
            model_name='parentsinfo',
            name='religion',
        ),
        migrations.AddField(
            model_name='parentsinfo',
            name='email',
            field=models.EmailField(default='example@email.com', max_length=64, verbose_name='Email Address'),
        ),
        migrations.AddField(
            model_name='parentsinfo',
            name='guardiansname',
            field=models.CharField(blank=True, max_length=64, verbose_name='Guardians Name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='applicationtype',
            field=models.CharField(blank=True, choices=[('GS', 'Grade School Program'), ('JH', 'Junior High School Program'), ('SPED', 'Special Education Program'), ('SH', 'Senior High School Program'), ('CA', 'CASA Program')], default='CA', help_text='Choose Application Program', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='civilstatus',
            field=models.CharField(blank=True, choices=[('M', 'Married'), ('SP', 'Single Parent'), ('W', 'Widowed'), ('D', 'Divorcee')], default='M', help_text='Please select Civit Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='religion',
            field=models.CharField(blank=True, choices=[('I', 'INC'), ('M', 'Muslim'), ('B', 'Buddhist'), ('C', 'Catholic')], default='C', help_text='Please select Religion', max_length=30),
        ),
        migrations.AlterField(
            model_name='parentsinfo',
            name='fathersname',
            field=models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, related_name='customuser_mothersname', to=settings.AUTH_USER_MODEL, verbose_name='Parents Name'),
        ),
        migrations.AlterField(
            model_name='parentsinfo',
            name='mothersname',
            field=models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, related_name='customuser_fathersname', to=settings.AUTH_USER_MODEL, verbose_name='Parents Name'),
        ),
        migrations.AlterField(
            model_name='students',
            name='groupinfo',
            field=models.CharField(blank=True, choices=[('CA', 'CASA AFTERNOON 1:30'), ('G9', 'GRADE 9'), ('G1', 'GRADE 1'), ('G8', 'GRADE 8'), ('G5', 'GRADE 5'), ('TEA', 'TEACH AM'), ('G6', 'GRADE 6'), ('TEP-GR1', 'TEACH PM GRADE 1'), ('CM', 'CASA AM'), ('TEP-GR2', 'TEACH PM GRADE 2'), ('TEP-GR2', 'TEACH PM GRADE 3'), ('G2', 'GRADE 2'), ('G10', 'GRADE 10'), ('G4', 'GRADE 4'), ('G3', 'GRADE 3'), ('TEP', 'TEACH PM'), ('PG', 'PLAY GROUP'), ('G7', 'GRADE 7')], default='CM', help_text='Choose Group for Students', max_length=10),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='rolegroup',
            field=models.CharField(blank=True, choices=[('SH', 'SCHOOL HEAD'), ('F', 'FACULTY'), ('S', 'STAFF')], default='F', help_text='Please choose Role / Duty', max_length=10),
        ),
        migrations.AddField(
            model_name='presentcondition',
            name='name',
            field=models.ForeignKey(max_length=64, on_delete=django.db.models.deletion.CASCADE, to='students.Students'),
        ),
        migrations.AddField(
            model_name='immunisationinfo',
            name='name',
            field=models.ForeignKey(max_length=64, on_delete=django.db.models.deletion.CASCADE, to='students.Students'),
        ),
        migrations.AddField(
            model_name='illnessinfo',
            name='name',
            field=models.ForeignKey(max_length=64, on_delete=django.db.models.deletion.CASCADE, to='students.Students'),
        ),
        migrations.AddField(
            model_name='hospitalinfo',
            name='name',
            field=models.ForeignKey(max_length=64, on_delete=django.db.models.deletion.CASCADE, to='students.Students'),
        ),
        migrations.AddField(
            model_name='accidentinfo',
            name='name',
            field=models.ForeignKey(max_length=64, on_delete=django.db.models.deletion.CASCADE, to='students.Students'),
        ),
    ]
