# Generated by Django 2.0.6 on 2018-07-12 05:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0062_auto_20180712_0131'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGrades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grades', models.IntegerField(verbose_name='Grades')),
            ],
        ),
        migrations.AlterModelOptions(
            name='immunisationinfo',
            options={'verbose_name_plural': 'Student Accident Information'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='applicationtype',
            field=models.CharField(blank=True, choices=[('SH', 'Senior High School Program'), ('JH', 'Junior High School Program'), ('CA', 'CASA Program'), ('GS', 'Grade School Program'), ('SPED', 'Special Education Program')], default='CA', help_text='Choose Application Program', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='civilstatus',
            field=models.CharField(blank=True, choices=[('SP', 'Single Parent'), ('D', 'Divorcee'), ('W', 'Widowed'), ('M', 'Married')], default='M', help_text='Please select Civit Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='illnessinfo',
            name='illnessinfo',
            field=models.CharField(choices=[('O', 'Others'), ('VP', 'Viral Infection'), ('HT', 'Hypertension'), ('ANE', 'Anemia'), ('HP', 'Heart Problem'), ('EP', 'Ear Problems'), ('MP', 'Metabolc Problem'), ('A', 'Allergy'), ('GP', 'Gastrointestinal Problems'), ('AST', 'Asthma'), ('DP', 'Dermatology Problem'), ('LP', 'Lung Problem'), ('SZ', 'Seizures'), ('CV', 'Convulsion'), ('HMP', 'Hematologic Problem'), ('EPL', 'Epilepsy'), ('TP', 'Thyroid Problem'), ('DM', 'Diabetes Mellitus')], default='A', max_length=64, verbose_name='Illness Information'),
        ),
        migrations.AlterField(
            model_name='parentsinfo',
            name='fathersname',
            field=models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, related_name='customuser_mothersname', to=settings.AUTH_USER_MODEL, verbose_name='Fathers Name'),
        ),
        migrations.AlterField(
            model_name='parentsinfo',
            name='mothersname',
            field=models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, related_name='customuser_fathersname', to=settings.AUTH_USER_MODEL, verbose_name='Mothers Name'),
        ),
        migrations.AlterField(
            model_name='presentcondition',
            name='currentcondition',
            field=models.CharField(choices=[('H', 'HEADACHE'), ('C', 'COLDS'), ('V', 'VOMITING'), ('CO', 'COUGH'), ('L', 'LBM'), ('S', 'STOMACH ACHE'), ('0', 'OTHERS'), ('D', 'DIARRHEA'), ('F', 'FEVER')], max_length=64, verbose_name='Current Medical Condition'),
        ),
        migrations.AlterField(
            model_name='students',
            name='groupinfo',
            field=models.CharField(blank=True, choices=[('TEP-GR2', 'TEACH PM GRADE 3'), ('PG', 'PLAY GROUP'), ('G6', 'GRADE 6'), ('TEP-GR2', 'TEACH PM GRADE 2'), ('G7', 'GRADE 7'), ('G9', 'GRADE 9'), ('G4', 'GRADE 4'), ('TEP', 'TEACH PM'), ('G1', 'GRADE 1'), ('G8', 'GRADE 8'), ('G10', 'GRADE 10'), ('G3', 'GRADE 3'), ('G5', 'GRADE 5'), ('G2', 'GRADE 2'), ('TEA', 'TEACH AM'), ('TEP-GR1', 'TEACH PM GRADE 1'), ('CA', 'CASA AFTERNOON 1:30'), ('CM', 'CASA AM')], default='CM', help_text='Choose Group for Students', max_length=10),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='rolegroup',
            field=models.CharField(blank=True, choices=[('SH', 'SCHOOL HEAD'), ('S', 'STAFF'), ('F', 'FACULTY')], default='F', help_text='Please choose Role / Duty', max_length=10),
        ),
        migrations.AddField(
            model_name='studentgrades',
            name='studentname',
            field=models.ForeignKey(max_length=64, on_delete=django.db.models.deletion.CASCADE, to='students.Students', verbose_name='Student Name'),
        ),
        migrations.AddField(
            model_name='studentgrades',
            name='subjectname',
            field=models.ForeignKey(max_length=64, on_delete=django.db.models.deletion.CASCADE, to='students.Subjects', verbose_name='Subject Name'),
        ),
        migrations.AddField(
            model_name='studentgrades',
            name='teachersname',
            field=models.ForeignKey(max_length=64, on_delete=django.db.models.deletion.CASCADE, to='students.Teachers', verbose_name=' Teachers Name'),
        ),
    ]
