# Generated by Django 2.0.6 on 2018-07-12 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0063_auto_20180712_0505'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterRatings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chargrades', models.CharField(default='G', max_length=10, verbose_name='Character Rates')),
                ('charactersets', models.ForeignKey(max_length=64, on_delete=django.db.models.deletion.CASCADE, to='students.CharacterBuildingActivities', verbose_name=' Character Activities')),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='applicationtype',
            field=models.CharField(blank=True, choices=[('SH', 'Senior High School Program'), ('CA', 'CASA Program'), ('SPED', 'Special Education Program'), ('JH', 'Junior High School Program'), ('GS', 'Grade School Program')], default='CA', help_text='Choose Application Program', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='civilstatus',
            field=models.CharField(blank=True, choices=[('W', 'Widowed'), ('M', 'Married'), ('D', 'Divorcee'), ('SP', 'Single Parent')], default='M', help_text='Please select Civit Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='religion',
            field=models.CharField(blank=True, choices=[('I', 'INC'), ('B', 'Buddhist'), ('M', 'Muslim'), ('C', 'Catholic')], default='C', help_text='Please select Religion', max_length=30),
        ),
        migrations.AlterField(
            model_name='illnessinfo',
            name='illnessinfo',
            field=models.CharField(choices=[('VP', 'Viral Infection'), ('DP', 'Dermatology Problem'), ('TP', 'Thyroid Problem'), ('CV', 'Convulsion'), ('O', 'Others'), ('DM', 'Diabetes Mellitus'), ('AST', 'Asthma'), ('ANE', 'Anemia'), ('LP', 'Lung Problem'), ('EPL', 'Epilepsy'), ('HMP', 'Hematologic Problem'), ('HT', 'Hypertension'), ('A', 'Allergy'), ('GP', 'Gastrointestinal Problems'), ('SZ', 'Seizures'), ('EP', 'Ear Problems'), ('HP', 'Heart Problem'), ('MP', 'Metabolc Problem')], default='A', max_length=64, verbose_name='Illness Information'),
        ),
        migrations.AlterField(
            model_name='presentcondition',
            name='currentcondition',
            field=models.CharField(choices=[('C', 'COLDS'), ('D', 'DIARRHEA'), ('S', 'STOMACH ACHE'), ('0', 'OTHERS'), ('CO', 'COUGH'), ('V', 'VOMITING'), ('L', 'LBM'), ('F', 'FEVER'), ('H', 'HEADACHE')], max_length=64, verbose_name='Current Medical Condition'),
        ),
        migrations.AlterField(
            model_name='students',
            name='groupinfo',
            field=models.CharField(blank=True, choices=[('G8', 'GRADE 8'), ('G10', 'GRADE 10'), ('TEA', 'TEACH AM'), ('TEP-GR2', 'TEACH PM GRADE 3'), ('G1', 'GRADE 1'), ('G5', 'GRADE 5'), ('G6', 'GRADE 6'), ('TEP-GR2', 'TEACH PM GRADE 2'), ('TEP-GR1', 'TEACH PM GRADE 1'), ('G9', 'GRADE 9'), ('G2', 'GRADE 2'), ('G7', 'GRADE 7'), ('TEP', 'TEACH PM'), ('G4', 'GRADE 4'), ('G3', 'GRADE 3'), ('PG', 'PLAY GROUP'), ('CM', 'CASA AM'), ('CA', 'CASA AFTERNOON 1:30')], default='CM', help_text='Choose Group for Students', max_length=10),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='rolegroup',
            field=models.CharField(blank=True, choices=[('F', 'FACULTY'), ('SH', 'SCHOOL HEAD'), ('S', 'STAFF')], default='F', help_text='Please choose Role / Duty', max_length=10),
        ),
        migrations.AddField(
            model_name='characterratings',
            name='studentname',
            field=models.ForeignKey(max_length=64, on_delete=django.db.models.deletion.CASCADE, to='students.Students', verbose_name='Student Name'),
        ),
    ]
