# Generated by Django 2.0.6 on 2018-07-12 06:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0064_auto_20180712_0621'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterratings',
            name='dateperiod',
            field=models.DateField(default=datetime.date.today, verbose_name='Date Info Period'),
        ),
        migrations.AddField(
            model_name='characterratings',
            name='startperiodofillness',
            field=models.DateField(default=datetime.date.today, verbose_name='Date Started'),
        ),
        migrations.AddField(
            model_name='studentgrades',
            name='dateperiod',
            field=models.DateField(default=datetime.date.today, verbose_name='Date Info Period'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='applicationtype',
            field=models.CharField(blank=True, choices=[('JH', 'Junior High School Program'), ('SPED', 'Special Education Program'), ('GS', 'Grade School Program'), ('SH', 'Senior High School Program'), ('CA', 'CASA Program')], default='CA', help_text='Choose Application Program', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='civilstatus',
            field=models.CharField(blank=True, choices=[('W', 'Widowed'), ('D', 'Divorcee'), ('M', 'Married'), ('SP', 'Single Parent')], default='M', help_text='Please select Civit Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='religion',
            field=models.CharField(blank=True, choices=[('C', 'Catholic'), ('I', 'INC'), ('M', 'Muslim'), ('B', 'Buddhist')], default='C', help_text='Please select Religion', max_length=30),
        ),
        migrations.AlterField(
            model_name='illnessinfo',
            name='illnessinfo',
            field=models.CharField(choices=[('GP', 'Gastrointestinal Problems'), ('AST', 'Asthma'), ('DM', 'Diabetes Mellitus'), ('TP', 'Thyroid Problem'), ('MP', 'Metabolc Problem'), ('ANE', 'Anemia'), ('VP', 'Viral Infection'), ('HP', 'Heart Problem'), ('HT', 'Hypertension'), ('LP', 'Lung Problem'), ('A', 'Allergy'), ('EP', 'Ear Problems'), ('EPL', 'Epilepsy'), ('HMP', 'Hematologic Problem'), ('O', 'Others'), ('DP', 'Dermatology Problem'), ('CV', 'Convulsion'), ('SZ', 'Seizures')], default='A', max_length=64, verbose_name='Illness Information'),
        ),
        migrations.AlterField(
            model_name='presentcondition',
            name='currentcondition',
            field=models.CharField(choices=[('F', 'FEVER'), ('V', 'VOMITING'), ('C', 'COLDS'), ('H', 'HEADACHE'), ('L', 'LBM'), ('0', 'OTHERS'), ('CO', 'COUGH'), ('S', 'STOMACH ACHE'), ('D', 'DIARRHEA')], max_length=64, verbose_name='Current Medical Condition'),
        ),
        migrations.AlterField(
            model_name='students',
            name='groupinfo',
            field=models.CharField(blank=True, choices=[('TEP-GR2', 'TEACH PM GRADE 3'), ('CA', 'CASA AFTERNOON 1:30'), ('G3', 'GRADE 3'), ('TEP', 'TEACH PM'), ('TEP-GR1', 'TEACH PM GRADE 1'), ('TEA', 'TEACH AM'), ('G6', 'GRADE 6'), ('G4', 'GRADE 4'), ('G5', 'GRADE 5'), ('G1', 'GRADE 1'), ('G9', 'GRADE 9'), ('TEP-GR2', 'TEACH PM GRADE 2'), ('PG', 'PLAY GROUP'), ('G8', 'GRADE 8'), ('CM', 'CASA AM'), ('G2', 'GRADE 2'), ('G7', 'GRADE 7'), ('G10', 'GRADE 10')], default='CM', help_text='Choose Group for Students', max_length=10),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='rolegroup',
            field=models.CharField(blank=True, choices=[('SH', 'SCHOOL HEAD'), ('F', 'FACULTY'), ('S', 'STAFF')], default='F', help_text='Please choose Role / Duty', max_length=10),
        ),
    ]
