# Generated by Django 2.0.6 on 2018-07-12 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0065_auto_20180712_0640'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservationLists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traitsname', models.CharField(max_length=64, verbose_name='Traits')),
            ],
            options={
                'verbose_name_plural': 'PAGUNLAD SA TAGLAY NA MGA PAGPAPAHALAGA AT SALOOBIN LISTS',
            },
        ),
        migrations.AlterModelOptions(
            name='accidentinfo',
            options={'verbose_name_plural': 'Student Accident Information'},
        ),
        migrations.AlterModelOptions(
            name='characterbuildingactivities',
            options={'verbose_name_plural': 'Character Building Activities Traits Lists'},
        ),
        migrations.AlterModelOptions(
            name='characterratings',
            options={'verbose_name_plural': 'Character Building Activities Records'},
        ),
        migrations.AlterModelOptions(
            name='gradeyear',
            options={'verbose_name_plural': 'Student Grade Year Lists'},
        ),
        migrations.AlterModelOptions(
            name='immunisationinfo',
            options={'verbose_name_plural': 'Student Accident Immunisation Info'},
        ),
        migrations.AlterModelOptions(
            name='studentgrades',
            options={'verbose_name_plural': 'Grades Records of Students'},
        ),
        migrations.AlterModelOptions(
            name='subjects',
            options={'verbose_name_plural': 'Subjects Lists Information'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='applicationtype',
            field=models.CharField(blank=True, choices=[('SPED', 'Special Education Program'), ('SH', 'Senior High School Program'), ('CA', 'CASA Program'), ('GS', 'Grade School Program'), ('JH', 'Junior High School Program')], default='CA', help_text='Choose Application Program', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='civilstatus',
            field=models.CharField(blank=True, choices=[('W', 'Widowed'), ('D', 'Divorcee'), ('SP', 'Single Parent'), ('M', 'Married')], default='M', help_text='Please select Civit Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='religion',
            field=models.CharField(blank=True, choices=[('I', 'INC'), ('C', 'Catholic'), ('M', 'Muslim'), ('B', 'Buddhist')], default='C', help_text='Please select Religion', max_length=30),
        ),
        migrations.AlterField(
            model_name='illnessinfo',
            name='illnessinfo',
            field=models.CharField(choices=[('TP', 'Thyroid Problem'), ('VP', 'Viral Infection'), ('MP', 'Metabolc Problem'), ('A', 'Allergy'), ('ANE', 'Anemia'), ('DP', 'Dermatology Problem'), ('LP', 'Lung Problem'), ('GP', 'Gastrointestinal Problems'), ('SZ', 'Seizures'), ('AST', 'Asthma'), ('EP', 'Ear Problems'), ('HMP', 'Hematologic Problem'), ('HT', 'Hypertension'), ('CV', 'Convulsion'), ('O', 'Others'), ('HP', 'Heart Problem'), ('EPL', 'Epilepsy'), ('DM', 'Diabetes Mellitus')], default='A', max_length=64, verbose_name='Illness Information'),
        ),
        migrations.AlterField(
            model_name='presentcondition',
            name='currentcondition',
            field=models.CharField(choices=[('D', 'DIARRHEA'), ('S', 'STOMACH ACHE'), ('0', 'OTHERS'), ('H', 'HEADACHE'), ('V', 'VOMITING'), ('C', 'COLDS'), ('F', 'FEVER'), ('L', 'LBM'), ('CO', 'COUGH')], max_length=64, verbose_name='Current Medical Condition'),
        ),
        migrations.AlterField(
            model_name='students',
            name='groupinfo',
            field=models.CharField(blank=True, choices=[('CA', 'CASA AFTERNOON 1:30'), ('CM', 'CASA AM'), ('TEP-GR2', 'TEACH PM GRADE 2'), ('G3', 'GRADE 3'), ('G4', 'GRADE 4'), ('PG', 'PLAY GROUP'), ('G8', 'GRADE 8'), ('TEP-GR1', 'TEACH PM GRADE 1'), ('G9', 'GRADE 9'), ('TEP', 'TEACH PM'), ('G7', 'GRADE 7'), ('G1', 'GRADE 1'), ('TEP-GR2', 'TEACH PM GRADE 3'), ('G10', 'GRADE 10'), ('TEA', 'TEACH AM'), ('G5', 'GRADE 5'), ('G2', 'GRADE 2'), ('G6', 'GRADE 6')], default='CM', help_text='Choose Group for Students', max_length=10),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='rolegroup',
            field=models.CharField(blank=True, choices=[('SH', 'SCHOOL HEAD'), ('S', 'STAFF'), ('F', 'FACULTY')], default='F', help_text='Please choose Role / Duty', max_length=10),
        ),
    ]
