# Generated by Django 2.0.6 on 2018-07-12 09:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0067_auto_20180712_0816'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterObservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observegrades', models.CharField(default='G', max_length=10, verbose_name='Character Rates')),
                ('dateadded', models.DateField(default=datetime.date.today, verbose_name='Date Started')),
                ('dateperiod', models.DateField(default=datetime.date.today, verbose_name='Date Info Period')),
                ('observationsets', models.ForeignKey(max_length=64, on_delete=django.db.models.deletion.CASCADE, to='students.CharacterBuildingActivities', verbose_name=' Character Activities')),
            ],
            options={
                'verbose_name_plural': 'PAGUNLAD SA TAGLAY NA MGA PAGPAPAHALAGA AT SALOOBIN LISTS',
            },
        ),
        migrations.AlterModelOptions(
            name='observationlists',
            options={'verbose_name_plural': 'PAGUNLAD LISTS'},
        ),
        migrations.RenameField(
            model_name='characterratings',
            old_name='startperiodofillness',
            new_name='dateadded',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='applicationtype',
            field=models.CharField(blank=True, choices=[('JH', 'Junior High School Program'), ('SPED', 'Special Education Program'), ('GS', 'Grade School Program'), ('CA', 'CASA Program'), ('SH', 'Senior High School Program')], default='CA', help_text='Choose Application Program', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='civilstatus',
            field=models.CharField(blank=True, choices=[('W', 'Widowed'), ('M', 'Married'), ('SP', 'Single Parent'), ('D', 'Divorcee')], default='M', help_text='Please select Civit Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='religion',
            field=models.CharField(blank=True, choices=[('B', 'Buddhist'), ('I', 'INC'), ('C', 'Catholic'), ('M', 'Muslim')], default='C', help_text='Please select Religion', max_length=30),
        ),
        migrations.AlterField(
            model_name='illnessinfo',
            name='illnessinfo',
            field=models.CharField(choices=[('EPL', 'Epilepsy'), ('LP', 'Lung Problem'), ('O', 'Others'), ('SZ', 'Seizures'), ('AST', 'Asthma'), ('A', 'Allergy'), ('DP', 'Dermatology Problem'), ('MP', 'Metabolc Problem'), ('HT', 'Hypertension'), ('HP', 'Heart Problem'), ('CV', 'Convulsion'), ('ANE', 'Anemia'), ('TP', 'Thyroid Problem'), ('DM', 'Diabetes Mellitus'), ('VP', 'Viral Infection'), ('EP', 'Ear Problems'), ('GP', 'Gastrointestinal Problems'), ('HMP', 'Hematologic Problem')], default='A', max_length=64, verbose_name='Illness Information'),
        ),
        migrations.AlterField(
            model_name='presentcondition',
            name='currentcondition',
            field=models.CharField(choices=[('F', 'FEVER'), ('L', 'LBM'), ('CO', 'COUGH'), ('D', 'DIARRHEA'), ('C', 'COLDS'), ('S', 'STOMACH ACHE'), ('V', 'VOMITING'), ('H', 'HEADACHE'), ('0', 'OTHERS')], max_length=64, verbose_name='Current Medical Condition'),
        ),
        migrations.AlterField(
            model_name='students',
            name='groupinfo',
            field=models.CharField(blank=True, choices=[('CM', 'CASA AM'), ('CA', 'CASA AFTERNOON 1:30'), ('TEP-GR1', 'TEACH PM GRADE 1'), ('G10', 'GRADE 10'), ('TEP-GR2', 'TEACH PM GRADE 2'), ('G1', 'GRADE 1'), ('TEA', 'TEACH AM'), ('G5', 'GRADE 5'), ('G7', 'GRADE 7'), ('TEP-GR2', 'TEACH PM GRADE 3'), ('PG', 'PLAY GROUP'), ('G3', 'GRADE 3'), ('G9', 'GRADE 9'), ('TEP', 'TEACH PM'), ('G4', 'GRADE 4'), ('G2', 'GRADE 2'), ('G6', 'GRADE 6'), ('G8', 'GRADE 8')], default='CM', help_text='Choose Group for Students', max_length=10),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='rolegroup',
            field=models.CharField(blank=True, choices=[('SH', 'SCHOOL HEAD'), ('S', 'STAFF'), ('F', 'FACULTY')], default='F', help_text='Please choose Role / Duty', max_length=10),
        ),
        migrations.AddField(
            model_name='characterobservation',
            name='studentname',
            field=models.ForeignKey(max_length=64, on_delete=django.db.models.deletion.CASCADE, to='students.Students', verbose_name='Student Name'),
        ),
    ]
