# Generated by Django 2.0.6 on 2018-07-12 09:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0068_auto_20180712_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characterobservation',
            name='dateperiod',
        ),
        migrations.RemoveField(
            model_name='characterratings',
            name='dateperiod',
        ),
        migrations.AlterField(
            model_name='characterobservation',
            name='dateadded',
            field=models.DateField(default=datetime.date.today, verbose_name='Date added'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='applicationtype',
            field=models.CharField(blank=True, choices=[('CA', 'CASA Program'), ('SPED', 'Special Education Program'), ('SH', 'Senior High School Program'), ('JH', 'Junior High School Program'), ('GS', 'Grade School Program')], default='CA', help_text='Choose Application Program', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='civilstatus',
            field=models.CharField(blank=True, choices=[('M', 'Married'), ('D', 'Divorcee'), ('SP', 'Single Parent'), ('W', 'Widowed')], default='M', help_text='Please select Civit Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='religion',
            field=models.CharField(blank=True, choices=[('M', 'Muslim'), ('B', 'Buddhist'), ('C', 'Catholic'), ('I', 'INC')], default='C', help_text='Please select Religion', max_length=30),
        ),
        migrations.AlterField(
            model_name='illnessinfo',
            name='illnessinfo',
            field=models.CharField(choices=[('EPL', 'Epilepsy'), ('TP', 'Thyroid Problem'), ('DP', 'Dermatology Problem'), ('LP', 'Lung Problem'), ('CV', 'Convulsion'), ('HMP', 'Hematologic Problem'), ('EP', 'Ear Problems'), ('MP', 'Metabolc Problem'), ('HP', 'Heart Problem'), ('GP', 'Gastrointestinal Problems'), ('O', 'Others'), ('A', 'Allergy'), ('SZ', 'Seizures'), ('VP', 'Viral Infection'), ('HT', 'Hypertension'), ('ANE', 'Anemia'), ('AST', 'Asthma'), ('DM', 'Diabetes Mellitus')], default='A', max_length=64, verbose_name='Illness Information'),
        ),
        migrations.AlterField(
            model_name='presentcondition',
            name='currentcondition',
            field=models.CharField(choices=[('0', 'OTHERS'), ('F', 'FEVER'), ('D', 'DIARRHEA'), ('CO', 'COUGH'), ('L', 'LBM'), ('V', 'VOMITING'), ('H', 'HEADACHE'), ('C', 'COLDS'), ('S', 'STOMACH ACHE')], max_length=64, verbose_name='Current Medical Condition'),
        ),
        migrations.AlterField(
            model_name='students',
            name='groupinfo',
            field=models.CharField(blank=True, choices=[('CM', 'CASA AM'), ('TEP-GR2', 'TEACH PM GRADE 2'), ('G2', 'GRADE 2'), ('G5', 'GRADE 5'), ('G3', 'GRADE 3'), ('G4', 'GRADE 4'), ('G7', 'GRADE 7'), ('G8', 'GRADE 8'), ('CA', 'CASA AFTERNOON 1:30'), ('G1', 'GRADE 1'), ('G6', 'GRADE 6'), ('TEP-GR1', 'TEACH PM GRADE 1'), ('PG', 'PLAY GROUP'), ('TEP-GR2', 'TEACH PM GRADE 3'), ('TEP', 'TEACH PM'), ('G9', 'GRADE 9'), ('G10', 'GRADE 10'), ('TEA', 'TEACH AM')], default='CM', help_text='Choose Group for Students', max_length=10),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='rolegroup',
            field=models.CharField(blank=True, choices=[('S', 'STAFF'), ('SH', 'SCHOOL HEAD'), ('F', 'FACULTY')], default='F', help_text='Please choose Role / Duty', max_length=10),
        ),
    ]
