# Generated by Django 2.0.6 on 2018-07-12 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0069_auto_20180712_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterobservation',
            name='observationsets',
            field=models.ForeignKey(max_length=64, on_delete=django.db.models.deletion.CASCADE, to='students.ObservationLists', verbose_name=' Character Activities'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='applicationtype',
            field=models.CharField(blank=True, choices=[('JH', 'Junior High School Program'), ('CA', 'CASA Program'), ('SH', 'Senior High School Program'), ('SPED', 'Special Education Program'), ('GS', 'Grade School Program')], default='CA', help_text='Choose Application Program', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='civilstatus',
            field=models.CharField(blank=True, choices=[('D', 'Divorcee'), ('M', 'Married'), ('W', 'Widowed'), ('SP', 'Single Parent')], default='M', help_text='Please select Civit Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='religion',
            field=models.CharField(blank=True, choices=[('B', 'Buddhist'), ('M', 'Muslim'), ('C', 'Catholic'), ('I', 'INC')], default='C', help_text='Please select Religion', max_length=30),
        ),
        migrations.AlterField(
            model_name='illnessinfo',
            name='illnessinfo',
            field=models.CharField(choices=[('A', 'Allergy'), ('O', 'Others'), ('HT', 'Hypertension'), ('ANE', 'Anemia'), ('MP', 'Metabolc Problem'), ('EP', 'Ear Problems'), ('EPL', 'Epilepsy'), ('DM', 'Diabetes Mellitus'), ('CV', 'Convulsion'), ('DP', 'Dermatology Problem'), ('GP', 'Gastrointestinal Problems'), ('HP', 'Heart Problem'), ('TP', 'Thyroid Problem'), ('VP', 'Viral Infection'), ('SZ', 'Seizures'), ('AST', 'Asthma'), ('LP', 'Lung Problem'), ('HMP', 'Hematologic Problem')], default='A', max_length=64, verbose_name='Illness Information'),
        ),
        migrations.AlterField(
            model_name='presentcondition',
            name='currentcondition',
            field=models.CharField(choices=[('H', 'HEADACHE'), ('0', 'OTHERS'), ('V', 'VOMITING'), ('S', 'STOMACH ACHE'), ('C', 'COLDS'), ('D', 'DIARRHEA'), ('L', 'LBM'), ('CO', 'COUGH'), ('F', 'FEVER')], max_length=64, verbose_name='Current Medical Condition'),
        ),
        migrations.AlterField(
            model_name='students',
            name='groupinfo',
            field=models.CharField(blank=True, choices=[('TEA', 'TEACH AM'), ('PG', 'PLAY GROUP'), ('G4', 'GRADE 4'), ('G10', 'GRADE 10'), ('CA', 'CASA AFTERNOON 1:30'), ('G3', 'GRADE 3'), ('G2', 'GRADE 2'), ('G9', 'GRADE 9'), ('G5', 'GRADE 5'), ('TEP', 'TEACH PM'), ('TEP-GR1', 'TEACH PM GRADE 1'), ('G6', 'GRADE 6'), ('TEP-GR2', 'TEACH PM GRADE 3'), ('G7', 'GRADE 7'), ('TEP-GR2', 'TEACH PM GRADE 2'), ('CM', 'CASA AM'), ('G1', 'GRADE 1'), ('G8', 'GRADE 8')], default='CM', help_text='Choose Group for Students', max_length=10),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='rolegroup',
            field=models.CharField(blank=True, choices=[('S', 'STAFF'), ('F', 'FACULTY'), ('SH', 'SCHOOL HEAD')], default='F', help_text='Please choose Role / Duty', max_length=10),
        ),
    ]
