# Generated by Django 2.0.6 on 2018-07-13 02:11

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('students', '0070_auto_20180712_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('average', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=6)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('foo', models.TextField()),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='customuser',
            name='applicationtype',
            field=models.CharField(blank=True, choices=[('JH', 'Junior High School Program'), ('CA', 'CASA Program'), ('GS', 'Grade School Program'), ('SPED', 'Special Education Program'), ('SH', 'Senior High School Program')], default='CA', help_text='Choose Application Program', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='civilstatus',
            field=models.CharField(blank=True, choices=[('W', 'Widowed'), ('D', 'Divorcee'), ('SP', 'Single Parent'), ('M', 'Married')], default='M', help_text='Please select Civit Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='religion',
            field=models.CharField(blank=True, choices=[('M', 'Muslim'), ('I', 'INC'), ('B', 'Buddhist'), ('C', 'Catholic')], default='C', help_text='Please select Religion', max_length=30),
        ),
        migrations.AlterField(
            model_name='illnessinfo',
            name='illnessinfo',
            field=models.CharField(choices=[('TP', 'Thyroid Problem'), ('HT', 'Hypertension'), ('HP', 'Heart Problem'), ('CV', 'Convulsion'), ('ANE', 'Anemia'), ('AST', 'Asthma'), ('SZ', 'Seizures'), ('MP', 'Metabolc Problem'), ('A', 'Allergy'), ('VP', 'Viral Infection'), ('DP', 'Dermatology Problem'), ('HMP', 'Hematologic Problem'), ('O', 'Others'), ('EP', 'Ear Problems'), ('GP', 'Gastrointestinal Problems'), ('DM', 'Diabetes Mellitus'), ('EPL', 'Epilepsy'), ('LP', 'Lung Problem')], default='A', max_length=64, verbose_name='Illness Information'),
        ),
        migrations.AlterField(
            model_name='presentcondition',
            name='currentcondition',
            field=models.CharField(choices=[('C', 'COLDS'), ('0', 'OTHERS'), ('CO', 'COUGH'), ('S', 'STOMACH ACHE'), ('F', 'FEVER'), ('H', 'HEADACHE'), ('D', 'DIARRHEA'), ('L', 'LBM'), ('V', 'VOMITING')], max_length=64, verbose_name='Current Medical Condition'),
        ),
        migrations.AlterField(
            model_name='students',
            name='groupinfo',
            field=models.CharField(blank=True, choices=[('TEP', 'TEACH PM'), ('G1', 'GRADE 1'), ('G10', 'GRADE 10'), ('TEP-GR2', 'TEACH PM GRADE 2'), ('TEP-GR2', 'TEACH PM GRADE 3'), ('G7', 'GRADE 7'), ('G3', 'GRADE 3'), ('G5', 'GRADE 5'), ('TEP-GR1', 'TEACH PM GRADE 1'), ('G8', 'GRADE 8'), ('G9', 'GRADE 9'), ('TEA', 'TEACH AM'), ('CM', 'CASA AM'), ('PG', 'PLAY GROUP'), ('G2', 'GRADE 2'), ('G4', 'GRADE 4'), ('CA', 'CASA AFTERNOON 1:30'), ('G6', 'GRADE 6')], default='CM', help_text='Choose Group for Students', max_length=10),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='rolegroup',
            field=models.CharField(blank=True, choices=[('SH', 'SCHOOL HEAD'), ('F', 'FACULTY'), ('S', 'STAFF')], default='F', help_text='Please choose Role / Duty', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='testrating',
            unique_together={('content_type', 'object_id')},
        ),
    ]
