# Generated by Django 2.0.6 on 2018-07-14 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0072_auto_20180713_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='guardiansname',
            field=models.CharField(blank=True, max_length=64, verbose_name='Guardians Name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='applicationtype',
            field=models.CharField(blank=True, choices=[('JH', 'Junior High School Program'), ('SPED', 'Special Education Program'), ('SH', 'Senior High School Program'), ('GS', 'Grade School Program'), ('CA', 'CASA Program')], default='CA', help_text='Choose Application Program', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='civilstatus',
            field=models.CharField(blank=True, choices=[('M', 'Married'), ('D', 'Divorcee'), ('W', 'Widowed'), ('SP', 'Single Parent')], default='M', help_text='Please select Civit Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(blank=True, max_length=64, verbose_name='Complete Parents Name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='religion',
            field=models.CharField(blank=True, choices=[('B', 'Buddhist'), ('I', 'INC'), ('M', 'Muslim'), ('C', 'Catholic')], default='C', help_text='Please select Religion', max_length=30),
        ),
        migrations.AlterField(
            model_name='illnessinfo',
            name='illnessinfo',
            field=models.CharField(choices=[('LP', 'Lung Problem'), ('CV', 'Convulsion'), ('MP', 'Metabolc Problem'), ('DP', 'Dermatology Problem'), ('GP', 'Gastrointestinal Problems'), ('HMP', 'Hematologic Problem'), ('HP', 'Heart Problem'), ('ANE', 'Anemia'), ('HT', 'Hypertension'), ('O', 'Others'), ('DM', 'Diabetes Mellitus'), ('AST', 'Asthma'), ('SZ', 'Seizures'), ('A', 'Allergy'), ('EP', 'Ear Problems'), ('EPL', 'Epilepsy'), ('TP', 'Thyroid Problem'), ('VP', 'Viral Infection')], default='A', max_length=64, verbose_name='Illness Information'),
        ),
        migrations.AlterField(
            model_name='presentcondition',
            name='currentcondition',
            field=models.CharField(choices=[('CO', 'COUGH'), ('F', 'FEVER'), ('V', 'VOMITING'), ('C', 'COLDS'), ('L', 'LBM'), ('S', 'STOMACH ACHE'), ('H', 'HEADACHE'), ('0', 'OTHERS'), ('D', 'DIARRHEA')], max_length=64, verbose_name='Current Medical Condition'),
        ),
        migrations.AlterField(
            model_name='students',
            name='groupinfo',
            field=models.CharField(blank=True, choices=[('CM', 'CASA AM'), ('TEP', 'TEACH PM'), ('TEA', 'TEACH AM'), ('G3', 'GRADE 3'), ('G5', 'GRADE 5'), ('G2', 'GRADE 2'), ('G9', 'GRADE 9'), ('G4', 'GRADE 4'), ('PG', 'PLAY GROUP'), ('G1', 'GRADE 1'), ('G7', 'GRADE 7'), ('G8', 'GRADE 8'), ('G10', 'GRADE 10'), ('TEP-GR2', 'TEACH PM GRADE 2'), ('CA', 'CASA AFTERNOON 1:30'), ('G6', 'GRADE 6'), ('TEP-GR2', 'TEACH PM GRADE 3'), ('TEP-GR1', 'TEACH PM GRADE 1')], default='CM', help_text='Choose Group for Students', max_length=10),
        ),
    ]
