# Generated by Django 2.0.6 on 2018-07-14 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0074_auto_20180714_0435'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='fathersname',
            field=models.CharField(blank=True, max_length=64, verbose_name='Fathers Complete Name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.CharField(blank=True, max_length=64, verbose_name='Full Address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='applicationtype',
            field=models.CharField(blank=True, choices=[('SPED', 'Special Education Program'), ('SH', 'Senior High School Program'), ('GS', 'Grade School Program'), ('CA', 'CASA Program'), ('JH', 'Junior High School Program')], default='CA', help_text='Choose Application Program', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='civilstatus',
            field=models.CharField(blank=True, choices=[('M', 'Married'), ('D', 'Divorcee'), ('SP', 'Single Parent'), ('W', 'Widowed')], default='M', help_text='Please select Civit Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='guardiansname',
            field=models.CharField(blank=True, max_length=64, verbose_name='Guardians Complete Name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(blank=True, max_length=64, verbose_name='Mothers Complete Name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='religion',
            field=models.CharField(blank=True, choices=[('M', 'Muslim'), ('B', 'Buddhist'), ('C', 'Catholic'), ('I', 'INC')], default='C', help_text='Please select Religion', max_length=30),
        ),
        migrations.AlterField(
            model_name='illnessinfo',
            name='illnessinfo',
            field=models.CharField(choices=[('HT', 'Hypertension'), ('LP', 'Lung Problem'), ('EPL', 'Epilepsy'), ('A', 'Allergy'), ('EP', 'Ear Problems'), ('SZ', 'Seizures'), ('AST', 'Asthma'), ('DM', 'Diabetes Mellitus'), ('ANE', 'Anemia'), ('GP', 'Gastrointestinal Problems'), ('HMP', 'Hematologic Problem'), ('O', 'Others'), ('HP', 'Heart Problem'), ('MP', 'Metabolc Problem'), ('TP', 'Thyroid Problem'), ('DP', 'Dermatology Problem'), ('VP', 'Viral Infection'), ('CV', 'Convulsion')], default='A', max_length=64, verbose_name='Illness Information'),
        ),
        migrations.AlterField(
            model_name='presentcondition',
            name='currentcondition',
            field=models.CharField(choices=[('V', 'VOMITING'), ('0', 'OTHERS'), ('C', 'COLDS'), ('F', 'FEVER'), ('H', 'HEADACHE'), ('S', 'STOMACH ACHE'), ('D', 'DIARRHEA'), ('L', 'LBM'), ('CO', 'COUGH')], max_length=64, verbose_name='Current Medical Condition'),
        ),
        migrations.AlterField(
            model_name='students',
            name='groupinfo',
            field=models.CharField(blank=True, choices=[('TEP', 'TEACH PM'), ('TEP-GR2', 'TEACH PM GRADE 2'), ('G4', 'GRADE 4'), ('G6', 'GRADE 6'), ('TEA', 'TEACH AM'), ('CM', 'CASA AM'), ('TEP-GR2', 'TEACH PM GRADE 3'), ('G3', 'GRADE 3'), ('G2', 'GRADE 2'), ('G7', 'GRADE 7'), ('G9', 'GRADE 9'), ('G1', 'GRADE 1'), ('G10', 'GRADE 10'), ('G8', 'GRADE 8'), ('TEP-GR1', 'TEACH PM GRADE 1'), ('CA', 'CASA AFTERNOON 1:30'), ('G5', 'GRADE 5'), ('PG', 'PLAY GROUP')], default='CM', help_text='Choose Group for Students', max_length=10),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='rolegroup',
            field=models.CharField(blank=True, choices=[('S', 'STAFF'), ('F', 'FACULTY'), ('SH', 'SCHOOL HEAD')], default='F', help_text='Please choose Role / Duty', max_length=10),
        ),
    ]
