# Generated by Django 2.0.6 on 2018-07-15 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0075_auto_20180714_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.CharField(blank=True, max_length=300, verbose_name='Full Address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='applicationtype',
            field=models.CharField(blank=True, choices=[('CA', 'CASA Program'), ('SPED', 'Special Education Program'), ('GS', 'Grade School Program'), ('JH', 'Junior High School Program'), ('SH', 'Senior High School Program')], default='CA', help_text='Choose Application Program', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='childsname',
            field=models.ForeignKey(max_length=64, on_delete=django.db.models.deletion.CASCADE, to='students.Students'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='civilstatus',
            field=models.CharField(blank=True, choices=[('D', 'Divorcee'), ('SP', 'Single Parent'), ('M', 'Married'), ('W', 'Widowed')], default='M', help_text='Please select Civit Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='religion',
            field=models.CharField(blank=True, choices=[('B', 'Buddhist'), ('C', 'Catholic'), ('I', 'INC'), ('M', 'Muslim')], default='C', help_text='Please select Religion', max_length=30),
        ),
        migrations.AlterField(
            model_name='illnessinfo',
            name='illnessinfo',
            field=models.CharField(choices=[('AST', 'Asthma'), ('HT', 'Hypertension'), ('HMP', 'Hematologic Problem'), ('DM', 'Diabetes Mellitus'), ('TP', 'Thyroid Problem'), ('EP', 'Ear Problems'), ('CV', 'Convulsion'), ('LP', 'Lung Problem'), ('GP', 'Gastrointestinal Problems'), ('HP', 'Heart Problem'), ('A', 'Allergy'), ('EPL', 'Epilepsy'), ('DP', 'Dermatology Problem'), ('SZ', 'Seizures'), ('VP', 'Viral Infection'), ('O', 'Others'), ('MP', 'Metabolc Problem'), ('ANE', 'Anemia')], default='A', max_length=64, verbose_name='Illness Information'),
        ),
        migrations.AlterField(
            model_name='presentcondition',
            name='currentcondition',
            field=models.CharField(choices=[('C', 'COLDS'), ('L', 'LBM'), ('CO', 'COUGH'), ('V', 'VOMITING'), ('S', 'STOMACH ACHE'), ('F', 'FEVER'), ('D', 'DIARRHEA'), ('0', 'OTHERS'), ('H', 'HEADACHE')], max_length=64, verbose_name='Current Medical Condition'),
        ),
        migrations.AlterField(
            model_name='students',
            name='groupinfo',
            field=models.CharField(blank=True, choices=[('TEP', 'TEACH PM'), ('G10', 'GRADE 10'), ('G7', 'GRADE 7'), ('PG', 'PLAY GROUP'), ('G1', 'GRADE 1'), ('TEA', 'TEACH AM'), ('G2', 'GRADE 2'), ('TEP-GR2', 'TEACH PM GRADE 2'), ('CA', 'CASA AFTERNOON 1:30'), ('G8', 'GRADE 8'), ('CM', 'CASA AM'), ('G5', 'GRADE 5'), ('TEP-GR1', 'TEACH PM GRADE 1'), ('G6', 'GRADE 6'), ('G9', 'GRADE 9'), ('G4', 'GRADE 4'), ('TEP-GR2', 'TEACH PM GRADE 3'), ('G3', 'GRADE 3')], default='CM', help_text='Choose Group for Students', max_length=10),
        ),
    ]
