# Generated by Django 2.0.6 on 2018-07-15 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0076_auto_20180715_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='applicationtype',
            field=models.CharField(blank=True, choices=[('CA', 'CASA Program'), ('SPED', 'Special Education Program'), ('GS', 'Grade School Program'), ('SH', 'Senior High School Program'), ('JH', 'Junior High School Program')], default='CA', help_text='Choose Application Program', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='civilstatus',
            field=models.CharField(blank=True, choices=[('M', 'Married'), ('SP', 'Single Parent'), ('W', 'Widowed'), ('D', 'Divorcee')], default='M', help_text='Please select Civit Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='illnessinfo',
            name='illnessinfo',
            field=models.CharField(choices=[('A', 'Allergy'), ('AST', 'Asthma'), ('HP', 'Heart Problem'), ('HMP', 'Hematologic Problem'), ('SZ', 'Seizures'), ('ANE', 'Anemia'), ('O', 'Others'), ('DM', 'Diabetes Mellitus'), ('TP', 'Thyroid Problem'), ('MP', 'Metabolc Problem'), ('DP', 'Dermatology Problem'), ('EPL', 'Epilepsy'), ('CV', 'Convulsion'), ('VP', 'Viral Infection'), ('GP', 'Gastrointestinal Problems'), ('HT', 'Hypertension'), ('LP', 'Lung Problem'), ('EP', 'Ear Problems')], default='A', max_length=64, verbose_name='Illness Information'),
        ),
        migrations.AlterField(
            model_name='presentcondition',
            name='currentcondition',
            field=models.CharField(choices=[('CO', 'COUGH'), ('H', 'HEADACHE'), ('0', 'OTHERS'), ('F', 'FEVER'), ('C', 'COLDS'), ('S', 'STOMACH ACHE'), ('D', 'DIARRHEA'), ('V', 'VOMITING'), ('L', 'LBM')], max_length=64, verbose_name='Current Medical Condition'),
        ),
        migrations.AlterField(
            model_name='students',
            name='groupinfo',
            field=models.CharField(blank=True, choices=[('G4', 'GRADE 4'), ('TEP', 'TEACH PM'), ('CA', 'CASA AFTERNOON 1:30'), ('G6', 'GRADE 6'), ('G2', 'GRADE 2'), ('G5', 'GRADE 5'), ('G8', 'GRADE 8'), ('G1', 'GRADE 1'), ('TEP-GR1', 'TEACH PM GRADE 1'), ('TEP-GR2', 'TEACH PM GRADE 2'), ('G3', 'GRADE 3'), ('G7', 'GRADE 7'), ('G10', 'GRADE 10'), ('TEA', 'TEACH AM'), ('G9', 'GRADE 9'), ('TEP-GR2', 'TEACH PM GRADE 3'), ('PG', 'PLAY GROUP'), ('CM', 'CASA AM')], default='CM', help_text='Choose Group for Students', max_length=10),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='rolegroup',
            field=models.CharField(blank=True, choices=[('SH', 'SCHOOL HEAD'), ('S', 'STAFF'), ('F', 'FACULTY')], default='F', help_text='Please choose Role / Duty', max_length=10),
        ),
    ]
