# Generated by Django 2.0.6 on 2018-07-15 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0077_auto_20180715_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='applicationtype',
            field=models.CharField(blank=True, choices=[('SPED', 'Special Education Program'), ('GS', 'Grade School Program'), ('CA', 'CASA Program'), ('SH', 'Senior High School Program'), ('JH', 'Junior High School Program')], default='CA', help_text='Choose Application Program', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='childsname',
            field=models.CharField(blank=True, max_length=300, verbose_name='Students'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='civilstatus',
            field=models.CharField(blank=True, choices=[('M', 'Married'), ('SP', 'Single Parent'), ('D', 'Divorcee'), ('W', 'Widowed')], default='M', help_text='Please select Civit Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='religion',
            field=models.CharField(blank=True, choices=[('M', 'Muslim'), ('I', 'INC'), ('B', 'Buddhist'), ('C', 'Catholic')], default='C', help_text='Please select Religion', max_length=30),
        ),
        migrations.AlterField(
            model_name='illnessinfo',
            name='illnessinfo',
            field=models.CharField(choices=[('TP', 'Thyroid Problem'), ('AST', 'Asthma'), ('LP', 'Lung Problem'), ('SZ', 'Seizures'), ('DM', 'Diabetes Mellitus'), ('HP', 'Heart Problem'), ('ANE', 'Anemia'), ('EPL', 'Epilepsy'), ('DP', 'Dermatology Problem'), ('A', 'Allergy'), ('GP', 'Gastrointestinal Problems'), ('HT', 'Hypertension'), ('MP', 'Metabolc Problem'), ('CV', 'Convulsion'), ('VP', 'Viral Infection'), ('O', 'Others'), ('EP', 'Ear Problems'), ('HMP', 'Hematologic Problem')], default='A', max_length=64, verbose_name='Illness Information'),
        ),
        migrations.AlterField(
            model_name='presentcondition',
            name='currentcondition',
            field=models.CharField(choices=[('F', 'FEVER'), ('L', 'LBM'), ('C', 'COLDS'), ('V', 'VOMITING'), ('D', 'DIARRHEA'), ('0', 'OTHERS'), ('CO', 'COUGH'), ('H', 'HEADACHE'), ('S', 'STOMACH ACHE')], max_length=64, verbose_name='Current Medical Condition'),
        ),
        migrations.AlterField(
            model_name='students',
            name='groupinfo',
            field=models.CharField(blank=True, choices=[('TEP-GR2', 'TEACH PM GRADE 2'), ('G1', 'GRADE 1'), ('TEA', 'TEACH AM'), ('CA', 'CASA AFTERNOON 1:30'), ('G7', 'GRADE 7'), ('G9', 'GRADE 9'), ('G10', 'GRADE 10'), ('CM', 'CASA AM'), ('G4', 'GRADE 4'), ('G2', 'GRADE 2'), ('G6', 'GRADE 6'), ('TEP-GR1', 'TEACH PM GRADE 1'), ('G5', 'GRADE 5'), ('TEP', 'TEACH PM'), ('G8', 'GRADE 8'), ('PG', 'PLAY GROUP'), ('G3', 'GRADE 3'), ('TEP-GR2', 'TEACH PM GRADE 3')], default='CM', help_text='Choose Group for Students', max_length=10),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='rolegroup',
            field=models.CharField(blank=True, choices=[('S', 'STAFF'), ('F', 'FACULTY'), ('SH', 'SCHOOL HEAD')], default='F', help_text='Please choose Role / Duty', max_length=10),
        ),
    ]
