# Generated by Django 2.0.6 on 2018-07-15 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0078_auto_20180715_0539'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='childsnameone',
            field=models.ForeignKey(max_length=64, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students_name', to='students.Students', verbose_name='Additional Child'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='applicationtype',
            field=models.CharField(blank=True, choices=[('SH', 'Senior High School Program'), ('CA', 'CASA Program'), ('GS', 'Grade School Program'), ('SPED', 'Special Education Program'), ('JH', 'Junior High School Program')], default='CA', help_text='Choose Application Program', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='childsname',
            field=models.CharField(blank=True, max_length=300, verbose_name='Childs Name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='civilstatus',
            field=models.CharField(blank=True, choices=[('SP', 'Single Parent'), ('W', 'Widowed'), ('D', 'Divorcee'), ('M', 'Married')], default='M', help_text='Please select Civit Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='religion',
            field=models.CharField(blank=True, choices=[('I', 'INC'), ('B', 'Buddhist'), ('M', 'Muslim'), ('C', 'Catholic')], default='C', help_text='Please select Religion', max_length=30),
        ),
        migrations.AlterField(
            model_name='illnessinfo',
            name='illnessinfo',
            field=models.CharField(choices=[('EP', 'Ear Problems'), ('DM', 'Diabetes Mellitus'), ('GP', 'Gastrointestinal Problems'), ('HP', 'Heart Problem'), ('SZ', 'Seizures'), ('A', 'Allergy'), ('CV', 'Convulsion'), ('EPL', 'Epilepsy'), ('LP', 'Lung Problem'), ('VP', 'Viral Infection'), ('ANE', 'Anemia'), ('AST', 'Asthma'), ('TP', 'Thyroid Problem'), ('HMP', 'Hematologic Problem'), ('HT', 'Hypertension'), ('O', 'Others'), ('DP', 'Dermatology Problem'), ('MP', 'Metabolc Problem')], default='A', max_length=64, verbose_name='Illness Information'),
        ),
        migrations.AlterField(
            model_name='presentcondition',
            name='currentcondition',
            field=models.CharField(choices=[('L', 'LBM'), ('CO', 'COUGH'), ('D', 'DIARRHEA'), ('F', 'FEVER'), ('S', 'STOMACH ACHE'), ('C', 'COLDS'), ('H', 'HEADACHE'), ('V', 'VOMITING'), ('0', 'OTHERS')], max_length=64, verbose_name='Current Medical Condition'),
        ),
        migrations.AlterField(
            model_name='students',
            name='groupinfo',
            field=models.CharField(blank=True, choices=[('PG', 'PLAY GROUP'), ('G5', 'GRADE 5'), ('G2', 'GRADE 2'), ('G6', 'GRADE 6'), ('TEA', 'TEACH AM'), ('TEP-GR2', 'TEACH PM GRADE 3'), ('TEP', 'TEACH PM'), ('CM', 'CASA AM'), ('G1', 'GRADE 1'), ('CA', 'CASA AFTERNOON 1:30'), ('G8', 'GRADE 8'), ('G9', 'GRADE 9'), ('G10', 'GRADE 10'), ('G7', 'GRADE 7'), ('G4', 'GRADE 4'), ('G3', 'GRADE 3'), ('TEP-GR1', 'TEACH PM GRADE 1'), ('TEP-GR2', 'TEACH PM GRADE 2')], default='CM', help_text='Choose Group for Students', max_length=10),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='rolegroup',
            field=models.CharField(blank=True, choices=[('S', 'STAFF'), ('SH', 'SCHOOL HEAD'), ('F', 'FACULTY')], default='F', help_text='Please choose Role / Duty', max_length=10),
        ),
    ]
