# Generated by Django 2.0.6 on 2018-07-15 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0079_auto_20180715_0557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='childsnameone',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='applicationtype',
            field=models.CharField(blank=True, choices=[('GS', 'Grade School Program'), ('SPED', 'Special Education Program'), ('JH', 'Junior High School Program'), ('CA', 'CASA Program'), ('SH', 'Senior High School Program')], default='CA', help_text='Choose Application Program', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='civilstatus',
            field=models.CharField(blank=True, choices=[('SP', 'Single Parent'), ('M', 'Married'), ('W', 'Widowed'), ('D', 'Divorcee')], default='M', help_text='Please select Civit Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='religion',
            field=models.CharField(blank=True, choices=[('C', 'Catholic'), ('I', 'INC'), ('M', 'Muslim'), ('B', 'Buddhist')], default='C', help_text='Please select Religion', max_length=30),
        ),
        migrations.AlterField(
            model_name='illnessinfo',
            name='illnessinfo',
            field=models.CharField(choices=[('MP', 'Metabolc Problem'), ('HP', 'Heart Problem'), ('GP', 'Gastrointestinal Problems'), ('HT', 'Hypertension'), ('EP', 'Ear Problems'), ('SZ', 'Seizures'), ('EPL', 'Epilepsy'), ('O', 'Others'), ('VP', 'Viral Infection'), ('ANE', 'Anemia'), ('TP', 'Thyroid Problem'), ('DM', 'Diabetes Mellitus'), ('HMP', 'Hematologic Problem'), ('AST', 'Asthma'), ('A', 'Allergy'), ('CV', 'Convulsion'), ('LP', 'Lung Problem'), ('DP', 'Dermatology Problem')], default='A', max_length=64, verbose_name='Illness Information'),
        ),
        migrations.AlterField(
            model_name='presentcondition',
            name='currentcondition',
            field=models.CharField(choices=[('D', 'DIARRHEA'), ('S', 'STOMACH ACHE'), ('C', 'COLDS'), ('0', 'OTHERS'), ('CO', 'COUGH'), ('F', 'FEVER'), ('H', 'HEADACHE'), ('V', 'VOMITING'), ('L', 'LBM')], max_length=64, verbose_name='Current Medical Condition'),
        ),
        migrations.AlterField(
            model_name='students',
            name='groupinfo',
            field=models.CharField(blank=True, choices=[('G2', 'GRADE 2'), ('G8', 'GRADE 8'), ('G1', 'GRADE 1'), ('TEP-GR2', 'TEACH PM GRADE 3'), ('G6', 'GRADE 6'), ('G4', 'GRADE 4'), ('TEP', 'TEACH PM'), ('G5', 'GRADE 5'), ('G9', 'GRADE 9'), ('TEP-GR1', 'TEACH PM GRADE 1'), ('TEA', 'TEACH AM'), ('PG', 'PLAY GROUP'), ('G3', 'GRADE 3'), ('G10', 'GRADE 10'), ('TEP-GR2', 'TEACH PM GRADE 2'), ('CM', 'CASA AM'), ('CA', 'CASA AFTERNOON 1:30'), ('G7', 'GRADE 7')], default='CM', help_text='Choose Group for Students', max_length=10),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='rolegroup',
            field=models.CharField(blank=True, choices=[('SH', 'SCHOOL HEAD'), ('S', 'STAFF'), ('F', 'FACULTY')], default='F', help_text='Please choose Role / Duty', max_length=10),
        ),
    ]
