# Generated by Django 2.0.6 on 2018-07-16 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0080_auto_20180715_0634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentbio',
            name='parentsnameinfo',
        ),
        migrations.AddField(
            model_name='studentbio',
            name='guardiansname',
            field=models.CharField(blank=True, max_length=64, verbose_name='Guardians Name'),
        ),
        migrations.AddField(
            model_name='studentbio',
            name='momsname',
            field=models.CharField(blank=True, max_length=64, verbose_name='Mothers Name'),
        ),
        migrations.AddField(
            model_name='studentbio',
            name='popsname',
            field=models.CharField(blank=True, max_length=64, verbose_name='Fathers Name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='applicationtype',
            field=models.CharField(blank=True, choices=[('SH', 'Senior High School Program'), ('GS', 'Grade School Program'), ('CA', 'CASA Program'), ('SPED', 'Special Education Program'), ('JH', 'Junior High School Program')], default='CA', help_text='Choose Application Program', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='civilstatus',
            field=models.CharField(blank=True, choices=[('D', 'Divorcee'), ('M', 'Married'), ('W', 'Widowed'), ('SP', 'Single Parent')], default='M', help_text='Please select Civit Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='religion',
            field=models.CharField(blank=True, choices=[('C', 'Catholic'), ('M', 'Muslim'), ('B', 'Buddhist'), ('I', 'INC')], default='C', help_text='Please select Religion', max_length=30),
        ),
        migrations.AlterField(
            model_name='illnessinfo',
            name='illnessinfo',
            field=models.CharField(choices=[('ANE', 'Anemia'), ('AST', 'Asthma'), ('DM', 'Diabetes Mellitus'), ('SZ', 'Seizures'), ('DP', 'Dermatology Problem'), ('GP', 'Gastrointestinal Problems'), ('EPL', 'Epilepsy'), ('TP', 'Thyroid Problem'), ('HT', 'Hypertension'), ('EP', 'Ear Problems'), ('LP', 'Lung Problem'), ('MP', 'Metabolc Problem'), ('VP', 'Viral Infection'), ('O', 'Others'), ('A', 'Allergy'), ('CV', 'Convulsion'), ('HP', 'Heart Problem'), ('HMP', 'Hematologic Problem')], default='A', max_length=64, verbose_name='Illness Information'),
        ),
        migrations.AlterField(
            model_name='presentcondition',
            name='currentcondition',
            field=models.CharField(choices=[('D', 'DIARRHEA'), ('C', 'COLDS'), ('S', 'STOMACH ACHE'), ('V', 'VOMITING'), ('F', 'FEVER'), ('L', 'LBM'), ('CO', 'COUGH'), ('0', 'OTHERS'), ('H', 'HEADACHE')], max_length=64, verbose_name='Current Medical Condition'),
        ),
        migrations.AlterField(
            model_name='students',
            name='groupinfo',
            field=models.CharField(blank=True, choices=[('TEP-GR1', 'TEACH PM GRADE 1'), ('G9', 'GRADE 9'), ('TEA', 'TEACH AM'), ('G1', 'GRADE 1'), ('TEP-GR2', 'TEACH PM GRADE 2'), ('G8', 'GRADE 8'), ('PG', 'PLAY GROUP'), ('G2', 'GRADE 2'), ('G7', 'GRADE 7'), ('G10', 'GRADE 10'), ('TEP', 'TEACH PM'), ('G5', 'GRADE 5'), ('G3', 'GRADE 3'), ('G6', 'GRADE 6'), ('TEP-GR2', 'TEACH PM GRADE 3'), ('CA', 'CASA AFTERNOON 1:30'), ('CM', 'CASA AM'), ('G4', 'GRADE 4')], default='CM', help_text='Choose Group for Students', max_length=10),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='rolegroup',
            field=models.CharField(blank=True, choices=[('F', 'FACULTY'), ('S', 'STAFF'), ('SH', 'SCHOOL HEAD')], default='F', help_text='Please choose Role / Duty', max_length=10),
        ),
    ]
