# Generated by Django 2.0.6 on 2018-07-16 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0081_auto_20180716_0606'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentbio',
            name='username',
            field=models.ForeignKey(blank=True, max_length=64, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customuser_username', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='applicationtype',
            field=models.CharField(blank=True, choices=[('JH', 'Junior High School Program'), ('SPED', 'Special Education Program'), ('CA', 'CASA Program'), ('SH', 'Senior High School Program'), ('GS', 'Grade School Program')], default='CA', help_text='Choose Application Program', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='civilstatus',
            field=models.CharField(blank=True, choices=[('M', 'Married'), ('SP', 'Single Parent'), ('W', 'Widowed'), ('D', 'Divorcee')], default='M', help_text='Please select Civit Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='religion',
            field=models.CharField(blank=True, choices=[('M', 'Muslim'), ('I', 'INC'), ('B', 'Buddhist'), ('C', 'Catholic')], default='C', help_text='Please select Religion', max_length=30),
        ),
        migrations.AlterField(
            model_name='illnessinfo',
            name='illnessinfo',
            field=models.CharField(choices=[('HP', 'Heart Problem'), ('ANE', 'Anemia'), ('AST', 'Asthma'), ('MP', 'Metabolc Problem'), ('SZ', 'Seizures'), ('A', 'Allergy'), ('CV', 'Convulsion'), ('EPL', 'Epilepsy'), ('O', 'Others'), ('VP', 'Viral Infection'), ('HMP', 'Hematologic Problem'), ('DM', 'Diabetes Mellitus'), ('GP', 'Gastrointestinal Problems'), ('EP', 'Ear Problems'), ('TP', 'Thyroid Problem'), ('LP', 'Lung Problem'), ('HT', 'Hypertension'), ('DP', 'Dermatology Problem')], default='A', max_length=64, verbose_name='Illness Information'),
        ),
        migrations.AlterField(
            model_name='presentcondition',
            name='currentcondition',
            field=models.CharField(choices=[('0', 'OTHERS'), ('V', 'VOMITING'), ('CO', 'COUGH'), ('H', 'HEADACHE'), ('D', 'DIARRHEA'), ('L', 'LBM'), ('F', 'FEVER'), ('C', 'COLDS'), ('S', 'STOMACH ACHE')], max_length=64, verbose_name='Current Medical Condition'),
        ),
        migrations.AlterField(
            model_name='students',
            name='groupinfo',
            field=models.CharField(blank=True, choices=[('G2', 'GRADE 2'), ('CM', 'CASA AM'), ('TEP-GR1', 'TEACH PM GRADE 1'), ('G8', 'GRADE 8'), ('G4', 'GRADE 4'), ('TEP-GR2', 'TEACH PM GRADE 3'), ('TEP', 'TEACH PM'), ('TEA', 'TEACH AM'), ('G5', 'GRADE 5'), ('G7', 'GRADE 7'), ('G9', 'GRADE 9'), ('G3', 'GRADE 3'), ('G10', 'GRADE 10'), ('G6', 'GRADE 6'), ('G1', 'GRADE 1'), ('PG', 'PLAY GROUP'), ('CA', 'CASA AFTERNOON 1:30'), ('TEP-GR2', 'TEACH PM GRADE 2')], default='CM', help_text='Choose Group for Students', max_length=10),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='rolegroup',
            field=models.CharField(blank=True, choices=[('SH', 'SCHOOL HEAD'), ('S', 'STAFF'), ('F', 'FACULTY')], default='F', help_text='Please choose Role / Duty', max_length=10),
        ),
    ]
