# Generated by Django 2.0.6 on 2018-07-16 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0082_auto_20180716_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='applicationtype',
            field=models.CharField(blank=True, choices=[('SH', 'Senior High School Program'), ('CA', 'CASA Program'), ('SPED', 'Special Education Program'), ('JH', 'Junior High School Program'), ('GS', 'Grade School Program')], default='CA', help_text='Choose Application Program', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='civilstatus',
            field=models.CharField(blank=True, choices=[('D', 'Divorcee'), ('M', 'Married'), ('W', 'Widowed'), ('SP', 'Single Parent')], default='M', help_text='Please select Civit Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='religion',
            field=models.CharField(blank=True, choices=[('I', 'INC'), ('C', 'Catholic'), ('B', 'Buddhist'), ('M', 'Muslim')], default='C', help_text='Please select Religion', max_length=30),
        ),
        migrations.AlterField(
            model_name='illnessinfo',
            name='illnessinfo',
            field=models.CharField(choices=[('ANE', 'Anemia'), ('A', 'Allergy'), ('LP', 'Lung Problem'), ('SZ', 'Seizures'), ('CV', 'Convulsion'), ('EPL', 'Epilepsy'), ('HP', 'Heart Problem'), ('MP', 'Metabolc Problem'), ('EP', 'Ear Problems'), ('DP', 'Dermatology Problem'), ('O', 'Others'), ('HT', 'Hypertension'), ('DM', 'Diabetes Mellitus'), ('TP', 'Thyroid Problem'), ('AST', 'Asthma'), ('GP', 'Gastrointestinal Problems'), ('VP', 'Viral Infection'), ('HMP', 'Hematologic Problem')], default='A', max_length=64, verbose_name='Illness Information'),
        ),
        migrations.AlterField(
            model_name='presentcondition',
            name='currentcondition',
            field=models.CharField(choices=[('L', 'LBM'), ('S', 'STOMACH ACHE'), ('F', 'FEVER'), ('C', 'COLDS'), ('D', 'DIARRHEA'), ('H', 'HEADACHE'), ('V', 'VOMITING'), ('CO', 'COUGH'), ('0', 'OTHERS')], max_length=64, verbose_name='Current Medical Condition'),
        ),
        migrations.AlterField(
            model_name='studentbio',
            name='username',
            field=models.ForeignKey(blank=True, max_length=64, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customuser_name', to=settings.AUTH_USER_MODEL, verbose_name='Primary User Info'),
        ),
        migrations.AlterField(
            model_name='students',
            name='groupinfo',
            field=models.CharField(blank=True, choices=[('G8', 'GRADE 8'), ('G2', 'GRADE 2'), ('G7', 'GRADE 7'), ('G9', 'GRADE 9'), ('TEP-GR2', 'TEACH PM GRADE 3'), ('CM', 'CASA AM'), ('PG', 'PLAY GROUP'), ('TEP-GR1', 'TEACH PM GRADE 1'), ('CA', 'CASA AFTERNOON 1:30'), ('G3', 'GRADE 3'), ('G5', 'GRADE 5'), ('G6', 'GRADE 6'), ('TEA', 'TEACH AM'), ('G4', 'GRADE 4'), ('TEP-GR2', 'TEACH PM GRADE 2'), ('G1', 'GRADE 1'), ('TEP', 'TEACH PM'), ('G10', 'GRADE 10')], default='CM', help_text='Choose Group for Students', max_length=10),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='rolegroup',
            field=models.CharField(blank=True, choices=[('S', 'STAFF'), ('F', 'FACULTY'), ('SH', 'SCHOOL HEAD')], default='F', help_text='Please choose Role / Duty', max_length=10),
        ),
    ]
