# Generated by Django 2.0.6 on 2018-07-16 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0083_auto_20180716_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='applicationtype',
            field=models.CharField(blank=True, choices=[('GS', 'Grade School Program'), ('CA', 'CASA Program'), ('SH', 'Senior High School Program'), ('JH', 'Junior High School Program'), ('SPED', 'Special Education Program')], default='CA', help_text='Choose Application Program', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='civilstatus',
            field=models.CharField(blank=True, choices=[('D', 'Divorcee'), ('M', 'Married'), ('SP', 'Single Parent'), ('W', 'Widowed')], default='M', help_text='Please select Civit Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='religion',
            field=models.CharField(blank=True, choices=[('M', 'Muslim'), ('I', 'INC'), ('C', 'Catholic'), ('B', 'Buddhist')], default='C', help_text='Please select Religion', max_length=30),
        ),
        migrations.AlterField(
            model_name='illnessinfo',
            name='illnessinfo',
            field=models.CharField(choices=[('AST', 'Asthma'), ('VP', 'Viral Infection'), ('A', 'Allergy'), ('ANE', 'Anemia'), ('HT', 'Hypertension'), ('DM', 'Diabetes Mellitus'), ('DP', 'Dermatology Problem'), ('LP', 'Lung Problem'), ('SZ', 'Seizures'), ('CV', 'Convulsion'), ('EPL', 'Epilepsy'), ('TP', 'Thyroid Problem'), ('O', 'Others'), ('MP', 'Metabolc Problem'), ('EP', 'Ear Problems'), ('HMP', 'Hematologic Problem'), ('GP', 'Gastrointestinal Problems'), ('HP', 'Heart Problem')], default='A', max_length=64, verbose_name='Illness Information'),
        ),
        migrations.AlterField(
            model_name='presentcondition',
            name='currentcondition',
            field=models.CharField(choices=[('H', 'HEADACHE'), ('V', 'VOMITING'), ('0', 'OTHERS'), ('D', 'DIARRHEA'), ('F', 'FEVER'), ('L', 'LBM'), ('CO', 'COUGH'), ('C', 'COLDS'), ('S', 'STOMACH ACHE')], max_length=64, verbose_name='Current Medical Condition'),
        ),
        migrations.AlterField(
            model_name='studentbio',
            name='username',
            field=models.OneToOneField(blank=True, max_length=64, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customuser_username', to=settings.AUTH_USER_MODEL, verbose_name='Primary User Info'),
        ),
        migrations.AlterField(
            model_name='students',
            name='groupinfo',
            field=models.CharField(blank=True, choices=[('TEP-GR2', 'TEACH PM GRADE 3'), ('G1', 'GRADE 1'), ('TEA', 'TEACH AM'), ('G2', 'GRADE 2'), ('G6', 'GRADE 6'), ('G8', 'GRADE 8'), ('G4', 'GRADE 4'), ('TEP-GR1', 'TEACH PM GRADE 1'), ('TEP', 'TEACH PM'), ('G5', 'GRADE 5'), ('PG', 'PLAY GROUP'), ('CM', 'CASA AM'), ('G3', 'GRADE 3'), ('TEP-GR2', 'TEACH PM GRADE 2'), ('G10', 'GRADE 10'), ('G9', 'GRADE 9'), ('G7', 'GRADE 7'), ('CA', 'CASA AFTERNOON 1:30')], default='CM', help_text='Choose Group for Students', max_length=10),
        ),
    ]
