# Generated by Django 2.0.6 on 2018-07-16 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0084_auto_20180716_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='applicationtype',
            field=models.CharField(blank=True, choices=[('JH', 'Junior High School Program'), ('SPED', 'Special Education Program'), ('SH', 'Senior High School Program'), ('GS', 'Grade School Program'), ('CA', 'CASA Program')], default='CA', help_text='Choose Application Program', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='civilstatus',
            field=models.CharField(blank=True, choices=[('D', 'Divorcee'), ('M', 'Married'), ('W', 'Widowed'), ('SP', 'Single Parent')], default='M', help_text='Please select Civit Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='religion',
            field=models.CharField(blank=True, choices=[('I', 'INC'), ('C', 'Catholic'), ('B', 'Buddhist'), ('M', 'Muslim')], default='C', help_text='Please select Religion', max_length=30),
        ),
        migrations.AlterField(
            model_name='illnessinfo',
            name='illnessinfo',
            field=models.CharField(choices=[('TP', 'Thyroid Problem'), ('DP', 'Dermatology Problem'), ('EPL', 'Epilepsy'), ('GP', 'Gastrointestinal Problems'), ('HT', 'Hypertension'), ('LP', 'Lung Problem'), ('VP', 'Viral Infection'), ('SZ', 'Seizures'), ('DM', 'Diabetes Mellitus'), ('AST', 'Asthma'), ('HP', 'Heart Problem'), ('EP', 'Ear Problems'), ('A', 'Allergy'), ('CV', 'Convulsion'), ('ANE', 'Anemia'), ('O', 'Others'), ('MP', 'Metabolc Problem'), ('HMP', 'Hematologic Problem')], default='A', max_length=64, verbose_name='Illness Information'),
        ),
        migrations.AlterField(
            model_name='presentcondition',
            name='currentcondition',
            field=models.CharField(choices=[('0', 'OTHERS'), ('F', 'FEVER'), ('H', 'HEADACHE'), ('V', 'VOMITING'), ('L', 'LBM'), ('CO', 'COUGH'), ('S', 'STOMACH ACHE'), ('D', 'DIARRHEA'), ('C', 'COLDS')], max_length=64, verbose_name='Current Medical Condition'),
        ),
        migrations.AlterField(
            model_name='studentbio',
            name='username',
            field=models.OneToOneField(blank=True, max_length=64, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_customusername', to=settings.AUTH_USER_MODEL, verbose_name='Primary User Info'),
        ),
        migrations.AlterField(
            model_name='students',
            name='groupinfo',
            field=models.CharField(blank=True, choices=[('G1', 'GRADE 1'), ('G7', 'GRADE 7'), ('TEP-GR1', 'TEACH PM GRADE 1'), ('PG', 'PLAY GROUP'), ('G5', 'GRADE 5'), ('TEP-GR2', 'TEACH PM GRADE 3'), ('TEA', 'TEACH AM'), ('G2', 'GRADE 2'), ('G4', 'GRADE 4'), ('G6', 'GRADE 6'), ('CA', 'CASA AFTERNOON 1:30'), ('G3', 'GRADE 3'), ('G9', 'GRADE 9'), ('G10', 'GRADE 10'), ('CM', 'CASA AM'), ('TEP', 'TEACH PM'), ('G8', 'GRADE 8'), ('TEP-GR2', 'TEACH PM GRADE 2')], default='CM', help_text='Choose Group for Students', max_length=10),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='rolegroup',
            field=models.CharField(blank=True, choices=[('F', 'FACULTY'), ('S', 'STAFF'), ('SH', 'SCHOOL HEAD')], default='F', help_text='Please choose Role / Duty', max_length=10),
        ),
    ]
