# Generated by Django 2.0.6 on 2018-07-16 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0086_auto_20180716_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='applicationtype',
            field=models.CharField(blank=True, choices=[('SPED', 'Special Education Program'), ('JH', 'Junior High School Program'), ('SH', 'Senior High School Program'), ('GS', 'Grade School Program'), ('CA', 'CASA Program')], default='CA', help_text='Choose Application Program', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='civilstatus',
            field=models.CharField(blank=True, choices=[('W', 'Widowed'), ('D', 'Divorcee'), ('M', 'Married'), ('SP', 'Single Parent')], default='M', help_text='Please select Civit Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='religion',
            field=models.CharField(blank=True, choices=[('C', 'Catholic'), ('B', 'Buddhist'), ('I', 'INC'), ('M', 'Muslim')], default='C', help_text='Please select Religion', max_length=30),
        ),
        migrations.AlterField(
            model_name='illnessinfo',
            name='illnessinfo',
            field=models.CharField(choices=[('EP', 'Ear Problems'), ('DP', 'Dermatology Problem'), ('HP', 'Heart Problem'), ('ANE', 'Anemia'), ('HT', 'Hypertension'), ('CV', 'Convulsion'), ('LP', 'Lung Problem'), ('EPL', 'Epilepsy'), ('DM', 'Diabetes Mellitus'), ('GP', 'Gastrointestinal Problems'), ('VP', 'Viral Infection'), ('MP', 'Metabolc Problem'), ('O', 'Others'), ('HMP', 'Hematologic Problem'), ('TP', 'Thyroid Problem'), ('A', 'Allergy'), ('AST', 'Asthma'), ('SZ', 'Seizures')], default='A', max_length=64, verbose_name='Illness Information'),
        ),
        migrations.AlterField(
            model_name='presentcondition',
            name='currentcondition',
            field=models.CharField(choices=[('F', 'FEVER'), ('L', 'LBM'), ('D', 'DIARRHEA'), ('0', 'OTHERS'), ('H', 'HEADACHE'), ('V', 'VOMITING'), ('CO', 'COUGH'), ('C', 'COLDS'), ('S', 'STOMACH ACHE')], max_length=64, verbose_name='Current Medical Condition'),
        ),
        migrations.AlterField(
            model_name='studentbio',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_userinfo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='students',
            name='groupinfo',
            field=models.CharField(blank=True, choices=[('G8', 'GRADE 8'), ('PG', 'PLAY GROUP'), ('CA', 'CASA AFTERNOON 1:30'), ('TEP', 'TEACH PM'), ('G5', 'GRADE 5'), ('TEP-GR2', 'TEACH PM GRADE 2'), ('G1', 'GRADE 1'), ('G7', 'GRADE 7'), ('G4', 'GRADE 4'), ('G9', 'GRADE 9'), ('TEA', 'TEACH AM'), ('TEP-GR2', 'TEACH PM GRADE 3'), ('G3', 'GRADE 3'), ('G10', 'GRADE 10'), ('G2', 'GRADE 2'), ('CM', 'CASA AM'), ('TEP-GR1', 'TEACH PM GRADE 1'), ('G6', 'GRADE 6')], default='CM', help_text='Choose Group for Students', max_length=10),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='rolegroup',
            field=models.CharField(blank=True, choices=[('SH', 'SCHOOL HEAD'), ('F', 'FACULTY'), ('S', 'STAFF')], default='F', help_text='Please choose Role / Duty', max_length=10),
        ),
    ]
