# Generated by Django 2.0.6 on 2018-07-21 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0087_auto_20180716_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='applicationtype',
            field=models.CharField(blank=True, choices=[('SH', 'Senior High School Program'), ('JH', 'Junior High School Program'), ('CA', 'CASA Program'), ('SPED', 'Special Education Program'), ('GS', 'Grade School Program')], default='CA', help_text='Choose Application Program', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='civilstatus',
            field=models.CharField(blank=True, choices=[('SP', 'Single Parent'), ('W', 'Widowed'), ('M', 'Married'), ('D', 'Divorcee')], default='M', help_text='Please select Civit Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='religion',
            field=models.CharField(blank=True, choices=[('B', 'Buddhist'), ('M', 'Muslim'), ('I', 'INC'), ('C', 'Catholic')], default='C', help_text='Please select Religion', max_length=30),
        ),
        migrations.AlterField(
            model_name='illnessinfo',
            name='illnessinfo',
            field=models.CharField(choices=[('EPL', 'Epilepsy'), ('HT', 'Hypertension'), ('DP', 'Dermatology Problem'), ('GP', 'Gastrointestinal Problems'), ('SZ', 'Seizures'), ('ANE', 'Anemia'), ('EP', 'Ear Problems'), ('MP', 'Metabolc Problem'), ('TP', 'Thyroid Problem'), ('VP', 'Viral Infection'), ('AST', 'Asthma'), ('HP', 'Heart Problem'), ('O', 'Others'), ('DM', 'Diabetes Mellitus'), ('CV', 'Convulsion'), ('HMP', 'Hematologic Problem'), ('LP', 'Lung Problem'), ('A', 'Allergy')], default='A', max_length=64, verbose_name='Illness Information'),
        ),
        migrations.AlterField(
            model_name='presentcondition',
            name='currentcondition',
            field=models.CharField(choices=[('0', 'OTHERS'), ('D', 'DIARRHEA'), ('C', 'COLDS'), ('H', 'HEADACHE'), ('V', 'VOMITING'), ('F', 'FEVER'), ('CO', 'COUGH'), ('S', 'STOMACH ACHE'), ('L', 'LBM')], max_length=64, verbose_name='Current Medical Condition'),
        ),
        migrations.AlterField(
            model_name='studentbio',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students_username', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='students',
            name='groupinfo',
            field=models.CharField(blank=True, choices=[('G9', 'GRADE 9'), ('TEP-GR2', 'TEACH PM GRADE 2'), ('G5', 'GRADE 5'), ('PG', 'PLAY GROUP'), ('G4', 'GRADE 4'), ('TEP-GR1', 'TEACH PM GRADE 1'), ('TEA', 'TEACH AM'), ('G6', 'GRADE 6'), ('G7', 'GRADE 7'), ('TEP', 'TEACH PM'), ('G8', 'GRADE 8'), ('TEP-GR2', 'TEACH PM GRADE 3'), ('CA', 'CASA AFTERNOON 1:30'), ('G2', 'GRADE 2'), ('G1', 'GRADE 1'), ('G3', 'GRADE 3'), ('G10', 'GRADE 10'), ('CM', 'CASA AM')], default='CM', help_text='Choose Group for Students', max_length=10),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='rolegroup',
            field=models.CharField(blank=True, choices=[('S', 'STAFF'), ('F', 'FACULTY'), ('SH', 'SCHOOL HEAD')], default='F', help_text='Please choose Role / Duty', max_length=10),
        ),
    ]
