# Generated by Django 2.0.6 on 2018-07-24 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0088_auto_20180721_0738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentbio',
            name='username',
        ),
        migrations.AddField(
            model_name='studentbio',
            name='user',
            field=models.OneToOneField(max_length=64, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='applicationtype',
            field=models.CharField(blank=True, choices=[('GS', 'Grade School Program'), ('JH', 'Junior High School Program'), ('SH', 'Senior High School Program'), ('SPED', 'Special Education Program'), ('CA', 'CASA Program')], default='CA', help_text='Choose Application Program', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='civilstatus',
            field=models.CharField(blank=True, choices=[('W', 'Widowed'), ('D', 'Divorcee'), ('M', 'Married'), ('SP', 'Single Parent')], default='M', help_text='Please select Civit Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='religion',
            field=models.CharField(blank=True, choices=[('B', 'Buddhist'), ('C', 'Catholic'), ('I', 'INC'), ('M', 'Muslim')], default='C', help_text='Please select Religion', max_length=30),
        ),
        migrations.AlterField(
            model_name='illnessinfo',
            name='illnessinfo',
            field=models.CharField(choices=[('HT', 'Hypertension'), ('HMP', 'Hematologic Problem'), ('SZ', 'Seizures'), ('O', 'Others'), ('MP', 'Metabolc Problem'), ('VP', 'Viral Infection'), ('CV', 'Convulsion'), ('EPL', 'Epilepsy'), ('TP', 'Thyroid Problem'), ('A', 'Allergy'), ('HP', 'Heart Problem'), ('AST', 'Asthma'), ('DM', 'Diabetes Mellitus'), ('ANE', 'Anemia'), ('GP', 'Gastrointestinal Problems'), ('LP', 'Lung Problem'), ('DP', 'Dermatology Problem'), ('EP', 'Ear Problems')], default='A', max_length=64, verbose_name='Illness Information'),
        ),
        migrations.AlterField(
            model_name='presentcondition',
            name='currentcondition',
            field=models.CharField(choices=[('F', 'FEVER'), ('V', 'VOMITING'), ('L', 'LBM'), ('S', 'STOMACH ACHE'), ('H', 'HEADACHE'), ('0', 'OTHERS'), ('C', 'COLDS'), ('CO', 'COUGH'), ('D', 'DIARRHEA')], max_length=64, verbose_name='Current Medical Condition'),
        ),
        migrations.AlterField(
            model_name='students',
            name='groupinfo',
            field=models.CharField(blank=True, choices=[('G8', 'GRADE 8'), ('CA', 'CASA AFTERNOON 1:30'), ('PG', 'PLAY GROUP'), ('G4', 'GRADE 4'), ('G5', 'GRADE 5'), ('G7', 'GRADE 7'), ('TEP-GR1', 'TEACH PM GRADE 1'), ('TEP-GR2', 'TEACH PM GRADE 3'), ('G9', 'GRADE 9'), ('CM', 'CASA AM'), ('TEP-GR2', 'TEACH PM GRADE 2'), ('G6', 'GRADE 6'), ('G1', 'GRADE 1'), ('G3', 'GRADE 3'), ('TEP', 'TEACH PM'), ('G10', 'GRADE 10'), ('G2', 'GRADE 2'), ('TEA', 'TEACH AM')], default='CM', help_text='Choose Group for Students', max_length=10),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='rolegroup',
            field=models.CharField(blank=True, choices=[('S', 'STAFF'), ('SH', 'SCHOOL HEAD'), ('F', 'FACULTY')], default='F', help_text='Please choose Role / Duty', max_length=10),
        ),
    ]
