# Generated by Django 2.0.6 on 2018-07-25 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0090_auto_20180725_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='applicationtype',
            field=models.CharField(blank=True, choices=[('GRADE SCHOOL PROGRAM', 'Grade School Program'), ('SPED', 'Special Education Program'), ('JUNIOR HIGH SCHOOL PROGRAM', 'Junior High School Program'), ('CASA PROGRAM', 'CASA Program'), ('SENIOR HIGH SCHOOL PROGRAM', 'Senior High School Program')], default='CASA PROGRAM', help_text='Choose Application Program', max_length=64),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='civilstatus',
            field=models.CharField(blank=True, choices=[('SP', 'Single Parent'), ('W', 'Widowed'), ('D', 'Divorcee'), ('M', 'Married')], default='M', help_text='Please select Civit Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='religion',
            field=models.CharField(blank=True, choices=[('I', 'INC'), ('B', 'Buddhist'), ('M', 'Muslim'), ('C', 'Catholic')], default='C', help_text='Please select Religion', max_length=30),
        ),
        migrations.AlterField(
            model_name='illnessinfo',
            name='illnessinfo',
            field=models.CharField(choices=[('DM', 'Diabetes Mellitus'), ('VP', 'Viral Infection'), ('AST', 'Asthma'), ('GP', 'Gastrointestinal Problems'), ('EPL', 'Epilepsy'), ('O', 'Others'), ('DP', 'Dermatology Problem'), ('ANE', 'Anemia'), ('HP', 'Heart Problem'), ('LP', 'Lung Problem'), ('MP', 'Metabolc Problem'), ('SZ', 'Seizures'), ('TP', 'Thyroid Problem'), ('HMP', 'Hematologic Problem'), ('HT', 'Hypertension'), ('CV', 'Convulsion'), ('EP', 'Ear Problems'), ('A', 'Allergy')], default='A', max_length=64, verbose_name='Illness Information'),
        ),
        migrations.AlterField(
            model_name='presentcondition',
            name='currentcondition',
            field=models.CharField(choices=[('H', 'HEADACHE'), ('S', 'STOMACH ACHE'), ('0', 'OTHERS'), ('D', 'DIARRHEA'), ('V', 'VOMITING'), ('F', 'FEVER'), ('L', 'LBM'), ('CO', 'COUGH'), ('C', 'COLDS')], max_length=64, verbose_name='Current Medical Condition'),
        ),
        migrations.AlterField(
            model_name='studentbio',
            name='user',
            field=models.ForeignKey(max_length=64, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='students',
            name='groupinfo',
            field=models.CharField(blank=True, choices=[('CM', 'CASA AM'), ('TEA', 'TEACH AM'), ('G5', 'GRADE 5'), ('G1', 'GRADE 1'), ('G4', 'GRADE 4'), ('TEP-GR2', 'TEACH PM GRADE 2'), ('PG', 'PLAY GROUP'), ('G7', 'GRADE 7'), ('G2', 'GRADE 2'), ('TEP-GR2', 'TEACH PM GRADE 3'), ('CA', 'CASA AFTERNOON 1:30'), ('G8', 'GRADE 8'), ('G9', 'GRADE 9'), ('G10', 'GRADE 10'), ('G3', 'GRADE 3'), ('TEP-GR1', 'TEACH PM GRADE 1'), ('G6', 'GRADE 6'), ('TEP', 'TEACH PM')], default='CM', help_text='Choose Group for Students', max_length=10),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='rolegroup',
            field=models.CharField(blank=True, choices=[('F', 'FACULTY'), ('S', 'STAFF'), ('SH', 'SCHOOL HEAD')], default='F', help_text='Please choose Role / Duty', max_length=10),
        ),
    ]
