# Generated by Django 2.0.6 on 2018-07-25 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0091_auto_20180725_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='applicationtype',
            field=models.CharField(blank=True, choices=[('CASA PROGRAM', 'CASA Program'), ('GRADE SCHOOL PROGRAM', 'Grade School Program'), ('JUNIOR HIGH SCHOOL PROGRAM', 'Junior High School Program'), ('SPED', 'Special Education Program'), ('SENIOR HIGH SCHOOL PROGRAM', 'Senior High School Program')], default='CASA PROGRAM', help_text='Choose Application Program', max_length=64),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='civilstatus',
            field=models.CharField(blank=True, choices=[('M', 'Married'), ('SP', 'Single Parent'), ('D', 'Divorcee'), ('W', 'Widowed')], default='M', help_text='Please select Civit Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='religion',
            field=models.CharField(blank=True, choices=[('C', 'Catholic'), ('I', 'INC'), ('M', 'Muslim'), ('B', 'Buddhist')], default='C', help_text='Please select Religion', max_length=30),
        ),
        migrations.AlterField(
            model_name='illnessinfo',
            name='illnessinfo',
            field=models.CharField(choices=[('AST', 'Asthma'), ('SZ', 'Seizures'), ('GP', 'Gastrointestinal Problems'), ('DP', 'Dermatology Problem'), ('DM', 'Diabetes Mellitus'), ('LP', 'Lung Problem'), ('EPL', 'Epilepsy'), ('O', 'Others'), ('HMP', 'Hematologic Problem'), ('CV', 'Convulsion'), ('EP', 'Ear Problems'), ('A', 'Allergy'), ('ANE', 'Anemia'), ('MP', 'Metabolc Problem'), ('TP', 'Thyroid Problem'), ('HT', 'Hypertension'), ('HP', 'Heart Problem'), ('VP', 'Viral Infection')], default='A', max_length=64, verbose_name='Illness Information'),
        ),
        migrations.AlterField(
            model_name='presentcondition',
            name='currentcondition',
            field=models.CharField(choices=[('C', 'COLDS'), ('D', 'DIARRHEA'), ('S', 'STOMACH ACHE'), ('L', 'LBM'), ('0', 'OTHERS'), ('F', 'FEVER'), ('V', 'VOMITING'), ('H', 'HEADACHE'), ('CO', 'COUGH')], max_length=64, verbose_name='Current Medical Condition'),
        ),
        migrations.AlterField(
            model_name='studentgrades',
            name='grades',
            field=models.CharField(choices=[('P', '87-91'), ('AP', '82-86'), ('D', '77-81'), ('A', '92-96'), ('B', '76'), ('E', '97-100')], default='B', help_text='Choose appropriate marks', max_length=64, verbose_name='Grading System'),
        ),
        migrations.AlterField(
            model_name='students',
            name='groupinfo',
            field=models.CharField(blank=True, choices=[('G9', 'GRADE 9'), ('TEP-GR2', 'TEACH PM GRADE 2'), ('TEA', 'TEACH AM'), ('G4', 'GRADE 4'), ('CA', 'CASA AFTERNOON 1:30'), ('G1', 'GRADE 1'), ('G10', 'GRADE 10'), ('G8', 'GRADE 8'), ('G2', 'GRADE 2'), ('TEP-GR1', 'TEACH PM GRADE 1'), ('CM', 'CASA AM'), ('TEP', 'TEACH PM'), ('G5', 'GRADE 5'), ('TEP-GR2', 'TEACH PM GRADE 3'), ('G7', 'GRADE 7'), ('G3', 'GRADE 3'), ('PG', 'PLAY GROUP'), ('G6', 'GRADE 6')], default='CM', help_text='Choose Group for Students', max_length=10),
        ),
        migrations.AddField(
            model_name='financialinfo',
            name='studentname',
            field=models.ForeignKey(max_length=64, on_delete=django.db.models.deletion.CASCADE, to='students.Students', verbose_name='Student Name'),
        ),
    ]
