# Generated by Django 2.0.6 on 2018-07-25 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0092_auto_20180725_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatementAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modeofpayment', models.CharField(choices=[('A', 'ANNUAL'), ('QRT', 'QUARTERLY'), ('SA', 'SEMI-ANNUAL')], default='A', help_text='Choose Terms of Payment', max_length=64, verbose_name='Mode of Payment')),
                ('musicclassprice', models.DecimalField(decimal_places=6, max_digits=20, verbose_name='Music Class Price')),
                ('bookspricetotal', models.DecimalField(decimal_places=6, max_digits=20, verbose_name='Books Price Total')),
                ('notebooks', models.DecimalField(decimal_places=6, max_digits=20, verbose_name='Notebook Price')),
                ('uniforms', models.DecimalField(decimal_places=6, max_digits=20, verbose_name='Uniform Price')),
                ('other', models.DecimalField(decimal_places=6, max_digits=20, verbose_name='Miscellaneous & Others')),
                ('totalprice', models.DecimalField(decimal_places=6, max_digits=20, verbose_name='Total Price')),
                ('reservationfee', models.DecimalField(decimal_places=6, max_digits=20, verbose_name='Reservation Fee')),
                ('discount', models.DecimalField(decimal_places=6, max_digits=20, verbose_name='Discount Fee')),
                ('gtotal', models.DecimalField(decimal_places=6, max_digits=20, verbose_name='Grand Total')),
                ('gradeyear', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, related_name='statement_gradeyear', to='students.GradeYear', verbose_name='Grade Year')),
            ],
        ),
        migrations.RemoveField(
            model_name='financialinfo',
            name='studentname',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='applicationtype',
            field=models.CharField(blank=True, choices=[('SENIOR HIGH SCHOOL PROGRAM', 'Senior High School Program'), ('SPED', 'Special Education Program'), ('CASA PROGRAM', 'CASA Program'), ('JUNIOR HIGH SCHOOL PROGRAM', 'Junior High School Program'), ('GRADE SCHOOL PROGRAM', 'Grade School Program')], default='CASA PROGRAM', help_text='Choose Application Program', max_length=64),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='civilstatus',
            field=models.CharField(blank=True, choices=[('SP', 'Single Parent'), ('W', 'Widowed'), ('D', 'Divorcee'), ('M', 'Married')], default='M', help_text='Please select Civit Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='religion',
            field=models.CharField(blank=True, choices=[('M', 'Muslim'), ('B', 'Buddhist'), ('I', 'INC'), ('C', 'Catholic')], default='C', help_text='Please select Religion', max_length=30),
        ),
        migrations.AlterField(
            model_name='illnessinfo',
            name='illnessinfo',
            field=models.CharField(choices=[('ANE', 'Anemia'), ('DM', 'Diabetes Mellitus'), ('MP', 'Metabolc Problem'), ('SZ', 'Seizures'), ('CV', 'Convulsion'), ('VP', 'Viral Infection'), ('TP', 'Thyroid Problem'), ('AST', 'Asthma'), ('HMP', 'Hematologic Problem'), ('HT', 'Hypertension'), ('EPL', 'Epilepsy'), ('DP', 'Dermatology Problem'), ('HP', 'Heart Problem'), ('EP', 'Ear Problems'), ('O', 'Others'), ('A', 'Allergy'), ('LP', 'Lung Problem'), ('GP', 'Gastrointestinal Problems')], default='A', max_length=64, verbose_name='Illness Information'),
        ),
        migrations.AlterField(
            model_name='presentcondition',
            name='currentcondition',
            field=models.CharField(choices=[('C', 'COLDS'), ('L', 'LBM'), ('CO', 'COUGH'), ('H', 'HEADACHE'), ('V', 'VOMITING'), ('D', 'DIARRHEA'), ('0', 'OTHERS'), ('F', 'FEVER'), ('S', 'STOMACH ACHE')], max_length=64, verbose_name='Current Medical Condition'),
        ),
        migrations.AlterField(
            model_name='studentgrades',
            name='grades',
            field=models.CharField(choices=[('77-81', 'D'), ('76', 'B'), ('92-96', 'A'), ('82-86', 'AP'), ('97-100', 'E'), ('87-91', 'P')], default='B', help_text='Choose appropriate marks', max_length=64, verbose_name='Grading System'),
        ),
        migrations.AlterField(
            model_name='students',
            name='groupinfo',
            field=models.CharField(blank=True, choices=[('G10', 'GRADE 10'), ('TEP-GR2', 'TEACH PM GRADE 3'), ('G6', 'GRADE 6'), ('PG', 'PLAY GROUP'), ('G1', 'GRADE 1'), ('CM', 'CASA AM'), ('TEP', 'TEACH PM'), ('TEA', 'TEACH AM'), ('G4', 'GRADE 4'), ('G3', 'GRADE 3'), ('TEP-GR1', 'TEACH PM GRADE 1'), ('CA', 'CASA AFTERNOON 1:30'), ('G8', 'GRADE 8'), ('G9', 'GRADE 9'), ('TEP-GR2', 'TEACH PM GRADE 2'), ('G7', 'GRADE 7'), ('G2', 'GRADE 2'), ('G5', 'GRADE 5')], default='CM', help_text='Choose Group for Students', max_length=10),
        ),
        migrations.DeleteModel(
            name='FinancialInfo',
        ),
        migrations.AddField(
            model_name='statementaccount',
            name='studentname',
            field=models.ForeignKey(max_length=64, on_delete=django.db.models.deletion.CASCADE, to='students.Students', verbose_name='Student Name'),
        ),
    ]
