# Generated by Django 2.0.6 on 2018-07-26 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0094_auto_20180726_0200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statementaccount',
            name='totalprice',
        ),
        migrations.RemoveField(
            model_name='statementaccount',
            name='totalprice_currency',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='applicationtype',
            field=models.CharField(blank=True, choices=[('SENIOR HIGH SCHOOL PROGRAM', 'Senior High School Program'), ('SPED', 'Special Education Program'), ('GRADE SCHOOL PROGRAM', 'Grade School Program'), ('JUNIOR HIGH SCHOOL PROGRAM', 'Junior High School Program'), ('CASA PROGRAM', 'CASA Program')], default='CASA PROGRAM', help_text='Choose Application Program', max_length=64),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='civilstatus',
            field=models.CharField(blank=True, choices=[('M', 'Married'), ('W', 'Widowed'), ('D', 'Divorcee'), ('SP', 'Single Parent')], default='M', help_text='Please select Civit Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='religion',
            field=models.CharField(blank=True, choices=[('C', 'Catholic'), ('M', 'Muslim'), ('B', 'Buddhist'), ('I', 'INC')], default='C', help_text='Please select Religion', max_length=30),
        ),
        migrations.AlterField(
            model_name='illnessinfo',
            name='illnessinfo',
            field=models.CharField(choices=[('EP', 'Ear Problems'), ('ANE', 'Anemia'), ('VP', 'Viral Infection'), ('DP', 'Dermatology Problem'), ('GP', 'Gastrointestinal Problems'), ('O', 'Others'), ('AST', 'Asthma'), ('HP', 'Heart Problem'), ('MP', 'Metabolc Problem'), ('CV', 'Convulsion'), ('DM', 'Diabetes Mellitus'), ('EPL', 'Epilepsy'), ('TP', 'Thyroid Problem'), ('LP', 'Lung Problem'), ('HMP', 'Hematologic Problem'), ('HT', 'Hypertension'), ('A', 'Allergy'), ('SZ', 'Seizures')], default='A', max_length=64, verbose_name='Illness Information'),
        ),
        migrations.AlterField(
            model_name='presentcondition',
            name='currentcondition',
            field=models.CharField(choices=[('D', 'DIARRHEA'), ('C', 'COLDS'), ('V', 'VOMITING'), ('CO', 'COUGH'), ('L', 'LBM'), ('H', 'HEADACHE'), ('S', 'STOMACH ACHE'), ('0', 'OTHERS'), ('F', 'FEVER')], max_length=64, verbose_name='Current Medical Condition'),
        ),
        migrations.AlterField(
            model_name='studentgrades',
            name='grades',
            field=models.CharField(choices=[('97-100', 'E'), ('92-96', 'A'), ('77-81', 'D'), ('82-86', 'AP'), ('76', 'B'), ('87-91', 'P')], default='B', help_text='Choose appropriate marks', max_length=64, verbose_name='Grading System'),
        ),
        migrations.AlterField(
            model_name='students',
            name='groupinfo',
            field=models.CharField(blank=True, choices=[('G9', 'GRADE 9'), ('CM', 'CASA AM'), ('PG', 'PLAY GROUP'), ('G5', 'GRADE 5'), ('TEP-GR2', 'TEACH PM GRADE 3'), ('G3', 'GRADE 3'), ('TEA', 'TEACH AM'), ('TEP-GR2', 'TEACH PM GRADE 2'), ('TEP-GR1', 'TEACH PM GRADE 1'), ('G1', 'GRADE 1'), ('CA', 'CASA AFTERNOON 1:30'), ('G2', 'GRADE 2'), ('G4', 'GRADE 4'), ('TEP', 'TEACH PM'), ('G10', 'GRADE 10'), ('G6', 'GRADE 6'), ('G7', 'GRADE 7'), ('G8', 'GRADE 8')], default='CM', help_text='Choose Group for Students', max_length=10),
        ),
    ]
