# Generated by Django 2.0.6 on 2018-07-26 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0097_auto_20180726_0346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testsoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musicprice', models.DecimalField(decimal_places=6, max_digits=20, verbose_name='music price test')),
                ('bookprice', models.DecimalField(decimal_places=6, max_digits=20, verbose_name='book price')),
                ('uniprice', models.DecimalField(decimal_places=6, max_digits=20, verbose_name='uniform')),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='applicationtype',
            field=models.CharField(blank=True, choices=[('GRADE SCHOOL PROGRAM', 'Grade School Program'), ('SPED', 'Special Education Program'), ('JUNIOR HIGH SCHOOL PROGRAM', 'Junior High School Program'), ('CASA PROGRAM', 'CASA Program'), ('SENIOR HIGH SCHOOL PROGRAM', 'Senior High School Program')], default='CASA PROGRAM', help_text='Choose Application Program', max_length=64),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='civilstatus',
            field=models.CharField(blank=True, choices=[('M', 'Married'), ('D', 'Divorcee'), ('SP', 'Single Parent'), ('W', 'Widowed')], default='M', help_text='Please select Civit Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='religion',
            field=models.CharField(blank=True, choices=[('M', 'Muslim'), ('I', 'INC'), ('B', 'Buddhist'), ('C', 'Catholic')], default='C', help_text='Please select Religion', max_length=30),
        ),
        migrations.AlterField(
            model_name='illnessinfo',
            name='illnessinfo',
            field=models.CharField(choices=[('LP', 'Lung Problem'), ('HP', 'Heart Problem'), ('ANE', 'Anemia'), ('MP', 'Metabolc Problem'), ('O', 'Others'), ('HT', 'Hypertension'), ('DP', 'Dermatology Problem'), ('A', 'Allergy'), ('EP', 'Ear Problems'), ('HMP', 'Hematologic Problem'), ('GP', 'Gastrointestinal Problems'), ('TP', 'Thyroid Problem'), ('EPL', 'Epilepsy'), ('VP', 'Viral Infection'), ('AST', 'Asthma'), ('CV', 'Convulsion'), ('SZ', 'Seizures'), ('DM', 'Diabetes Mellitus')], default='A', max_length=64, verbose_name='Illness Information'),
        ),
        migrations.AlterField(
            model_name='presentcondition',
            name='currentcondition',
            field=models.CharField(choices=[('C', 'COLDS'), ('F', 'FEVER'), ('0', 'OTHERS'), ('L', 'LBM'), ('D', 'DIARRHEA'), ('S', 'STOMACH ACHE'), ('V', 'VOMITING'), ('H', 'HEADACHE'), ('CO', 'COUGH')], max_length=64, verbose_name='Current Medical Condition'),
        ),
        migrations.AlterField(
            model_name='statementaccount',
            name='modeofpayment',
            field=models.CharField(choices=[('SA', 'SEMI-ANNUAL'), ('QRT', 'QUARTERLY'), ('A', 'ANNUAL')], default='A', help_text='Choose Terms of Payment', max_length=64, verbose_name='Mode of Payment'),
        ),
        migrations.AlterField(
            model_name='studentgrades',
            name='grades',
            field=models.CharField(choices=[('82-86', 'AP'), ('76', 'B'), ('87-91', 'P'), ('92-96', 'A'), ('97-100', 'E'), ('77-81', 'D')], default='B', help_text='Choose appropriate marks', max_length=64, verbose_name='Grading System'),
        ),
        migrations.AlterField(
            model_name='students',
            name='groupinfo',
            field=models.CharField(blank=True, choices=[('G1', 'GRADE 1'), ('G2', 'GRADE 2'), ('G10', 'GRADE 10'), ('G6', 'GRADE 6'), ('TEP-GR2', 'TEACH PM GRADE 2'), ('G8', 'GRADE 8'), ('TEA', 'TEACH AM'), ('CA', 'CASA AFTERNOON 1:30'), ('PG', 'PLAY GROUP'), ('G5', 'GRADE 5'), ('G7', 'GRADE 7'), ('G9', 'GRADE 9'), ('TEP', 'TEACH PM'), ('TEP-GR2', 'TEACH PM GRADE 3'), ('TEP-GR1', 'TEACH PM GRADE 1'), ('CM', 'CASA AM'), ('G3', 'GRADE 3'), ('G4', 'GRADE 4')], default='CM', help_text='Choose Group for Students', max_length=10),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='rolegroup',
            field=models.CharField(blank=True, choices=[('SH', 'SCHOOL HEAD'), ('S', 'STAFF'), ('F', 'FACULTY')], default='F', help_text='Please choose Role / Duty', max_length=10),
        ),
    ]
