# Generated by Django 2.0.6 on 2018-07-27 03:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0099_auto_20180726_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentbio',
            name='profilepic',
            field=models.ImageField(blank=True, upload_to='profile_image', verbose_name='Student Profile Picture'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='applicationtype',
            field=models.CharField(blank=True, choices=[('SENIOR HIGH SCHOOL PROGRAM', 'Senior High School Program'), ('GRADE SCHOOL PROGRAM', 'Grade School Program'), ('CASA PROGRAM', 'CASA Program'), ('JUNIOR HIGH SCHOOL PROGRAM', 'Junior High School Program'), ('SPED', 'Special Education Program')], default='CASA PROGRAM', help_text='Choose Application Program', max_length=64),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='civilstatus',
            field=models.CharField(blank=True, choices=[('D', 'Divorcee'), ('W', 'Widowed'), ('SP', 'Single Parent'), ('M', 'Married')], default='M', help_text='Please select Civit Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='dateupdatedbio',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Updated'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='dateuserjoined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Registered'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profilepic',
            field=models.ImageField(blank=True, upload_to='profile_image', verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='religion',
            field=models.CharField(blank=True, choices=[('B', 'Buddhist'), ('I', 'INC'), ('C', 'Catholic'), ('M', 'Muslim')], default='C', help_text='Please select Religion', max_length=30),
        ),
        migrations.AlterField(
            model_name='illnessinfo',
            name='illnessinfo',
            field=models.CharField(choices=[('HMP', 'Hematologic Problem'), ('CV', 'Convulsion'), ('HT', 'Hypertension'), ('SZ', 'Seizures'), ('TP', 'Thyroid Problem'), ('EP', 'Ear Problems'), ('LP', 'Lung Problem'), ('A', 'Allergy'), ('EPL', 'Epilepsy'), ('GP', 'Gastrointestinal Problems'), ('MP', 'Metabolc Problem'), ('VP', 'Viral Infection'), ('O', 'Others'), ('ANE', 'Anemia'), ('AST', 'Asthma'), ('HP', 'Heart Problem'), ('DM', 'Diabetes Mellitus'), ('DP', 'Dermatology Problem')], default='A', max_length=64, verbose_name='Illness Information'),
        ),
        migrations.AlterField(
            model_name='presentcondition',
            name='currentcondition',
            field=models.CharField(choices=[('V', 'VOMITING'), ('C', 'COLDS'), ('L', 'LBM'), ('H', 'HEADACHE'), ('CO', 'COUGH'), ('0', 'OTHERS'), ('F', 'FEVER'), ('D', 'DIARRHEA'), ('S', 'STOMACH ACHE')], max_length=64, verbose_name='Current Medical Condition'),
        ),
        migrations.AlterField(
            model_name='statementaccount',
            name='modeofpayment',
            field=models.CharField(choices=[('A', 'ANNUAL'), ('QRT', 'QUARTERLY'), ('SA', 'SEMI-ANNUAL')], default='A', help_text='Choose Terms of Payment', max_length=64, verbose_name='Mode of Payment'),
        ),
        migrations.AlterField(
            model_name='studentgrades',
            name='grades',
            field=models.CharField(choices=[('82-86', 'AP'), ('87-91', 'P'), ('97-100', 'E'), ('92-96', 'A'), ('77-81', 'D'), ('76', 'B')], default='B', help_text='Choose appropriate marks', max_length=64, verbose_name='Grading System'),
        ),
        migrations.AlterField(
            model_name='students',
            name='groupinfo',
            field=models.CharField(blank=True, choices=[('G4', 'GRADE 4'), ('G10', 'GRADE 10'), ('TEP', 'TEACH PM'), ('TEP-GR2', 'TEACH PM GRADE 3'), ('PG', 'PLAY GROUP'), ('G9', 'GRADE 9'), ('TEP-GR1', 'TEACH PM GRADE 1'), ('G2', 'GRADE 2'), ('G5', 'GRADE 5'), ('TEP-GR2', 'TEACH PM GRADE 2'), ('G8', 'GRADE 8'), ('CM', 'CASA AM'), ('G6', 'GRADE 6'), ('G1', 'GRADE 1'), ('G7', 'GRADE 7'), ('G3', 'GRADE 3'), ('CA', 'CASA AFTERNOON 1:30'), ('TEA', 'TEACH AM')], default='CM', help_text='Choose Group for Students', max_length=10),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='rolegroup',
            field=models.CharField(blank=True, choices=[('F', 'FACULTY'), ('SH', 'SCHOOL HEAD'), ('S', 'STAFF')], default='F', help_text='Please choose Role / Duty', max_length=10),
        ),
    ]
