# Generated by Django 2.0.6 on 2018-07-29 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0100_auto_20180727_0353'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='studentbioidinfo',
            field=models.ForeignKey(max_length=10, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.StudentBio'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='applicationtype',
            field=models.CharField(blank=True, choices=[('SPED', 'Special Education Program'), ('CASA PROGRAM', 'CASA Program'), ('GRADE SCHOOL PROGRAM', 'Grade School Program'), ('SENIOR HIGH SCHOOL PROGRAM', 'Senior High School Program'), ('JUNIOR HIGH SCHOOL PROGRAM', 'Junior High School Program')], default='CASA PROGRAM', help_text='Choose Application Program', max_length=64),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='civilstatus',
            field=models.CharField(blank=True, choices=[('D', 'Divorcee'), ('SP', 'Single Parent'), ('W', 'Widowed'), ('M', 'Married')], default='M', help_text='Please select Civit Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='religion',
            field=models.CharField(blank=True, choices=[('M', 'Muslim'), ('B', 'Buddhist'), ('I', 'INC'), ('C', 'Catholic')], default='C', help_text='Please select Religion', max_length=30),
        ),
        migrations.AlterField(
            model_name='illnessinfo',
            name='illnessinfo',
            field=models.CharField(choices=[('EP', 'Ear Problems'), ('HP', 'Heart Problem'), ('HT', 'Hypertension'), ('EPL', 'Epilepsy'), ('A', 'Allergy'), ('DP', 'Dermatology Problem'), ('LP', 'Lung Problem'), ('GP', 'Gastrointestinal Problems'), ('VP', 'Viral Infection'), ('SZ', 'Seizures'), ('AST', 'Asthma'), ('DM', 'Diabetes Mellitus'), ('MP', 'Metabolc Problem'), ('HMP', 'Hematologic Problem'), ('TP', 'Thyroid Problem'), ('CV', 'Convulsion'), ('ANE', 'Anemia'), ('O', 'Others')], default='A', max_length=64, verbose_name='Illness Information'),
        ),
        migrations.AlterField(
            model_name='presentcondition',
            name='currentcondition',
            field=models.CharField(choices=[('0', 'OTHERS'), ('CO', 'COUGH'), ('L', 'LBM'), ('C', 'COLDS'), ('D', 'DIARRHEA'), ('V', 'VOMITING'), ('F', 'FEVER'), ('S', 'STOMACH ACHE'), ('H', 'HEADACHE')], max_length=64, verbose_name='Current Medical Condition'),
        ),
        migrations.AlterField(
            model_name='statementaccount',
            name='modeofpayment',
            field=models.CharField(choices=[('QRT', 'QUARTERLY'), ('SA', 'SEMI-ANNUAL'), ('A', 'ANNUAL')], default='A', help_text='Choose Terms of Payment', max_length=64, verbose_name='Mode of Payment'),
        ),
        migrations.AlterField(
            model_name='studentgrades',
            name='grades',
            field=models.CharField(choices=[('82-86', 'AP'), ('92-96', 'A'), ('76', 'B'), ('87-91', 'P'), ('97-100', 'E'), ('77-81', 'D')], default='B', help_text='Choose appropriate marks', max_length=64, verbose_name='Grading System'),
        ),
        migrations.AlterField(
            model_name='students',
            name='groupinfo',
            field=models.CharField(blank=True, choices=[('GRADE 7', 'G7'), ('TEACH PM GRADE 2', 'TEP-GR2'), ('CASA AM', 'CM'), ('GRADE 4', 'G4'), ('TEACH AM', 'TEA'), ('GRADE 8', 'G8'), ('PLAY GROUP', 'PG'), ('CASA AFTERNOON 1:30', 'CA'), ('GRADE 6', 'G6'), ('GRADE 3', 'G3'), ('GRADE 2', 'G2'), ('GRADE 5', 'G5'), ('GRADE 1', 'G1'), ('TEACH PM GRADE 3', 'TEP-GR3'), ('TEACH PM GRADE 1', 'TEP=GR1'), ('GRADE 10', 'G10'), ('GRADE 9', 'G9'), ('TEACH PM', 'TEP')], default='CASA AM', help_text='Choose Group for Students', max_length=10),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='rolegroup',
            field=models.CharField(blank=True, choices=[('SH', 'SCHOOL HEAD'), ('S', 'STAFF'), ('F', 'FACULTY')], default='F', help_text='Please choose Role / Duty', max_length=10),
        ),
    ]
