# Generated by Django 2.0.6 on 2018-07-31 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0102_auto_20180730_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testpayment1', models.DecimalField(decimal_places=6, max_digits=20, verbose_name='Mode of Payment')),
                ('testpayment2', models.DecimalField(decimal_places=6, max_digits=20, verbose_name='Mode of Payment Price')),
            ],
        ),
        migrations.AlterField(
            model_name='characterratings',
            name='chargrades',
            field=models.CharField(choices=[('NEEDS IMPROVEMENT', 'NI'), ('EXCELLENT', 'E'), ('GOOD', 'G'), ('UNSATISFACTORY / FAILED', 'U'), ('FAIR / PASSED', 'F'), ('VERY GOOD', 'VG')], default='EXCELLENT', help_text='Choose the appropriate grade', max_length=6, verbose_name='Character Rates'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='applicationtype',
            field=models.CharField(blank=True, choices=[('CASA PROGRAM', 'CASA Program'), ('SENIOR HIGH SCHOOL PROGRAM', 'Senior High School Program'), ('GRADE SCHOOL PROGRAM', 'Grade School Program'), ('SPED', 'Special Education Program'), ('JUNIOR HIGH SCHOOL PROGRAM', 'Junior High School Program')], default='CASA PROGRAM', help_text='Choose Application Program', max_length=64),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='civilstatus',
            field=models.CharField(blank=True, choices=[('M', 'Married'), ('SP', 'Single Parent'), ('W', 'Widowed'), ('D', 'Divorcee')], default='M', help_text='Please select Civit Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='religion',
            field=models.CharField(blank=True, choices=[('M', 'Muslim'), ('C', 'Catholic'), ('B', 'Buddhist'), ('I', 'INC')], default='C', help_text='Please select Religion', max_length=30),
        ),
        migrations.AlterField(
            model_name='illnessinfo',
            name='illnessinfo',
            field=models.CharField(choices=[('LP', 'Lung Problem'), ('HT', 'Hypertension'), ('ANE', 'Anemia'), ('HMP', 'Hematologic Problem'), ('AST', 'Asthma'), ('VP', 'Viral Infection'), ('SZ', 'Seizures'), ('O', 'Others'), ('GP', 'Gastrointestinal Problems'), ('MP', 'Metabolc Problem'), ('DM', 'Diabetes Mellitus'), ('EP', 'Ear Problems'), ('DP', 'Dermatology Problem'), ('CV', 'Convulsion'), ('A', 'Allergy'), ('HP', 'Heart Problem'), ('EPL', 'Epilepsy'), ('TP', 'Thyroid Problem')], default='A', max_length=64, verbose_name='Illness Information'),
        ),
        migrations.AlterField(
            model_name='presentcondition',
            name='currentcondition',
            field=models.CharField(choices=[('V', 'VOMITING'), ('D', 'DIARRHEA'), ('H', 'HEADACHE'), ('0', 'OTHERS'), ('C', 'COLDS'), ('CO', 'COUGH'), ('S', 'STOMACH ACHE'), ('F', 'FEVER'), ('L', 'LBM')], max_length=64, verbose_name='Current Medical Condition'),
        ),
        migrations.AlterField(
            model_name='statementaccount',
            name='modeofpayment',
            field=models.CharField(choices=[('A', 'ANNUAL'), ('QRT', 'QUARTERLY'), ('SA', 'SEMI-ANNUAL')], default='A', help_text='Choose Terms of Payment', max_length=64, verbose_name='Mode of Payment'),
        ),
        migrations.AlterField(
            model_name='studentgrades',
            name='grades',
            field=models.CharField(choices=[('92-96', 'A'), ('82-86', 'AP'), ('87-91', 'P'), ('76', 'B'), ('77-81', 'D'), ('97-100', 'E')], default='B', help_text='Choose appropriate marks', max_length=64, verbose_name='Grading System'),
        ),
        migrations.AlterField(
            model_name='students',
            name='groupinfo',
            field=models.CharField(blank=True, choices=[('TEACH PM GRADE 2', 'TEP-GR2'), ('TEACH PM', 'TEP'), ('GRADE 7', 'G7'), ('CASA AM', 'CM'), ('GRADE 8', 'G8'), ('GRADE 10', 'G10'), ('TEACH PM GRADE 1', 'TEP=GR1'), ('CASA AFTERNOON 1:30', 'CA'), ('GRADE 3', 'G3'), ('GRADE 9', 'G9'), ('TEACH PM GRADE 3', 'TEP-GR3'), ('PLAY GROUP', 'PG'), ('GRADE 1', 'G1'), ('GRADE 2', 'G2'), ('TEACH AM', 'TEA'), ('GRADE 6', 'G6'), ('GRADE 4', 'G4'), ('GRADE 5', 'G5')], default='CASA AM', help_text='Choose Group for Students', max_length=10),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='rolegroup',
            field=models.CharField(blank=True, choices=[('S', 'STAFF'), ('SH', 'SCHOOL HEAD'), ('F', 'FACULTY')], default='F', help_text='Please choose Role / Duty', max_length=10),
        ),
        migrations.AddField(
            model_name='compute',
            name='studentname',
            field=models.ForeignKey(max_length=64, on_delete=django.db.models.deletion.CASCADE, to='students.Students', verbose_name='Student Name'),
        ),
    ]
