# Generated by Django 2.0.6 on 2018-07-31 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0104_auto_20180731_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='compute',
            name='gtotal',
            field=models.IntegerField(default='1234', verbose_name='Grand Total Price'),
        ),
        migrations.AlterField(
            model_name='characterratings',
            name='chargrades',
            field=models.CharField(choices=[('GOOD', 'G'), ('EXCELLENT', 'E'), ('VERY GOOD', 'VG'), ('FAIR / PASSED', 'F'), ('UNSATISFACTORY / FAILED', 'U'), ('NEEDS IMPROVEMENT', 'NI')], default='EXCELLENT', help_text='Choose the appropriate grade', max_length=6, verbose_name='Character Rates'),
        ),
        migrations.AlterField(
            model_name='compute',
            name='testpayment1',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Mode of Payment'),
        ),
        migrations.AlterField(
            model_name='compute',
            name='testpayment2',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Mode of Payment Price'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='applicationtype',
            field=models.CharField(blank=True, choices=[('SPED', 'Special Education Program'), ('GRADE SCHOOL PROGRAM', 'Grade School Program'), ('JUNIOR HIGH SCHOOL PROGRAM', 'Junior High School Program'), ('SENIOR HIGH SCHOOL PROGRAM', 'Senior High School Program'), ('CASA PROGRAM', 'CASA Program')], default='CASA PROGRAM', help_text='Choose Application Program', max_length=64),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='civilstatus',
            field=models.CharField(blank=True, choices=[('D', 'Divorcee'), ('M', 'Married'), ('SP', 'Single Parent'), ('W', 'Widowed')], default='M', help_text='Please select Civit Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='religion',
            field=models.CharField(blank=True, choices=[('C', 'Catholic'), ('M', 'Muslim'), ('I', 'INC'), ('B', 'Buddhist')], default='C', help_text='Please select Religion', max_length=30),
        ),
        migrations.AlterField(
            model_name='illnessinfo',
            name='illnessinfo',
            field=models.CharField(choices=[('DP', 'Dermatology Problem'), ('HP', 'Heart Problem'), ('TP', 'Thyroid Problem'), ('A', 'Allergy'), ('EPL', 'Epilepsy'), ('CV', 'Convulsion'), ('ANE', 'Anemia'), ('HMP', 'Hematologic Problem'), ('VP', 'Viral Infection'), ('MP', 'Metabolc Problem'), ('DM', 'Diabetes Mellitus'), ('AST', 'Asthma'), ('GP', 'Gastrointestinal Problems'), ('SZ', 'Seizures'), ('LP', 'Lung Problem'), ('O', 'Others'), ('EP', 'Ear Problems'), ('HT', 'Hypertension')], default='A', max_length=64, verbose_name='Illness Information'),
        ),
        migrations.AlterField(
            model_name='presentcondition',
            name='currentcondition',
            field=models.CharField(choices=[('F', 'FEVER'), ('S', 'STOMACH ACHE'), ('C', 'COLDS'), ('L', 'LBM'), ('CO', 'COUGH'), ('V', 'VOMITING'), ('H', 'HEADACHE'), ('D', 'DIARRHEA'), ('0', 'OTHERS')], max_length=64, verbose_name='Current Medical Condition'),
        ),
        migrations.AlterField(
            model_name='statementaccount',
            name='modeofpayment',
            field=models.CharField(choices=[('A', 'ANNUAL'), ('QRT', 'QUARTERLY'), ('SA', 'SEMI-ANNUAL')], default='A', help_text='Choose Terms of Payment', max_length=64, verbose_name='Mode of Payment'),
        ),
        migrations.AlterField(
            model_name='studentgrades',
            name='grades',
            field=models.CharField(choices=[('97-100', 'E'), ('82-86', 'AP'), ('76', 'B'), ('77-81', 'D'), ('87-91', 'P'), ('92-96', 'A')], default='B', help_text='Choose appropriate marks', max_length=64, verbose_name='Grading System'),
        ),
        migrations.AlterField(
            model_name='students',
            name='groupinfo',
            field=models.CharField(blank=True, choices=[('GRADE 6', 'G6'), ('TEACH PM GRADE 2', 'TEP-GR2'), ('TEACH AM', 'TEA'), ('TEACH PM GRADE 1', 'TEP=GR1'), ('PLAY GROUP', 'PG'), ('GRADE 2', 'G2'), ('GRADE 4', 'G4'), ('GRADE 8', 'G8'), ('CASA AM', 'CM'), ('GRADE 1', 'G1'), ('GRADE 10', 'G10'), ('GRADE 7', 'G7'), ('GRADE 9', 'G9'), ('CASA AFTERNOON 1:30', 'CA'), ('GRADE 5', 'G5'), ('TEACH PM', 'TEP'), ('GRADE 3', 'G3'), ('TEACH PM GRADE 3', 'TEP-GR3')], default='CASA AM', help_text='Choose Group for Students', max_length=10),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='rolegroup',
            field=models.CharField(blank=True, choices=[('SH', 'SCHOOL HEAD'), ('S', 'STAFF'), ('F', 'FACULTY')], default='F', help_text='Please choose Role / Duty', max_length=10),
        ),
    ]
