# Generated by Django 2.0.6 on 2018-07-31 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0105_auto_20180731_0912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compute',
            name='gtotal',
        ),
        migrations.AlterField(
            model_name='characterratings',
            name='chargrades',
            field=models.CharField(choices=[('UNSATISFACTORY / FAILED', 'U'), ('FAIR / PASSED', 'F'), ('GOOD', 'G'), ('EXCELLENT', 'E'), ('VERY GOOD', 'VG'), ('NEEDS IMPROVEMENT', 'NI')], default='EXCELLENT', help_text='Choose the appropriate grade', max_length=6, verbose_name='Character Rates'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='applicationtype',
            field=models.CharField(blank=True, choices=[('JUNIOR HIGH SCHOOL PROGRAM', 'Junior High School Program'), ('CASA PROGRAM', 'CASA Program'), ('SENIOR HIGH SCHOOL PROGRAM', 'Senior High School Program'), ('GRADE SCHOOL PROGRAM', 'Grade School Program'), ('SPED', 'Special Education Program')], default='CASA PROGRAM', help_text='Choose Application Program', max_length=64),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='civilstatus',
            field=models.CharField(blank=True, choices=[('W', 'Widowed'), ('D', 'Divorcee'), ('SP', 'Single Parent'), ('M', 'Married')], default='M', help_text='Please select Civit Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='religion',
            field=models.CharField(blank=True, choices=[('B', 'Buddhist'), ('M', 'Muslim'), ('C', 'Catholic'), ('I', 'INC')], default='C', help_text='Please select Religion', max_length=30),
        ),
        migrations.AlterField(
            model_name='illnessinfo',
            name='illnessinfo',
            field=models.CharField(choices=[('HMP', 'Hematologic Problem'), ('DM', 'Diabetes Mellitus'), ('HP', 'Heart Problem'), ('HT', 'Hypertension'), ('ANE', 'Anemia'), ('AST', 'Asthma'), ('MP', 'Metabolc Problem'), ('EPL', 'Epilepsy'), ('GP', 'Gastrointestinal Problems'), ('SZ', 'Seizures'), ('TP', 'Thyroid Problem'), ('DP', 'Dermatology Problem'), ('LP', 'Lung Problem'), ('EP', 'Ear Problems'), ('CV', 'Convulsion'), ('O', 'Others'), ('A', 'Allergy'), ('VP', 'Viral Infection')], default='A', max_length=64, verbose_name='Illness Information'),
        ),
        migrations.AlterField(
            model_name='presentcondition',
            name='currentcondition',
            field=models.CharField(choices=[('H', 'HEADACHE'), ('S', 'STOMACH ACHE'), ('0', 'OTHERS'), ('C', 'COLDS'), ('F', 'FEVER'), ('L', 'LBM'), ('D', 'DIARRHEA'), ('CO', 'COUGH'), ('V', 'VOMITING')], max_length=64, verbose_name='Current Medical Condition'),
        ),
        migrations.AlterField(
            model_name='studentgrades',
            name='grades',
            field=models.CharField(choices=[('77-81', 'D'), ('82-86', 'AP'), ('97-100', 'E'), ('76', 'B'), ('92-96', 'A'), ('87-91', 'P')], default='B', help_text='Choose appropriate marks', max_length=64, verbose_name='Grading System'),
        ),
        migrations.AlterField(
            model_name='students',
            name='groupinfo',
            field=models.CharField(blank=True, choices=[('TEACH PM', 'TEP'), ('TEACH PM GRADE 1', 'TEP=GR1'), ('PLAY GROUP', 'PG'), ('TEACH PM GRADE 2', 'TEP-GR2'), ('CASA AM', 'CM'), ('TEACH PM GRADE 3', 'TEP-GR3'), ('GRADE 2', 'G2'), ('GRADE 8', 'G8'), ('TEACH AM', 'TEA'), ('GRADE 10', 'G10'), ('GRADE 6', 'G6'), ('GRADE 3', 'G3'), ('GRADE 5', 'G5'), ('GRADE 7', 'G7'), ('GRADE 4', 'G4'), ('GRADE 9', 'G9'), ('GRADE 1', 'G1'), ('CASA AFTERNOON 1:30', 'CA')], default='CASA AM', help_text='Choose Group for Students', max_length=10),
        ),
    ]
