# Generated by Django 2.0.6 on 2018-07-31 23:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0108_auto_20180731_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='immunisationinfo',
            name='endperiodimmune',
            field=models.DateField(default=datetime.date.today, verbose_name='Date Ended'),
        ),
        migrations.AddField(
            model_name='immunisationinfo',
            name='immunedetails',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Immunisation Details'),
        ),
        migrations.AddField(
            model_name='immunisationinfo',
            name='immuneinfo',
            field=models.CharField(choices=[('NONE', 'NONE'), ('BCG', 'BCG'), ('DPT1', 'DPT1'), ('DPT2', 'DPT2'), ('DPT3', 'DPT3'), ('DPTB1', 'DPT Booster 1'), ('DPTB2', 'DPT Booster 2'), ('DPTB3', 'DPT Booster 3 range 13-19 years old'), ('PLIO1', 'POLIO 1'), ('PLIO2', 'POLIO 2'), ('PLIO3', 'POLIO 3'), ('PB1', 'POLIO BOOSTER 1'), ('PB2', 'POLIO BOOSTER 2'), ('HIB1', 'HIB 1'), ('HIB2', 'HIB 2'), ('HIB3', 'HIB 3'), ('HIBB', 'HIB BOOSTER'), ('MSLS', 'MEASLES'), ('MMR', 'MMR'), ('MMRB', 'MMRB'), ('HPB1', 'HEPATITIS B1'), ('HPB2', 'HEPATITIS B2'), ('HPB3', 'HEPATITIS B3'), ('HPBB', 'HEPATITIS B BOOSTER'), ('HPA1', 'HEPATITIS A1'), ('HPA2', 'HEPATITIS A2'), ('VRCL', 'VARICELLA - CHICKEN POX'), ('INFLZ', 'INFLUENZA'), ('TYPHD', 'TYPHOID')], default='NONE', max_length=64, verbose_name='Immunisation Choices'),
        ),
        migrations.AddField(
            model_name='immunisationinfo',
            name='startperiodofimmune',
            field=models.DateField(default=datetime.date.today, verbose_name='Date Started'),
        ),
        migrations.AddField(
            model_name='immunisationinfo',
            name='treatmentdetails',
            field=models.CharField(blank=True, help_text='If under treatment, please indicate dosage of drug', max_length=64, null=True, verbose_name='Treatment Details'),
        ),
        migrations.AlterField(
            model_name='characterratings',
            name='chargrades',
            field=models.CharField(choices=[('NEEDS IMPROVEMENT', 'NI'), ('EXCELLENT', 'E'), ('VERY GOOD', 'VG'), ('GOOD', 'G'), ('FAIR / PASSED', 'F'), ('UNSATISFACTORY / FAILED', 'U')], default='EXCELLENT', help_text='Choose the appropriate grade', max_length=6, verbose_name='Character Rates'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='applicationtype',
            field=models.CharField(blank=True, choices=[('GRADE SCHOOL PROGRAM', 'Grade School Program'), ('SPED', 'Special Education Program'), ('SENIOR HIGH SCHOOL PROGRAM', 'Senior High School Program'), ('CASA PROGRAM', 'CASA Program'), ('JUNIOR HIGH SCHOOL PROGRAM', 'Junior High School Program')], default='CASA PROGRAM', help_text='Choose Application Program', max_length=64),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='civilstatus',
            field=models.CharField(blank=True, choices=[('SP', 'Single Parent'), ('D', 'Divorcee'), ('M', 'Married'), ('W', 'Widowed')], default='M', help_text='Please select Civit Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='illnessinfo',
            name='illnessinfo',
            field=models.CharField(choices=[('EP', 'Ear Problems'), ('LP', 'Lung Problem'), ('DP', 'Dermatology Problem'), ('HMP', 'Hematologic Problem'), ('HT', 'Hypertension'), ('ANE', 'Anemia'), ('MP', 'Metabolc Problem'), ('TP', 'Thyroid Problem'), ('AST', 'Asthma'), ('CV', 'Convulsion'), ('HP', 'Heart Problem'), ('O', 'Others'), ('A', 'Allergy'), ('DM', 'Diabetes Mellitus'), ('VP', 'Viral Infection'), ('EPL', 'Epilepsy'), ('GP', 'Gastrointestinal Problems'), ('SZ', 'Seizures')], default='A', max_length=64, verbose_name='Illness Information'),
        ),
        migrations.AlterField(
            model_name='presentcondition',
            name='currentcondition',
            field=models.CharField(choices=[('C', 'COLDS'), ('L', 'LBM'), ('H', 'HEADACHE'), ('V', 'VOMITING'), ('F', 'FEVER'), ('D', 'DIARRHEA'), ('CO', 'COUGH'), ('0', 'OTHERS'), ('S', 'STOMACH ACHE')], max_length=64, verbose_name='Current Medical Condition'),
        ),
        migrations.AlterField(
            model_name='studentgrades',
            name='grades',
            field=models.CharField(choices=[('76', 'B'), ('97-100', 'E'), ('87-91', 'P'), ('77-81', 'D'), ('92-96', 'A'), ('82-86', 'AP')], default='B', help_text='Choose appropriate marks', max_length=64, verbose_name='Grading System'),
        ),
        migrations.AlterField(
            model_name='students',
            name='groupinfo',
            field=models.CharField(blank=True, choices=[('GRADE 10', 'G10'), ('GRADE 1', 'G1'), ('TEACH AM', 'TEA'), ('GRADE 3', 'G3'), ('GRADE 9', 'G9'), ('GRADE 6', 'G6'), ('CASA AM', 'CM'), ('GRADE 2', 'G2'), ('TEACH PM GRADE 2', 'TEP-GR2'), ('GRADE 4', 'G4'), ('CASA AFTERNOON 1:30', 'CA'), ('GRADE 8', 'G8'), ('TEACH PM GRADE 3', 'TEP-GR3'), ('TEACH PM', 'TEP'), ('PLAY GROUP', 'PG'), ('TEACH PM GRADE 1', 'TEP=GR1'), ('GRADE 5', 'G5'), ('GRADE 7', 'G7')], default='CASA AM', help_text='Choose Group for Students', max_length=10),
        ),
    ]
