# Generated by Django 2.0.6 on 2018-08-01 00:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0109_auto_20180731_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentcondition',
            name='user',
            field=models.ForeignKey(max_length=64, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=' Parents Name '),
        ),
        migrations.AlterField(
            model_name='characterratings',
            name='chargrades',
            field=models.CharField(choices=[('FAIR / PASSED', 'F'), ('EXCELLENT', 'E'), ('VERY GOOD', 'VG'), ('UNSATISFACTORY / FAILED', 'U'), ('NEEDS IMPROVEMENT', 'NI'), ('GOOD', 'G')], default='EXCELLENT', help_text='Choose the appropriate grade', max_length=64, verbose_name='Character Rates'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='applicationtype',
            field=models.CharField(blank=True, choices=[('SPED', 'Special Education Program'), ('CASA PROGRAM', 'CASA Program'), ('GRADE SCHOOL PROGRAM', 'Grade School Program'), ('JUNIOR HIGH SCHOOL PROGRAM', 'Junior High School Program'), ('SENIOR HIGH SCHOOL PROGRAM', 'Senior High School Program')], default='CASA PROGRAM', help_text='Choose Application Program', max_length=64),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='civilstatus',
            field=models.CharField(blank=True, choices=[('W', 'Widowed'), ('D', 'Divorcee'), ('SP', 'Single Parent'), ('M', 'Married')], default='M', help_text='Please select Civit Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='religion',
            field=models.CharField(blank=True, choices=[('M', 'Muslim'), ('C', 'Catholic'), ('I', 'INC'), ('B', 'Buddhist')], default='C', help_text='Please select Religion', max_length=30),
        ),
        migrations.AlterField(
            model_name='illnessinfo',
            name='illnessinfo',
            field=models.CharField(choices=[('HMP', 'Hematologic Problem'), ('MP', 'Metabolc Problem'), ('O', 'Others'), ('VP', 'Viral Infection'), ('SZ', 'Seizures'), ('A', 'Allergy'), ('HT', 'Hypertension'), ('DP', 'Dermatology Problem'), ('ANE', 'Anemia'), ('EPL', 'Epilepsy'), ('EP', 'Ear Problems'), ('DM', 'Diabetes Mellitus'), ('HP', 'Heart Problem'), ('LP', 'Lung Problem'), ('CV', 'Convulsion'), ('GP', 'Gastrointestinal Problems'), ('AST', 'Asthma'), ('TP', 'Thyroid Problem')], default='A', max_length=64, verbose_name='Illness Information'),
        ),
        migrations.AlterField(
            model_name='immunisationinfo',
            name='immuneinfo',
            field=models.CharField(choices=[('NONE', 'NONE'), ('BCG', 'BCG'), ('DPT1', 'DPT1'), ('DPT2', 'DPT2'), ('DPT3', 'DPT3'), ('DPTB1', 'DPT Booster 1'), ('DPTB2', 'DPT Booster 2'), ('DPTB3', 'DPT Booster 3 range 13-19 years old'), ('POLIO 1', 'PLIO1'), ('POLIO2', 'PLIO2'), ('POLIO3', 'PLIO3'), ('POLIO BOOSTER 1', 'POLIO BOOSTER 1'), ('POLIO BOOSTER 2', 'POLIO BOOSTER 2'), ('HIB1', 'HIB 1'), ('HIB2', 'HIB 2'), ('HIB3', 'HIB 3'), ('HIB BOOSTER', 'HIB BOOSTER'), ('MEASLES', 'MEASLES'), ('MMR', 'MMR'), ('MMRB', 'MMRB'), ('HEPATITIS B1', 'HEPATITIS B1'), ('HEPATITIS B2', 'HEPATITIS B2'), ('HEPATITIS B3', 'HEPATITIS B3'), ('HEPATITIS B BOOSTER', 'HEPATITIS B BOOSTER'), ('HEPATITIS A1', 'HEPATITIS A1'), ('HEPATITIS A2', 'HEPATITIS A2'), ('VARICELLA - CHICKEN POX', 'VARICELLA - CHICKEN POX'), ('INFLUENZA', 'INFLUENZA'), ('TYPHOID', 'TYPHOID')], default='NONE', max_length=64, verbose_name='Immunisation Choices'),
        ),
        migrations.AlterField(
            model_name='presentcondition',
            name='currentcondition',
            field=models.CharField(choices=[('D', 'DIARRHEA'), ('C', 'COLDS'), ('H', 'HEADACHE'), ('F', 'FEVER'), ('V', 'VOMITING'), ('CO', 'COUGH'), ('S', 'STOMACH ACHE'), ('L', 'LBM'), ('0', 'OTHERS')], max_length=64, verbose_name='Current Medical Condition'),
        ),
        migrations.AlterField(
            model_name='statementaccount',
            name='modeofpayment',
            field=models.CharField(choices=[('QRT', 'QUARTERLY'), ('SA', 'SEMI-ANNUAL'), ('A', 'ANNUAL')], default='A', help_text='Choose Terms of Payment', max_length=64, verbose_name='Mode of Payment'),
        ),
        migrations.AlterField(
            model_name='studentgrades',
            name='grades',
            field=models.CharField(choices=[('76', 'B'), ('77-81', 'D'), ('92-96', 'A'), ('97-100', 'E'), ('87-91', 'P'), ('82-86', 'AP')], default='B', help_text='Choose appropriate marks', max_length=64, verbose_name='Grading System'),
        ),
        migrations.AlterField(
            model_name='students',
            name='groupinfo',
            field=models.CharField(blank=True, choices=[('CASA AM', 'CM'), ('GRADE 7', 'G7'), ('GRADE 4', 'G4'), ('GRADE 5', 'G5'), ('TEACH PM GRADE 2', 'TEP-GR2'), ('GRADE 2', 'G2'), ('GRADE 6', 'G6'), ('GRADE 1', 'G1'), ('TEACH AM', 'TEA'), ('CASA AFTERNOON 1:30', 'CA'), ('GRADE 8', 'G8'), ('GRADE 9', 'G9'), ('GRADE 3', 'G3'), ('PLAY GROUP', 'PG'), ('TEACH PM GRADE 3', 'TEP-GR3'), ('GRADE 10', 'G10'), ('TEACH PM GRADE 1', 'TEP=GR1'), ('TEACH PM', 'TEP')], default='CASA AM', help_text='Choose Group for Students', max_length=10),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='rolegroup',
            field=models.CharField(blank=True, choices=[('S', 'STAFF'), ('F', 'FACULTY'), ('SH', 'SCHOOL HEAD')], default='F', help_text='Please choose Role / Duty', max_length=10),
        ),
    ]
