# Generated by Django 2.0.6 on 2018-08-01 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0110_auto_20180801_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='accidentinfo',
            name='user',
            field=models.ForeignKey(max_length=64, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=' Parents Name '),
        ),
        migrations.AddField(
            model_name='hospitalinfo',
            name='user',
            field=models.ForeignKey(max_length=64, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=' Parents Name '),
        ),
        migrations.AddField(
            model_name='illnessinfo',
            name='user',
            field=models.ForeignKey(max_length=64, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=' Parents Name '),
        ),
        migrations.AddField(
            model_name='immunisationinfo',
            name='user',
            field=models.ForeignKey(max_length=64, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=' Parents Name '),
        ),
        migrations.AlterField(
            model_name='characterratings',
            name='chargrades',
            field=models.CharField(choices=[('FAIR / PASSED', 'F'), ('UNSATISFACTORY / FAILED', 'U'), ('NEEDS IMPROVEMENT', 'NI'), ('EXCELLENT', 'E'), ('VERY GOOD', 'VG'), ('GOOD', 'G')], default='EXCELLENT', help_text='Choose the appropriate grade', max_length=64, verbose_name='Character Rates'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='applicationtype',
            field=models.CharField(blank=True, choices=[('JUNIOR HIGH SCHOOL PROGRAM', 'Junior High School Program'), ('CASA PROGRAM', 'CASA Program'), ('SENIOR HIGH SCHOOL PROGRAM', 'Senior High School Program'), ('GRADE SCHOOL PROGRAM', 'Grade School Program'), ('SPED', 'Special Education Program')], default='CASA PROGRAM', help_text='Choose Application Program', max_length=64),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='civilstatus',
            field=models.CharField(blank=True, choices=[('M', 'Married'), ('SP', 'Single Parent'), ('D', 'Divorcee'), ('W', 'Widowed')], default='M', help_text='Please select Civit Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='religion',
            field=models.CharField(blank=True, choices=[('B', 'Buddhist'), ('C', 'Catholic'), ('M', 'Muslim'), ('I', 'INC')], default='C', help_text='Please select Religion', max_length=30),
        ),
        migrations.AlterField(
            model_name='illnessinfo',
            name='illnessinfo',
            field=models.CharField(choices=[('DM', 'Diabetes Mellitus'), ('SZ', 'Seizures'), ('ANE', 'Anemia'), ('HMP', 'Hematologic Problem'), ('MP', 'Metabolc Problem'), ('O', 'Others'), ('GP', 'Gastrointestinal Problems'), ('HP', 'Heart Problem'), ('HT', 'Hypertension'), ('LP', 'Lung Problem'), ('A', 'Allergy'), ('TP', 'Thyroid Problem'), ('DP', 'Dermatology Problem'), ('CV', 'Convulsion'), ('VP', 'Viral Infection'), ('EPL', 'Epilepsy'), ('AST', 'Asthma'), ('EP', 'Ear Problems')], default='A', max_length=64, verbose_name='Illness Information'),
        ),
        migrations.AlterField(
            model_name='presentcondition',
            name='currentcondition',
            field=models.CharField(choices=[('CO', 'COUGH'), ('0', 'OTHERS'), ('H', 'HEADACHE'), ('D', 'DIARRHEA'), ('C', 'COLDS'), ('S', 'STOMACH ACHE'), ('L', 'LBM'), ('V', 'VOMITING'), ('F', 'FEVER')], max_length=64, verbose_name='Current Medical Condition'),
        ),
        migrations.AlterField(
            model_name='statementaccount',
            name='modeofpayment',
            field=models.CharField(choices=[('A', 'ANNUAL'), ('SA', 'SEMI-ANNUAL'), ('QRT', 'QUARTERLY')], default='A', help_text='Choose Terms of Payment', max_length=64, verbose_name='Mode of Payment'),
        ),
        migrations.AlterField(
            model_name='statementaccount',
            name='studentname',
            field=models.ForeignKey(max_length=64, on_delete=django.db.models.deletion.CASCADE, to='students.Students', verbose_name='Student Name DB'),
        ),
        migrations.AlterField(
            model_name='studentgrades',
            name='grades',
            field=models.CharField(choices=[('82-86', 'AP'), ('97-100', 'E'), ('92-96', 'A'), ('76', 'B'), ('87-91', 'P'), ('77-81', 'D')], default='B', help_text='Choose appropriate marks', max_length=64, verbose_name='Grading System'),
        ),
        migrations.AlterField(
            model_name='students',
            name='groupinfo',
            field=models.CharField(blank=True, choices=[('CASA AFTERNOON 1:30', 'CA'), ('TEACH PM GRADE 1', 'TEP=GR1'), ('CASA AM', 'CM'), ('GRADE 3', 'G3'), ('PLAY GROUP', 'PG'), ('GRADE 1', 'G1'), ('GRADE 8', 'G8'), ('TEACH AM', 'TEA'), ('GRADE 7', 'G7'), ('GRADE 10', 'G10'), ('GRADE 4', 'G4'), ('GRADE 9', 'G9'), ('GRADE 6', 'G6'), ('TEACH PM GRADE 3', 'TEP-GR3'), ('GRADE 2', 'G2'), ('GRADE 5', 'G5'), ('TEACH PM', 'TEP'), ('TEACH PM GRADE 2', 'TEP-GR2')], default='CASA AM', help_text='Choose Group for Students', max_length=10),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='rolegroup',
            field=models.CharField(blank=True, choices=[('S', 'STAFF'), ('SH', 'SCHOOL HEAD'), ('F', 'FACULTY')], default='F', help_text='Please choose Role / Duty', max_length=10),
        ),
    ]
